/**
 * Render the hydrated EcosystemNode[] to a self-contained TypeScript module
 * at `apps/web/lib/ecosystem/derived.ts`, including inlined type defs so the
 * web app does not need to import from @arcanea/orchestrator at build time.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import type { EcosystemNode, EcosystemEdge } from './schema.js';

export function renderDerivedTs(nodes: EcosystemNode[], generatedAt: string): string {
  const edges: EcosystemEdge[] = nodes.flatMap((n) =>
    n.consumes.map((dep) => ({ source: n.id, target: dep, kind: 'consumes' as const })),
  );

  const header = `// AUTO-GENERATED by @arcanea/orchestrator ecosystem:build.
// Do not edit by hand. Edit .arcanea/config/{repos.json,manifest.yaml} and re-run.

export type Layer = 'substrate' | 'product' | 'surface';
export type Gate = 'source' | 'form' | 'pattern' | 'voice' | 'vision' | 'story' | 'world' | 'soul' | 'unity' | 'mastery';
export type Hemisphere = 'arc' | 'nea' | 'seam';
export type Status = 'built' | 'shipped' | 'wip' | 'orphan' | 'sunset' | 'external';

export interface EcosystemNode {
  id: string;
  name: string;
  description: string;
  layer: Layer;
  gate: Gate;
  hemisphere: Hemisphere;
  status: Status;
  repo?: string;
  github?: string;
  publicUrl?: string;
  packageVersion?: string;
  lastCommitAt?: string;
  lastVerifiedAt: string;
  consumes: string[];
  consumedBy: string[];
  isExternal: boolean;
  owner?: string;
  links: Record<string, string>;
}

export interface EcosystemEdge {
  source: string;
  target: string;
  kind: 'consumes' | 'bridges' | 'routes' | 'references';
}
`;

  return `${header}
export const GENERATED_AT = ${JSON.stringify(generatedAt)};

export const NODES: EcosystemNode[] = ${JSON.stringify(nodes, null, 2)};

export const EDGES: EcosystemEdge[] = ${JSON.stringify(edges, null, 2)};
`;
}

export async function writeDerivedFile(repoRoot: string, contents: string): Promise<string> {
  const outPath = path.join(repoRoot, 'apps/web/lib/ecosystem/derived.ts');
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, contents, 'utf8');
  return outPath;
}
