'use client';

/**
 * EU AI Act Article 50(1) disclosure.
 *
 * Luminors are named, human-like personas. Article 50(1) requires that a person
 * interacting with an AI system is informed of that fact unless it is obvious from
 * context — a named persona is precisely the case where it is not obvious. This
 * renders next to the persona name so the disclosure sits with the identity it
 * qualifies, and is deliberately not dismissible: the obligation is to inform at
 * the latest at the time of the first interaction, and a banner the user has
 * already closed does not satisfy that on a later visit.
 *
 * Obligations apply from 2026-08-02.
 */
export function AiDisclosure() {
  return (
    <>
      <span
        aria-hidden="true"
        title="Responses are generated by an AI system, not a human."
        className="px-1.5 py-px rounded text-[9px] font-medium uppercase tracking-wide text-white/40 bg-white/[0.06] border border-white/[0.08]"
      >
        AI
      </span>
      <span className="sr-only">
        You are interacting with an AI system. Responses are generated by artificial
        intelligence, not a human.
      </span>
    </>
  );
}
