declare module '@phosphor-icons/react' {
  import type { ComponentType, SVGProps } from 'react';

  export type PhosphorIcon = ComponentType<
    SVGProps<SVGSVGElement> & {
      size?: number | string;
      weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
      mirrored?: boolean;
    }
  >;

  export const IconContext: {
    Provider: ComponentType<{
      value?: Record<string, unknown>;
      children?: import('react').ReactNode;
    }>;
  };

  // ---------------------------------------------------------------------------
  // All icons imported in apps/web/lib/phosphor-icons.ts
  // ---------------------------------------------------------------------------
  export const ArrowBendDownLeft: PhosphorIcon;
  export const ArrowBendUpLeft: PhosphorIcon;
  export const ArrowCircleDown: PhosphorIcon;
  export const ArrowCounterClockwise: PhosphorIcon;
  export const ArrowDown: PhosphorIcon;
  export const ArrowLeft: PhosphorIcon;
  export const ArrowRight: PhosphorIcon;
  export const ArrowSquareOut: PhosphorIcon;
  export const ArrowUp: PhosphorIcon;
  export const ArrowUpRight: PhosphorIcon;
  export const ArrowsClockwise: PhosphorIcon;
  export const ArrowsDownUp: PhosphorIcon;
  export const ArrowsOut: PhosphorIcon;
  export const Bell: PhosphorIcon;
  export const Bird: PhosphorIcon;
  export const Book: PhosphorIcon;
  export const BookOpen: PhosphorIcon;
  export const Bookmark: PhosphorIcon;
  export const Books: PhosphorIcon;
  export const BracketsCurly: PhosphorIcon;
  export const BracketsSquare: PhosphorIcon;
  export const Brain: PhosphorIcon;
  export const Browser: PhosphorIcon;
  export const Bug: PhosphorIcon;
  export const Buildings: PhosphorIcon;
  export const Calendar: PhosphorIcon;
  export const CalendarDots: PhosphorIcon;
  export const Camera: PhosphorIcon;
  export const CaretDown: PhosphorIcon;
  export const CaretLeft: PhosphorIcon;
  export const CaretRight: PhosphorIcon;
  export const CaretUp: PhosphorIcon;
  export const Cat: PhosphorIcon;
  export const ChartBar: PhosphorIcon;
  export const Chat: PhosphorIcon;
  export const ChatCircle: PhosphorIcon;
  export const ChatCircleDots: PhosphorIcon;
  export const ChatCircleText: PhosphorIcon;
  export const ChatTeardrop: PhosphorIcon;
  export const ChatText: PhosphorIcon;
  export const Chats: PhosphorIcon;
  export const Check: PhosphorIcon;
  export const CheckCircle: PhosphorIcon;
  export const Checks: PhosphorIcon;
  export const Circle: PhosphorIcon;
  export const CircleNotch: PhosphorIcon;
  export const Clock: PhosphorIcon;
  export const ClockCounterClockwise: PhosphorIcon;
  export const Cloud: PhosphorIcon;
  export const CloudSlash: PhosphorIcon;
  export const Code: PhosphorIcon;
  export const CodeBlock: PhosphorIcon;
  export const Command: PhosphorIcon;
  export const Compass: PhosphorIcon;
  export const Copy: PhosphorIcon;
  export const Cpu: PhosphorIcon;
  export const Crown: PhosphorIcon;
  export const Database: PhosphorIcon;
  export const Diamond: PhosphorIcon;
  export const DotsSixVertical: PhosphorIcon;
  export const DotsThreeVertical: PhosphorIcon;
  export const Download: PhosphorIcon;
  export const Drop: PhosphorIcon;
  export const Envelope: PhosphorIcon;
  export const Eye: PhosphorIcon;
  export const EyeSlash: PhosphorIcon;
  export const Feather: PhosphorIcon;
  export const File: PhosphorIcon;
  export const FileCode: PhosphorIcon;
  export const FileText: PhosphorIcon;
  export const FilmStrip: PhosphorIcon;
  export const Fire: PhosphorIcon;
  export const Fish: PhosphorIcon;
  export const Flame: PhosphorIcon;
  export const FloppyDisk: PhosphorIcon;
  export const FolderOpen: PhosphorIcon;
  export const Funnel: PhosphorIcon;
  export const GameController: PhosphorIcon;
  export const Gear: PhosphorIcon;
  export const GitBranch: PhosphorIcon;
  export const GithubLogo: PhosphorIcon;
  export const Globe: PhosphorIcon;
  export const GraduationCap: PhosphorIcon;
  export const GridFour: PhosphorIcon;
  export const GridNine: PhosphorIcon;
  export const Heart: PhosphorIcon;
  export const Heartbeat: PhosphorIcon;
  export const House: PhosphorIcon;
  export const Image: PhosphorIcon;
  export const ImageSquare: PhosphorIcon;
  export const Infinity: PhosphorIcon;
  export const Info: PhosphorIcon;
  export const Keyboard: PhosphorIcon;
  export const Leaf: PhosphorIcon;
  export const Lightbulb: PhosphorIcon;
  export const Lightning: PhosphorIcon;
  export const Link: PhosphorIcon;
  export const List: PhosphorIcon;
  export const ListDashes: PhosphorIcon;
  export const ListNumbers: PhosphorIcon;
  export const Lock: PhosphorIcon;
  export const MagicWand: PhosphorIcon;
  export const MagnifyingGlass: PhosphorIcon;
  export const MagnifyingGlassPlus: PhosphorIcon;
  export const MapPin: PhosphorIcon;
  export const MapTrifold: PhosphorIcon;
  export const Microphone: PhosphorIcon;
  export const Minus: PhosphorIcon;
  export const Moon: PhosphorIcon;
  export const Mountains: PhosphorIcon;
  export const MusicNote: PhosphorIcon;
  export const MusicNotes: PhosphorIcon;
  export const Notebook: PhosphorIcon;
  export const Package: PhosphorIcon;
  export const PaintBrush: PhosphorIcon;
  export const Palette: PhosphorIcon;
  export const PaperPlane: PhosphorIcon;
  export const Paperclip: PhosphorIcon;
  export const Pen: PhosphorIcon;
  export const Pencil: PhosphorIcon;
  export const PencilSimple: PhosphorIcon;
  export const Planet: PhosphorIcon;
  export const Play: PhosphorIcon;
  export const Plus: PhosphorIcon;
  export const PushPin: PhosphorIcon;
  export const Question: PhosphorIcon;
  export const Quotes: PhosphorIcon;
  export const Radio: PhosphorIcon;
  export const Rocket: PhosphorIcon;
  export const Scales: PhosphorIcon;
  export const Scroll: PhosphorIcon;
  export const Share: PhosphorIcon;
  export const Shield: PhosphorIcon;
  export const ShieldStar: PhosphorIcon;
  export const Shuffle: PhosphorIcon;
  export const SignOut: PhosphorIcon;
  export const Skull: PhosphorIcon;
  export const SlidersHorizontal: PhosphorIcon;
  export const SortAscending: PhosphorIcon;
  export const SortDescending: PhosphorIcon;
  export const Sparkle: PhosphorIcon;
  export const Spinner: PhosphorIcon;
  export const Spiral: PhosphorIcon;
  export const SplitHorizontal: PhosphorIcon;
  export const SquaresFour: PhosphorIcon;
  export const Stack: PhosphorIcon;
  export const Star: PhosphorIcon;
  export const Sun: PhosphorIcon;
  export const Sword: PhosphorIcon;
  export const Tag: PhosphorIcon;
  export const Target: PhosphorIcon;
  export const Terminal: PhosphorIcon;
  export const TextAa: PhosphorIcon;
  export const TextB: PhosphorIcon;
  export const TextHOne: PhosphorIcon;
  export const TextHTwo: PhosphorIcon;
  export const TextItalic: PhosphorIcon;
  export const TextT: PhosphorIcon;
  export const Translate: PhosphorIcon;
  export const Trash: PhosphorIcon;
  export const Tree: PhosphorIcon;
  export const TrendDown: PhosphorIcon;
  export const TrendUp: PhosphorIcon;
  export const Trophy: PhosphorIcon;
  export const TwitterLogo: PhosphorIcon;
  export const Upload: PhosphorIcon;
  export const User: PhosphorIcon;
  export const UserCircle: PhosphorIcon;
  export const UserPlus: PhosphorIcon;
  export const Users: PhosphorIcon;
  export const VideoCamera: PhosphorIcon;
  export const Wand: PhosphorIcon;
  export const Warning: PhosphorIcon;
  export const WarningCircle: PhosphorIcon;
  export const Waves: PhosphorIcon;
  export const WifiHigh: PhosphorIcon;
  export const WifiSlash: PhosphorIcon;
  export const Wind: PhosphorIcon;
  export const Wrench: PhosphorIcon;
  export const X: PhosphorIcon;
  export const YoutubeLogo: PhosphorIcon;

  // Catch-all for any icons not explicitly listed
  const fallback: Record<string, PhosphorIcon>;
  export default fallback;
}

declare module '@phosphor-icons/react/dist/ssr' {
  export * from '@phosphor-icons/react';
}
