import type {
  CreationType,
  ElementName,
  GateName,
  GuardianName,
} from "@/lib/database/types/api-responses";
import {
  PhFire,
  PhDrop,
  PhLeaf,
  PhWind,
  PhSpiral,
  PhStar,
  PhFileText,
  PhImage,
  PhVideo,
  PhMusicNote,
  PhCode,
  PhStack,
} from "@/lib/phosphor-icons";

// ---------------------------------------------------------------------------
// Showcase creation shape (hardcoded canonical data)
// ---------------------------------------------------------------------------

export interface ShowcaseCreation {
  id: string;
  title: string;
  description: string;
  type: CreationType;
  element: ElementName;
  gate: GateName;
  guardian: GuardianName;
  creatorName: string;
  academyHouse: string;
  likeCount: number;
  viewCount: number;
  tags: string[];
  thumbnailUrl?: string;
  featuredRank?: number;
  visualQaScore?: number;
}

// ---------------------------------------------------------------------------
// Element styling maps
// ---------------------------------------------------------------------------

export const ELEMENT_COLORS: Record<
  ElementName,
  { gradient: string; badge: string; text: string }
> = {
  Fire: {
    gradient: "from-red-500/20 to-orange-500/5",
    badge: "bg-red-500/15 text-red-400 border-red-500/25",
    text: "text-red-400",
  },
  Water: {
    gradient: "from-blue-500/20 to-cyan-500/5",
    badge: "bg-blue-500/15 text-blue-400 border-blue-500/25",
    text: "text-blue-400",
  },
  Earth: {
    gradient: "from-green-500/20 to-emerald-500/5",
    badge: "bg-green-500/15 text-green-400 border-green-500/25",
    text: "text-green-400",
  },
  Wind: {
    gradient: "from-slate-300/20 to-slate-200/5",
    badge: "bg-slate-300/15 text-slate-300 border-slate-300/25",
    text: "text-slate-300",
  },
  Void: {
    gradient: "from-violet-500/20 to-purple-500/5",
    badge: "bg-violet-500/15 text-violet-400 border-violet-500/25",
    text: "text-violet-400",
  },
  Spirit: {
    gradient: "from-amber-400/20 to-yellow-300/5",
    badge: "bg-amber-400/15 text-amber-300 border-amber-400/25",
    text: "text-amber-300",
  },
};

export const ELEMENT_ICONS: Record<ElementName, typeof PhFire> = {
  Fire: PhFire,
  Water: PhDrop,
  Earth: PhLeaf,
  Wind: PhWind,
  Void: PhSpiral,
  Spirit: PhStar,
};

// ---------------------------------------------------------------------------
// Type styling maps
// ---------------------------------------------------------------------------

export const TYPE_ICONS: Record<CreationType, typeof PhFileText> = {
  text: PhFileText,
  image: PhImage,
  video: PhVideo,
  audio: PhMusicNote,
  code: PhCode,
  mixed: PhStack,
};

export const TYPE_LABELS: Record<CreationType, string> = {
  text: "Text",
  image: "Image",
  video: "Video",
  audio: "Audio",
  code: "Code",
  mixed: "Mixed",
};

// ---------------------------------------------------------------------------
// Curated visual world engine candidates
// ---------------------------------------------------------------------------

const VISUAL_WORLD_ENGINE_CREATIONS: ShowcaseCreation[] = [
  {
    id: "vwe-2026-07-043",
    title: "Unity Kyuro Bridge Action",
    description:
      "The strongest Unity action hook yet: creators physically coordinate across Kyuro's living bridge infrastructure to stabilize a proof artifact.",
    type: "image",
    element: "Earth",
    gate: "Unity",
    guardian: "Ino",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-043-unity-kyuro-bridge-action-thumb.jpg",
    likeCount: 29,
    viewCount: 0,
    featuredRank: 0.001,
    visualQaScore: 29,
    tags: ["visual-world-engine", "unity-gate", "kyuro", "cooperation", "qa-29"],
  },
  {
    id: "vwe-2026-07-044",
    title: "Gate Stays Open Consent Exit",
    description:
      "A Gate-Descent story frame where cooperation, witness, and consent open the exit instead of a monster-boss climax.",
    type: "image",
    element: "Spirit",
    gate: "Foundation",
    guardian: "Lyssandria",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Aether",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-044-gate-stays-open-consent-exit-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 0.002,
    visualQaScore: 28,
    tags: ["visual-world-engine", "gate-descent", "webtoon", "consent-exit", "qa-28"],
  },
  {
    id: "vwe-2026-07-045",
    title: "World Tower Dragon Habitat Bridge",
    description:
      "A healthy world-tower habitat with a peaceful dragon, vibrant fabric bridge, and creator-scale warmth; approved with crop caution.",
    type: "image",
    element: "Earth",
    gate: "Foundation",
    guardian: "Lyssandria",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Terra",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-045-world-tower-dragon-habitat-bridge-thumb.jpg",
    likeCount: 27,
    viewCount: 0,
    featuredRank: 0.003,
    visualQaScore: 27,
    tags: ["visual-world-engine", "mega-scale-world", "dragon-habitat", "qa-27"],
  },
  {
    id: "vwe-2026-07-040",
    title: "Unity Cooperation Lattice",
    description:
      "The corrected Unity pass: Kyuro becomes cooperation infrastructure while creators actively stabilize, witness, release, and protect the proof artifact.",
    type: "image",
    element: "Earth",
    gate: "Unity",
    guardian: "Ino",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-040-unity-kyuro-cooperation-lattice-thumb.jpg",
    likeCount: 29,
    viewCount: 0,
    featuredRank: 0.01,
    visualQaScore: 29,
    tags: ["visual-world-engine", "unity-gate", "kyuro", "cooperation", "qa-29"],
  },
  {
    id: "vwe-2026-07-041",
    title: "Webtoon Gate Choice",
    description:
      "A story-portal frame for the Gate-Descent choice: blank ledger, consent exit, and friends holding the Gate open together.",
    type: "image",
    element: "Spirit",
    gate: "Foundation",
    guardian: "Lyssandria",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Aether",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-041-webtoon-gate-choice-blank-ledger-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 0.02,
    visualQaScore: 28,
    tags: ["visual-world-engine", "webtoon", "gate-descent", "blank-ledger", "qa-28"],
  },
  {
    id: "vwe-2026-07-042",
    title: "Music Resonance Proof Cover",
    description:
      "A square cover source where live performance becomes a visible proof artifact inside a quiet Arcanea amphitheater.",
    type: "image",
    element: "Wind",
    gate: "Voice",
    guardian: "Alera",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Ventus",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-042-music-resonance-proof-cover-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 0.03,
    visualQaScore: 28,
    tags: ["visual-world-engine", "music", "voice-gate", "proof-cover", "qa-28"],
  },
  {
    id: "vwe-2026-07-036",
    title: "Veloura Membrane Corridor",
    description:
      "The strongest Flow Gate correction so far: Veloura becomes living aquifer membrane and corridor weather, not a creature-head silhouette.",
    type: "image",
    element: "Water",
    gate: "Flow",
    guardian: "Leyla",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Aqualis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-036-flow-gate-veloura-membrane-corridor-thumb.jpg",
    likeCount: 29,
    viewCount: 0,
    featuredRank: 0.1,
    visualQaScore: 29,
    tags: ["visual-world-engine", "flow-gate", "veloura", "qa-29"],
  },
  {
    id: "vwe-2026-07-037",
    title: "Starweave Perspective Loom",
    description:
      "A Starweave Gate expansion where Vaelith becomes a vast perspective loom of horizon-arches, starlight fabric, and parallax world windows.",
    type: "image",
    element: "Spirit",
    gate: "Starweave",
    guardian: "Elara",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-037-starweave-vaelith-perspective-loom-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 0.2,
    visualQaScore: 28,
    tags: ["visual-world-engine", "starweave-gate", "vaelith", "qa-28"],
  },
  {
    id: "vwe-2026-07-039",
    title: "Source Meta-Consciousness Atlas",
    description:
      "A Source Gate proof chamber: black-gold fertile unknown, white-gold consciousness, ten Gate lights, and Shinkami as guide instead of deity portrait.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-039-source-gate-shinkami-meta-consciousness-atlas-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 0.3,
    visualQaScore: 28,
    tags: ["visual-world-engine", "source-gate", "shinkami", "qa-28"],
  },
  {
    id: "vwe-2026-07-038",
    title: "Unity Partnership Sanctuary",
    description:
      "A Unity Gate candidate where Kyuro becomes paired sanctuary infrastructure and cooperation is visible through living bridge-spines.",
    type: "image",
    element: "Earth",
    gate: "Unity",
    guardian: "Ino",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-038-unity-kyuro-partnership-sanctuary-thumb.jpg",
    likeCount: 27,
    viewCount: 0,
    featuredRank: 0.4,
    visualQaScore: 27,
    tags: ["visual-world-engine", "unity-gate", "kyuro", "qa-27"],
  },
  {
    id: "vwe-2026-07-033",
    title: "Fire Gate Forge Titan",
    description:
      "A constructive Fire Gate social hook: Draconis sleeps as a lava-crystal habitat while tiny creators work safely in the forge city.",
    type: "image",
    element: "Fire",
    gate: "Fire",
    guardian: "Draconia",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Pyros",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-033-fire-gate-draconis-healthy-forge-titan-thumb.jpg",
    likeCount: 29,
    viewCount: 0,
    featuredRank: 1,
    visualQaScore: 29,
    tags: ["visual-world-engine", "fire-gate", "draconis", "qa-29"],
  },
  {
    id: "vwe-2026-07-008d",
    title: "Alera Resonance Console",
    description:
      "A Voice Gate correction where Alera reads as an Arcanea operator and Otome becomes protective resonance infrastructure.",
    type: "image",
    element: "Wind",
    gate: "Voice",
    guardian: "Alera",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Ventus",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-008d-alera-otome-operator-resonance-console-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 2,
    visualQaScore: 28,
    tags: ["visual-world-engine", "voice-gate", "otome", "qa-28"],
  },
  {
    id: "vwe-2026-07-032",
    title: "Flow Gate Aquifer Corridor",
    description:
      "A blue-silver Mar Arcano corridor city sheltered by Veloura as water-metal world infrastructure, approved with canon caution.",
    type: "image",
    element: "Water",
    gate: "Flow",
    guardian: "Leyla",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Aqualis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-032-flow-gate-veloura-aquifer-corridor-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 3,
    visualQaScore: 28,
    tags: ["visual-world-engine", "flow-gate", "veloura", "qa-28"],
  },
  {
    id: "vwe-2026-07-034",
    title: "Crown Gate Solar Library",
    description:
      "A 16:9 editorial source where Sol becomes a living solar canopy above Aiyami's blank crystal study city.",
    type: "image",
    element: "Spirit",
    gate: "Crown",
    guardian: "Aiyami",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-034-crown-gate-sol-solar-canopy-library-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 4,
    visualQaScore: 28,
    tags: ["visual-world-engine", "crown-gate", "sol", "qa-28"],
  },
  {
    id: "vwe-2026-07-009d",
    title: "Yumiko Perception Field",
    description:
      "A Sight Gate correction where Yumiko becomes non-humanoid lens weather and Lyria anchors the field with a blank prism.",
    type: "image",
    element: "Void",
    gate: "Sight",
    guardian: "Lyria",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-009d-lyria-yumiko-nonhumanoid-perception-field-thumb.jpg",
    likeCount: 27,
    viewCount: 0,
    featuredRank: 5,
    visualQaScore: 27,
    tags: ["visual-world-engine", "sight-gate", "yumiko", "qa-27"],
  },
  {
    id: "vwe-2026-07-035",
    title: "Music Proof Stage",
    description:
      "A vertical music/social source where a creator turns resonance into a portal-bloom proof artifact on a black-glass stage.",
    type: "image",
    element: "Wind",
    gate: "Voice",
    guardian: "Alera",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Ventus",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-035-arcanea-music-proof-stage-no-text-thumb.jpg",
    likeCount: 27,
    viewCount: 0,
    featuredRank: 6,
    visualQaScore: 27,
    tags: ["visual-world-engine", "music", "proof-stage", "qa-27"],
  },
  {
    id: "vwe-2026-07-028",
    title: "Heart Realm Living Ark",
    description:
      "A non-dragon megascale world hook: a living ark-city, tiny creators, fabric bridges, waterfalls, and a peaceful root-whale habitat presence.",
    type: "image",
    element: "Earth",
    gate: "Heart",
    guardian: "Maylinn",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Terra",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-028-heart-realm-living-ark-non-dragon-thumb.jpg",
    likeCount: 29,
    viewCount: 0,
    featuredRank: 7,
    visualQaScore: 29,
    tags: ["visual-world-engine", "mega-scale-world", "non-dragon", "qa-29"],
  },
  {
    id: "vwe-2026-07-025",
    title: "World Tower Social Crop",
    description:
      "A 4:5 living megastructure built for short-form and carousel hooks: tiny creators, fabric bridges, waterfalls, and a vast habitat presence.",
    type: "image",
    element: "Earth",
    gate: "Heart",
    guardian: "Maylinn",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Terra",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-025-world-tower-social-crop-thumb.jpg",
    likeCount: 29,
    viewCount: 0,
    featuredRank: 8,
    visualQaScore: 29,
    tags: ["visual-world-engine", "mega-scale-world", "instagram", "qa-29"],
  },
  {
    id: "vwe-2026-07-027",
    title: "Music Portal Bloom",
    description:
      "A text-free album and social source frame where sound becomes a living portal object in Arcanea gold, teal, and dark glass.",
    type: "image",
    element: "Wind",
    gate: "Voice",
    guardian: "Alera",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Ventus",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-027-music-portal-bloom-clean-thumb.jpg",
    likeCount: 29,
    viewCount: 0,
    featuredRank: 9,
    visualQaScore: 29,
    tags: ["visual-world-engine", "music", "album-source", "qa-29"],
  },
  {
    id: "vwe-2026-07-029",
    title: "Proof Trial Four Beats",
    description:
      "A four-beat story source where diverse creators notice The Drift, choose a proof artifact, and open a warm studio doorway.",
    type: "image",
    element: "Wind",
    gate: "Voice",
    guardian: "Alera",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Ventus",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-029-webtoon-trial-four-beats-diverse-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 10,
    visualQaScore: 28,
    tags: ["visual-world-engine", "webtoon", "story-sequence", "qa-28"],
  },
  {
    id: "vwe-2026-07-030",
    title: "First Proof Living Library",
    description:
      "A storybook/book source frame: a young creator and mentor enter a living lore library where proof artifacts become gentle worlds.",
    type: "image",
    element: "Spirit",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-030-storybook-first-proof-living-library-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 11,
    visualQaScore: 28,
    tags: ["visual-world-engine", "storybook", "book-source", "qa-28"],
  },
  {
    id: "vwe-2026-07-031",
    title: "Luminor Rank Proof Atlas",
    description:
      "A 16:9 proof-atlas artifact that keeps Luminor canon-safe as an earned mastery rank, with ten opened Gates as light architecture.",
    type: "image",
    element: "Spirit",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-031-luminor-rank-proof-atlas-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 12,
    visualQaScore: 28,
    tags: ["visual-world-engine", "luminor-rank", "proof-atlas", "qa-28"],
  },
  {
    id: "vwe-2026-07-020c",
    title: "First Trial Three Beats",
    description:
      "A clean three-beat webtoon source sequence: notice The Drift, choose the artifact, place proof into the blank ledger.",
    type: "image",
    element: "Wind",
    gate: "Voice",
    guardian: "Alera",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Ventus",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-020c-webtoon-first-trial-three-beats-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 13,
    visualQaScore: 28,
    tags: ["visual-world-engine", "webtoon", "story-sequence", "qa-28"],
  },
  {
    id: "vwe-2026-07-004c",
    title: "Kaelith Gravity Foundation",
    description:
      "A stronger Foundation Gate candidate: Kaelith shifts away from dragon silhouette into mountain-root gravity presence.",
    type: "image",
    element: "Earth",
    gate: "Foundation",
    guardian: "Lyssandria",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Terra",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-004c-lyssandria-kaelith-gravity-foundation-thumb.jpg",
    likeCount: 27,
    viewCount: 0,
    featuredRank: 14,
    visualQaScore: 27,
    tags: ["visual-world-engine", "foundation-gate", "kaelith", "qa-27"],
  },
  {
    id: "vwe-2026-07-001",
    title: "Genesis Proof Forge",
    description:
      "A creator faces the first proof artifact in Arcanea's dark-glass forge: the cleanest hero source for the Genesis loop.",
    type: "image",
    element: "Spirit",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-001-genesis-proof-forge-first-call-thumb.jpg",
    likeCount: 26,
    viewCount: 0,
    featuredRank: 15,
    visualQaScore: 26,
    tags: ["visual-world-engine", "genesis", "proof-artifact", "qa-26"],
  },
  {
    id: "vwe-2026-07-024b",
    title: "Clean Proof Artifact",
    description:
      "A focused proof object with clean negative space for X, YouTube, and Arcanea article/social overlays.",
    type: "image",
    element: "Spirit",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Synthesis",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-024b-clean-proof-artifact-og-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 16,
    visualQaScore: 28,
    tags: ["visual-world-engine", "social-og", "proof-artifact", "qa-28"],
  },
  {
    id: "vwe-2026-07-018",
    title: "World Tower Habitat",
    description:
      "A kilometer-scale living tower where fabric bridges, waterfalls, forests, crystal terraces, and vast beings share one vertical world.",
    type: "image",
    element: "Earth",
    gate: "Heart",
    guardian: "Maylinn",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Terra",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-018-world-tower-dragon-habitat-thumb.jpg",
    likeCount: 28,
    viewCount: 0,
    featuredRank: 17,
    visualQaScore: 28,
    tags: ["visual-world-engine", "mega-scale-world", "social-hook", "qa-28"],
  },
  {
    id: "vwe-2026-07-002b",
    title: "The Drift Meets Proof",
    description:
      "A blank proof ledger answers passive media fog with a finished artifact, built for vertical short-form hook testing.",
    type: "image",
    element: "Wind",
    gate: "Voice",
    guardian: "Alera",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Ventus",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-002b-the-drift-vs-proof-ledger-blank-thumb.jpg",
    likeCount: 27,
    viewCount: 0,
    featuredRank: 18,
    visualQaScore: 27,
    tags: ["visual-world-engine", "the-drift", "shorts", "qa-27"],
  },
  {
    id: "vwe-2026-07-020b",
    title: "First Trial Webtoon Frame",
    description:
      "A quiet creator-choice moment for the Arcanea webtoon pipeline, with no speech bubbles or baked-in text.",
    type: "image",
    element: "Wind",
    gate: "Voice",
    guardian: "Alera",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Ventus",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-020b-webtoon-first-trial-clean-thumb.jpg",
    likeCount: 27,
    viewCount: 0,
    featuredRank: 19,
    visualQaScore: 27,
    tags: ["visual-world-engine", "webtoon", "first-trial", "qa-27"],
  },
  {
    id: "vwe-2026-07-004b",
    title: "Lyssandria and Kaelith",
    description:
      "A Foundation Gate portal candidate for Lyssandria and Kaelith, approved with canon caution for the next Godbeast refinement pass.",
    type: "image",
    element: "Earth",
    gate: "Foundation",
    guardian: "Lyssandria",
    creatorName: "Arcanea Visual World Engine",
    academyHouse: "Terra",
    thumbnailUrl:
      "/images/arcanea-world-engine/god-run-2026-07-06/arc-visual-004b-lyssandria-kaelith-mythtech-thumb.jpg",
    likeCount: 26,
    viewCount: 0,
    featuredRank: 20,
    visualQaScore: 26,
    tags: ["visual-world-engine", "foundation-gate", "kaelith", "qa-26"],
  },
];

// ---------------------------------------------------------------------------
// Canonical showcase creations
// ---------------------------------------------------------------------------

export const SHOWCASE_CREATIONS: ShowcaseCreation[] = [
  ...VISUAL_WORLD_ENGINE_CREATIONS,
  {
    id: "gen_0",
    title: "Academy Grounds Exterior",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/academy_grounds_exterior_1783294020630.png",
    likeCount: 535,
    viewCount: 1673,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_1",
    title: "Academy Hall",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/academy_hall_1783293877994.png",
    likeCount: 279,
    viewCount: 1606,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_2",
    title: "Aiyami Crown",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/aiyami_crown_1783293950103.png",
    likeCount: 272,
    viewCount: 3004,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_3",
    title: "Alien Race Starlight Academy",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/alien_race_starlight_academy_1783294384574.png",
    likeCount: 259,
    viewCount: 5832,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_4",
    title: "Ancient Lore Archive",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/ancient_lore_archive_1783294183266.png",
    likeCount: 411,
    viewCount: 3630,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_5",
    title: "Arion Academy",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/arion_academy_1783293846776.png",
    likeCount: 447,
    viewCount: 5075,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_6",
    title: "Class Dungeon Hunter",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/class_dungeon_hunter_1783294321097.png",
    likeCount: 452,
    viewCount: 2513,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_7",
    title: "Class Magetech Warrior",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/class_magetech_warrior_1783294313149.png",
    likeCount: 267,
    viewCount: 2259,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_8",
    title: "Class Quantum Wizard",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/class_quantum_wizard_1783294288447.png",
    likeCount: 428,
    viewCount: 5350,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_9",
    title: "Class Reality Architect",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/class_reality_architect_1783294303350.png",
    likeCount: 271,
    viewCount: 5136,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_10",
    title: "Class Temporal Wizard",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/class_temporal_wizard_1783294297265.png",
    likeCount: 486,
    viewCount: 5184,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_11",
    title: "Colossal Ancient Machine",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/colossal_ancient_machine_1783294098401.png",
    likeCount: 109,
    viewCount: 5890,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_12",
    title: "Demon Lord Of The Abyss",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/demon_lord_of_the_abyss_1783294376933.png",
    likeCount: 320,
    viewCount: 1182,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_13",
    title: "Dungeon Entrance Gate",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/dungeon_entrance_gate_1783294034651.png",
    likeCount: 467,
    viewCount: 5522,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_14",
    title: "Elara Shift",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/elara_shift_1783293957586.png",
    likeCount: 505,
    viewCount: 3633,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_15",
    title: "Emilia Assassin",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/emilia_assassin_1783293870060.png",
    likeCount: 247,
    viewCount: 4431,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_16",
    title: "Faction Agentic Swarm",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/faction_agentic_swarm_1783294362731.png",
    likeCount: 322,
    viewCount: 1564,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_17",
    title: "Faction Kings Of Arcanea",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/faction_kings_of_arcanea_1783294353622.png",
    likeCount: 497,
    viewCount: 5774,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_18",
    title: "Lumina Capital",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/lumina_capital_1783294006233.png",
    likeCount: 308,
    viewCount: 5796,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_19",
    title: "Luminor Ascension",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/luminor_ascension_1783293964045.png",
    likeCount: 531,
    viewCount: 5557,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_20",
    title: "Magetech Creators Workshop",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/magetech_creators_workshop_1783294153853.png",
    likeCount: 126,
    viewCount: 3806,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_21",
    title: "Mamoru Dungeon",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/mamoru_dungeon_1783293853692.png",
    likeCount: 279,
    viewCount: 2321,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_22",
    title: "Mera Elements",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/mera_elements_1783293862991.png",
    likeCount: 200,
    viewCount: 5586,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_23",
    title: "Ruler Queen Of Arcanea",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/ruler_queen_of_arcanea_1783294370720.png",
    likeCount: 188,
    viewCount: 5391,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_24",
    title: "Shinkami Source",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/shinkami_source_1783293942362.png",
    likeCount: 379,
    viewCount: 3577,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_25",
    title: "Sleeping God Mountain",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/sleeping_god_mountain_1783294105097.png",
    likeCount: 154,
    viewCount: 4472,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_26",
    title: "Swarms Of The Abyss",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/swarms_of_the_abyss_1783294168653.png",
    likeCount: 500,
    viewCount: 3960,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_27",
    title: "The Abyss Edge",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/the_abyss_edge_1783294012996.png",
    likeCount: 284,
    viewCount: 5126,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_28",
    title: "The Crystal Forest",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/the_crystal_forest_1783294027797.png",
    likeCount: 375,
    viewCount: 2721,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_29",
    title: "The First Rebellion",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/the_first_rebellion_1783294176309.png",
    likeCount: 388,
    viewCount: 4739,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_30",
    title: "The Shattered Moon Event",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/the_shattered_moon_event_1783294160899.png",
    likeCount: 267,
    viewCount: 3529,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_31",
    title: "Titan Of Deep Sea",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl:
      "/images/arcanea-universe/titan_of_deep_sea_1783294091849.png",
    likeCount: 269,
    viewCount: 1062,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_32",
    title: "Titan Of Earth",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/titan_of_earth_1783294078128.png",
    likeCount: 239,
    viewCount: 5251,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_33",
    title: "Titan Of Sky",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/titan_of_sky_1783294085214.png",
    likeCount: 201,
    viewCount: 4480,
    tags: ["ai-art", "concept", "arcanea"],
  },
  {
    id: "gen_34",
    title: "Unity Gate Ino",
    description:
      "An AI-generated artifact from the Arcanea universe, crafted to evoke awe and cosmic scale.",
    type: "image",
    element: "Void",
    gate: "Source",
    guardian: "Shinkami",
    creatorName: "Arcanea Visual Engine",
    academyHouse: "Nero",
    thumbnailUrl: "/images/arcanea-universe/unity_gate_ino_1783293970990.png",
    likeCount: 281,
    viewCount: 2824,
    tags: ["ai-art", "concept", "arcanea"],
  },
];
