import type { NovellaChapter } from '@/components/books/illustrated-novella-reader';

export const seleneYBrioChapters: NovellaChapter[] = [
  {
    "id": "the-colour-of-other-people",
    "number": 1,
    "title": "The Colour of Other People",
    "subtitle": "Caracas · The first threshold",
    "paragraphs": [
      "The light around the woman beside Selene’s desk turned the colour of a struck match, and Selene deleted the last sentence of her proposal.",
      "“Too much?” she asked.",
      "Her colleague looked up from her phone. “What?”",
      "“The new layout.”",
      "“No. My sister’s in labour.”",
      "Selene put the sentence back.",
      "On the screen, a clean black line divided two columns of text. She had spent forty minutes getting it right. Beyond the office windows the Ávila stood beneath a low shelf of cloud, and the light at her colleague’s wrists fluttered again. Joy, perhaps. Fear. Both. Selene could see it as plainly as the coffee stain on the desk and understand it considerably less well.",
      "At twenty-nine, she was very good at making this distinction in retrospect.",
      "She finished the proposal. She answered a message she wanted to answer and three she did not. When the others left for drinks, she went with them, laughed at a story about a spectacularly unsuccessful date, and stayed until the restaurant filled with the overlapping colours of strangers. Then she excused herself with a headache. It was easier than describing the effort of listening to one voice while someone else’s sorrow flared behind it.",
      "At home she made coffee too late in the day. Guacamayas crossed the gap between the buildings, blue wings briefly catching the sun. Her phone showed the photograph she had taken of the mountain that morning: ordinary cloud, ordinary stone. None of the fine silver lines she had seen moving through it.",
      "She opened the front camera.",
      "A tired woman looked back. One eyebrow sat slightly higher than the other. The little gold hoops her grandmother had given her needed cleaning.",
      "There was no light around her.",
      "She moved the phone closer, as if a thing that had refused her for twenty-nine years might yield to a better angle.",
      "A voice message arrived from Mercedes.",
      "“Before you invent an excuse, I have made enough food for two.”",
      "Selene smiled despite herself.",
      "Her grandmother lived six floors below, in a flat whose windows were crowded with plants. Dinner was arepas, avocado, white cheese, and an argument about whether Selene was sleeping enough. Mercedes lost the argument without conceding it. When Selene took the plates to the sink, the old woman set a small cloth bundle on the table.",
      "Inside lay a translucent stone.",
      "Its light touched the ceiling in five narrow bands. Selene put a hand beneath them. The bands slid over her skin; nothing answered.",
      "“Where did you get this?”",
      "“From home.”",
      "“You’re home.”",
      "Mercedes turned the stone with one finger. “From before.”",
      "Selene sat down.",
      "The story took most of the evening. A place called Avilara. A mountain with a voice. A passage that had once opened beneath the Ávila and closed behind a frightened young woman carrying too little money and the wrong kind of shoes.",
      "“You could have told me.”",
      "“Yes.”",
      "The quick agreement made Selene angrier.",
      "“All those years I thought—”",
      "“I know some of what you thought.” Mercedes’s hand remained on the table, an inch from hers. “I don’t know all of it.”",
      "For once, Selene did not help someone finish the difficult part.",
      "The old woman waited. Then she said, “I was afraid you would go.”",
      "“So you let me be afraid to stay.”",
      "Mercedes lowered her eyes. Her destello loosened around her shoulders, pale violet threaded with amber. Selene could have spent the night trying to decide which part was remorse and which part was love.",
      "Instead she said, “I need you to answer my questions.”",
      "They spoke until the coffee went cold.",
      "The stone was a lens. It could clarify a living light for two breaths, then needed a day’s warmth against a living chest. It could neither create a gift nor tell its bearer what to do with one. No one, Mercedes said, could see their own destello.",
      "“Then how do you know you have one?”",
      "Her grandmother opened her mouth, stopped, and tried again.",
      "“I have been told. By people I trust.”",
      "Selene slept little. In the morning she told her mother where she was going, gave her the route Mercedes had drawn, and promised to return to the threshold the following evening if it remained open. Her mother disliked every part of it. They arranged a second check-in anyway.",
      "At the mountain, mist caught in Selene’s hair. A silver cat sat beside a cleft she did not remember from any trail.",
      "She lifted the stone.",
      "For two breaths, the rock disclosed a seam of pink light. Beyond it stood a valley too deep for the mountain to contain.",
      "The stone went cold.",
      "Selene checked the knot on her bag. Then she stepped through."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/01.webp",
        "alt": "Selene holds a small coffee cup at an open Caracas window at blue hour, with Ávila dark beyond the city.",
        "caption": "The city in her hands"
      },
      {
        "src": "/images/books/selene-y-brio/02.webp",
        "alt": "Selene lifts a prismatic stone at a narrow opening in the cloud forest, revealing a rose-gold valley beyond.",
        "caption": "A door in the mountain"
      }
    ]
  },
  {
    "id": "the-horse-who-said-no",
    "number": 2,
    "title": "The Horse Who Said No",
    "subtitle": "Avilara · The orchid road",
    "paragraphs": [
      "Brío took the cuff of Selene’s shirt between his teeth and tested whether it was edible.",
      "“It isn’t,” she told him.",
      "“He likes to establish these things himself.”",
      "The woman at the stable door had silver in her dark hair and a knife worn short from sharpening. She introduced herself as Renata Solar, examined the small map Mercedes had drawn, and sat down very abruptly.",
      "For a moment Selene thought she might be ill.",
      "“Mercedes,” Renata said.",
      "“My grandmother.”",
      "“That stubborn woman.”",
      "“She’ll be delighted you remember.”",
      "Renata laughed. The sound shook something loose in her face.",
      "She had found Selene on the threshold path the evening before, wet to the knees and furious that her phone could photograph a flower taller than a bus but could not send the photograph anywhere. Renata had given her a bed, fed her, and sent a runner to check the passage. The runner crossed before dawn with Selene’s letter and returned with her mother’s reply. After breakfast Selene checked the cleft herself, well before the evening she had promised. It had closed. Renata gave her the watch service’s schedule for the next likely opening. Selene sent word by the corridor-watch service whenever a passage allowed it; going home would require more patience than going out.",
      "Now there was Brío.",
      "He was a dark bay gelding with a small star on his forehead and an expression suggesting that most human plans required supervision. Selene had ridden on family trips to the plains, then taken lessons when she could afford them. She knew enough to recognise the difference between a horse standing quietly and one holding himself still.",
      "Brío watched a brass bell hanging outside the stable. One ear never left it.",
      "“He was a river courier,” Renata said. “A flood took a bridge under him. His rider lived. Neither of them works that route now.”",
      "“And you’re lending him to a stranger?”",
      "“I’m deciding whether to.”",
      "They began in the yard. Brío turned readily, stopped promptly, and refused to approach the bell. Selene tried a firmer cue.",
      "His back tightened.",
      "Renata lifted a hand. “Get off.”",
      "Selene dismounted, cheeks hot.",
      "“Watch his feet. Then his ears. Then decide what you know.”",
      "The yard smelled of leather and damp wood. Outside, orchids leaned from the trees, their violet throats large enough to shelter a person from rain. Their roots held the stable roof in place. Selene looked at the flowers because it was easier than looking at Renata.",
      "“I know he’s afraid.”",
      "“You suspect. What did you see?”",
      "“A fixed ear. Tension in his back. He shifted his weight away from the bell.”",
      "“Good. Keep the observation. You can ask him about the rest.”",
      "They moved the bell indoors. Brío walked across the yard.",
      "Renata offered no congratulation. She handed Selene a brush.",
      "By midday they had negotiated an arrangement. Renata would escort them as far as the first river station. Selene would check the saddle at every rest, walk the steepest descents, and bring Brío back if he became lame. Their destination was Solavila, where visiting Luminors received travellers seeking instruction. From there, if she still wished it, the road continued to Crystalpeak and the Academy.",
      "“A school,” Selene said, trying to hide her disappointment.",
      "“A good place to discover how much you don’t know.”",
      "“I have quite a lot of experience with that.”",
      "“Then you may be an excellent student.”",
      "The path rose beneath red hanging bracts. Beyond them stretched a country assembled from recognitions that had outgrown their names: moriche palms beside black water, distant table mountains, an araguaney shedding yellow blossoms into a stream. A fallen bract held enough rain for Brío to drink.",
      "Selene took out her phone. The camera made the mountains small.",
      "She put it away.",
      "Renata rode ahead on a grey mare. Brío followed, his stride warm and sure beneath Selene. There were lights everywhere—at the centres of birds, under the bark of trees, threading the enormous flowers—but distance gave them room. For the first time in months, she could look without bracing.",
      "“Destellos,” Renata said when Selene asked.",
      "“I know the word.”",
      "“Then begin with the things you don’t know.”",
      "Near evening, they passed a closed pavilion of white glass. No vine touched its walls. Selene noticed a thin blue current travelling from the surrounding roots toward the building.",
      "A sign on the door read: RIVER STATION. SERVICE SUSPENDED.",
      "Renata’s mouth tightened.",
      "From somewhere inside came the sound of a bell.",
      "Brío stopped so sharply that Selene caught the saddle.",
      "Far ahead, between two orchid stems, something enormous moved against the light."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/03.webp",
        "alt": "Selene offers her open palm to Brío in an orchid-root stable while Renata watches from a distance.",
        "caption": "Brío"
      },
      {
        "src": "/images/books/selene-y-brio/04.webp",
        "alt": "Selene rides Brío beneath immense violet orchids and tree ferns, with tepuis rising beyond the clouds.",
        "caption": "The orchid road"
      }
    ]
  },
  {
    "id": "what-the-jaguar-wanted",
    "number": 3,
    "title": "What the Jaguar Wanted",
    "subtitle": "The lower river · A mistaken certainty",
    "paragraphs": [
      "Selene’s hand closed on the reins before she understood how large the jaguar was.",
      "Its shoulder stood higher than Brío’s head. Rain darkened the gold between its rosettes. One ear was torn, and the light running beneath its fur pulsed with a dense, restless green.",
      "The cat stepped onto the path.",
      "Renata’s mare backed once. Brío turned his head toward an uphill track.",
      "“Turn uphill with him,” Renata said.",
      "But Selene was staring at the jaguar’s light. It was brightest along the riverward side of its body. The cat looked downstream, then at them, then downstream again.",
      "“It wants us to follow.”",
      "“Selene—”",
      "A bell rang below.",
      "Through the trees a young courier stood beside a narrow service bridge, pulling a warning cord. Water foamed against the first support. A woman on the far bank held a child on her hip.",
      "Selene felt the brief, intoxicating alignment of fear and purpose. Here was someone she could help. Here was a light that seemed to mean something simple.",
      "She asked Brío down the slope.",
      "He refused.",
      "This time she pressed him.",
      "He took three stiff steps. Mud slid under his hind foot. Selene hauled the rein, and the horse twisted to find his balance as the courier ran toward them. His boot struck a root. He fell badly, one arm trapped beneath him.",
      "The bridge gave a dry crack.",
      "Renata was off her mare and past them before Selene moved. She threw the woman a rope. The courier tried to rise and cried out. Water struck the bridge broadside and took half of it away.",
      "What followed came back to Selene later in separate pieces: Brío scrambling onto firm ground; her own hands dragging the courier by his coat; Renata planting her boots around a tree root; the child refusing to let go of a red shoe.",
      "They got everyone uphill.",
      "For a while, all Selene could hear was the river.",
      "The courier’s wrist swelled beneath Renata’s fingers. Renata asked his name. Tomás. He looked younger now that he was trying not to cry.",
      "“I’m sorry,” Selene said.",
      "He nodded without looking at her.",
      "She wanted him to say it was all right. She knew better than to ask.",
      "Across the water the jaguar climbed a shelf of rock. Something small emerged from the ferns beneath its belly: a cub, mud to its ears. The mother touched it with her nose and faced the broken bridge.",
      "Selene looked from the cub to the cat’s green light.",
      "“She was guarding the bank.”",
      "“Perhaps,” Renata said, tying a splint. “Now you have another piece of information.”",
      "“You could have stopped me.”",
      "“I told you to turn.”",
      "It was spoken without cruelty. Selene found that worse.",
      "They spent the night in a maintenance shelter above the flood line. At the shelter they found a station attendant. Renata sent him ahead on the grey mare for help; the woman and child slept near the stove. Brío stood under the awning, favouring no leg, but he moved away when Selene reached for him.",
      "She left her hand where he could see it.",
      "Eventually she put it down.",
      "At dawn Renata showed her the river schedule nailed inside the shelter. The emergency release was not due for another six days. Beside the date someone had stamped an amendment in blue ink.",
      "CONTINUITY RESERVE: INCREASED DRAW.",
      "“Solavila,” Renata said.",
      "“The city did this?”",
      "“The city signed a paper. We need to find out what the paper did.”",
      "Selene offered Tomás her remaining cash before remembering it belonged to another world. She put the useless notes away. Renata found her work instead: clean the shelter, boil water, carry his bag to the returning transport.",
      "When they lifted him into the cart, Selene said, “I made your route more dangerous.”",
      "“Yes,” he answered.",
      "“I’ll write what happened. Including what I did.”",
      "He studied her, then gave her the name of the office that handled injuries.",
      "After the cart left, she stood beside Brío for a long time. She brushed dried mud from his shoulder. When he shifted away, she followed only far enough to remain beside him.",
      "Upstream, the bell rang again.",
      "This time she listened to the horse."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/05.webp",
        "alt": "Selene and Brío stop on a forest trail before a golden jaguar mother whose cub hides near a root.",
        "caption": "A mother in the path"
      },
      {
        "src": "/images/books/selene-y-brio/06.webp",
        "alt": "A swollen river tears away a timber bridge while Selene and Brío remain on the rocky uphill bank.",
        "caption": "The bridge gives way"
      }
    ]
  },
  {
    "id": "a-place-to-stand",
    "number": 4,
    "title": "A Place to Stand",
    "subtitle": "The stone terraces · Foundation",
    "paragraphs": [
      "The bowl hit the ground for the fourth time, and Master Iolen Stoneward looked at Selene’s boots.",
      "“You keep trying to balance it with your face.”",
      "“It would help if it were flat.”",
      "“It’s a bowl.”",
      "He picked it up and placed it on the wall between them.",
      "Iolen repaired the old river terraces in exchange for meals, tools, and the privilege of complaining about other people’s mortar. Renata had brought Selene to him after the flood. He listened to her account, asked three questions about the bridge supports, and offered her an apprenticeship until the next supply cart reached Solavila.",
      "“For my gift?”",
      "“For the wall.”",
      "For six mornings she carried stone.",
      "Her palms blistered. Her shoulders learned to object before her pride did. Iolen showed her how to set the heaviest load close to her body and how to stop before her grip failed. When she tried to hurry, he took half the stones out of her basket and made her carry them twice.",
      "In the afternoons they sat beside the unfinished wall.",
      "He did not tell her to empty her mind.",
      "“Feel the place your heel meets the ground.”",
      "“I can still see everything.”",
      "“I didn’t ask you to stop seeing.”",
      "A beetle crossed the back of her hand. Green light moved through the hedge. Below them, a family of chigüires settled in a warm pool with the solemnity of people who had booked it in advance.",
      "Selene pressed her heel down. Stone. Damp leather. The weight of her own leg.",
      "For a moment the lights became part of a landscape she occupied.",
      "Then she thought, I’m doing it, and lost the feeling.",
      "Iolen handed her the bowl.",
      "By the eighth day she could carry it full of water from one end of the terrace to the other. On the ninth, he asked her a question halfway.",
      "“Why did you tell the horse to go?”",
      "Water splashed over her knuckles.",
      "“Someone needed help.”",
      "“Try the other reason.”",
      "She stared at the little pool darkening the dust.",
      "“Because I wanted to be certain.”",
      "He waited.",
      "“Because I’m tired of explaining what I see. I wanted one thing to happen that would prove it was useful.”",
      "Iolen took the bowl. “The wall still needs finishing.”",
      "She almost laughed. Then she did.",
      "That afternoon he showed her a simple Foundation working. A grounded palm, a narrow intention, enough Anima to steady one loose stone while the mortar settled. He demonstrated it with his own hand. Selene felt the fine vibration through the wall.",
      "When she tried, the stone shivered.",
      "Then every muscle in her forearm locked.",
      "Iolen lifted her hand immediately. “Enough.”",
      "“I nearly—”",
      "“Your hand is shaking. That is the answer for today.”",
      "She hated how little she had accomplished. An hour later she could not button her cuff.",
      "Seeing had never spent this part of her. Acting did.",
      "They waited two days before she tried again. This time she held a pebble steady for the space of an ordinary exhalation. Then she stopped while she still could.",
      "Iolen made no announcement about destiny.",
      "He gave her a better-fitting pair of work gloves.",
      "Renata visited at the end of the second week. She found Selene on the wall, laughing because Brío had carefully stolen a strip of sweet peel from Iolen’s pocket while the master was explaining discipline.",
      "“He looks well,” Renata said.",
      "“He’s an extortionist.”",
      "“He was that before.”",
      "The letter Renata carried was from Mercedes. Her mother had added a line at the bottom: Call me the moment anything in that place learns to use a telephone.",
      "Selene read it twice.",
      "Renata also brought news from the river. Three more stations had closed. The orchids below them had stayed open for four consecutive nights. Their petals were beginning to split.",
      "Iolen folded the notice.",
      "“The flowers need darkness to rest,” he said. “Whoever is drawing through those roots has forgotten what a pause is for.”",
      "Selene looked down at the wall they had finished that morning. Every stone rested on something.",
      "“What is the city resting on?” she asked.",
      "Iolen went to fetch his old survey maps."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/07.webp",
        "alt": "Selene rests her hands on warm stone beside an unfinished terrace as Master Iolen repairs the wall.",
        "caption": "The weight of a hand"
      },
      {
        "src": "/images/books/selene-y-brio/08.webp",
        "alt": "Selene rides Brío along broad stone terraces while capybaras rest beside a warm pool below.",
        "caption": "What holds us"
      }
    ]
  },
  {
    "id": "the-river-keeps-its-name",
    "number": 5,
    "title": "The River Keeps Its Name",
    "subtitle": "The morichal · Flow",
    "paragraphs": [
      "The ferrykeeper put Selene’s bag back on the bank.",
      "“Horse or luggage.”",
      "“There’s room.”",
      "“There is. There’s also a current.”",
      "Selene looked at the broad wooden ferry, the black water, and Brío, who had planted all four feet on dry ground. Iolen’s maps were wrapped inside her bag. So was the letter requesting an inspection of the city’s draw stations.",
      "“The papers have to come.”",
      "“Then you make two trips.”",
      "It took until afternoon to get Brío aboard. They loosened the ramp, moved a clattering chain, let him examine the boat, and waited. Selene led him on and straight off again twice. On the third attempt he stayed.",
      "The ferrykeeper pushed away without comment.",
      "She was a lean woman with a white scar across one knuckle and a laugh that arrived rarely but occupied considerable space. People at the landing called her Maestra. When Selene asked what she taught, she pointed to the boat.",
      "They crossed a country of palms and flooded grass. Giant otters surfaced near the reeds, calling to one another. Scarlet ibis lifted from a low island in a long red ribbon. No tepuis rose here; the land had opened over three days of travel until the sky seemed impossibly large.",
      "At the far bank, the ferrykeeper handed Selene a pole.",
      "“Tomorrow you can earn the second fare.”",
      "“I thought I’d paid.”",
      "“For passage. You asked about Flow.”",
      "Selene stayed four days.",
      "She learned where to place a foot on a moving deck. She learned that correcting too late required more force, and that a correction could itself tip the load. The ferrykeeper gave her a floating leaf to follow with her attention while ropes creaked, passengers asked questions, and Brío objected to a basket of chickens.",
      "“Come back to the leaf when you notice you’ve lost it.”",
      "“How often?”",
      "“As often as you lose it.”",
      "Selene tried to do this well enough to be praised. The ferrykeeper kept loading the boat.",
      "On the third night they crossed beneath water flowers opening pale as porcelain. Their wide leaves lifted against the hull. Selene saw blue-white Anima running along the veins, thinning toward the roots where a metal collar had been driven into the riverbed.",
      "The current pulled east.",
      "The river flowed west.",
      "She asked the ferrykeeper to stop.",
      "They tied up on an island and followed the buried pipe to a service chamber. Inside, the same mark from the closed station glowed on a glass gauge. CONTINUITY RESERVE.",
      "The gauge read NORMAL.",
      "Outside, a fallen flower smelled faintly sour.",
      "Selene wanted to tear the collar free. Instead she unfolded Iolen’s maps and checked the line. It connected to the city’s floodgates. The ferrykeeper showed her a maintenance wheel beneath the gauge.",
      "“Turn this without opening a relief channel and you send the whole head of water into the landing.”",
      "“Who taught you that?”",
      "“My mother. After somebody with a better education nearly washed us away.”",
      "They measured the water against a stake. They wrote the time. On the return crossing, Selene kept the leaf in sight while the ferrykeeper counted the beats between the gauge’s pulses. Four short. One long.",
      "At breakfast they compared the count with Iolen’s notes. The reserve was drawing during its scheduled rest.",
      "“Can you make it stop?” the ferrykeeper asked.",
      "“Not by myself.”",
      "“Good. Now you know how many people to bring.”",
      "When Selene left, the woman gave her a short length of red measuring cord. One knot marked each handspan.",
      "“No mystical significance,” she said when Selene examined it. “Don’t lose it.”",
      "That evening, Brío stepped onto a shallow ford without being pressed.",
      "Selene let him choose where to put his feet.",
      "Above the far bank, an orchid opened. It was beautiful enough to make her stop.",
      "Then she noticed the split running down its throat."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/09.webp",
        "alt": "Selene and Brío cross a raised wetland path among moriche palms as scarlet ibis traverse the dusk sky.",
        "caption": "The morichal"
      },
      {
        "src": "/images/books/selene-y-brio/10.webp",
        "alt": "Selene stands beside Brío on a wooden ferry while a grey-haired ferrywoman guides them across at night.",
        "caption": "The moving ground"
      }
    ]
  },
  {
    "id": "under-the-jaguars-sky",
    "number": 6,
    "title": "Under the Jaguar’s Sky",
    "subtitle": "The high road · The right to remain unknown",
    "paragraphs": [
      "Selene woke with Brío’s breath against her cheek.",
      "He was looking beyond the camp.",
      "The jaguar stood between two trees, its torn ear black against the moon. For one wild second Selene thought she had dreamed it there. Then the cat lowered its head and began to drink from the pool.",
      "Brío trembled.",
      "She moved slowly to his shoulder. The line of the escape path lay clear behind them. She took up the lead, keeping herself between him and the open slope only long enough to turn him toward it.",
      "The cat did not follow.",
      "At dawn she found its tracks beside the water. Smaller prints crossed them, then vanished into the ferns. The mother and cub had travelled upstream as the low banks flooded.",
      "Selene ate cold bread and waited until the forest sounds returned.",
      "The high road took them through wet stone and cloud. She walked beside Brío on the steepest sections. Pitcher plants grew in cracks beside the trail, their cups filled with clear water and the small remains of insects. Far below, the wetland had become a silver distance.",
      "By late afternoon she found the cause of the cat’s silence.",
      "A drainage grate had trapped the cub in a shallow stone basin. The mother paced above it. Each time Selene approached, the great head turned.",
      "The green light beneath the rosettes sharpened.",
      "Selene stopped.",
      "“I can see you,” she said softly. “That doesn’t mean I know you.”",
      "The sentence was for herself.",
      "She took Brío far enough away to wait behind a broad rock. The cat’s attention returned to the cub. Selene studied the grate. One hinge had rusted through; the other held fast. If she could lift it from the side, the opening might be wide enough.",
      "She remembered the stone trembling under her hand.",
      "No.",
      "She fetched a fallen branch instead.",
      "The first attempt broke the branch. The noise brought the jaguar forward. Selene retreated until the mother stopped, and waited, sweat cooling beneath her shirt. On the second attempt she stayed behind the grate’s stone housing. She fitted a stronger pole under the damaged hinge and put her weight on it.",
      "The metal rose.",
      "The cub scrambled out, all paws and indignation, and disappeared under its mother.",
      "Selene stepped back.",
      "Nothing happened that would have made a useful legend. The jaguar did not bow. It did not offer a name. It licked the cub’s wet head until the cub protested.",
      "Selene laughed once, breathless, then sat because her legs would no longer hold her.",
      "They camped on opposite sides of the valley.",
      "That night the mother limped down to the pool. It worried one forepaw, then rested it on a flat stone. Selene could see the thorn caught in the loose skin above the pad. She stayed beside the open path, watching until the cat stopped licking.",
      "Selene held out her empty hand.",
      "She waited through the ache in her arm. Brío stood behind her on a loose line, alert but no longer trying to leave.",
      "At last Selene approached from the side. The jaguar watched her hand and kept its paw on the stone. When its lip tightened she stopped. Only when its breathing settled again did she reach the last small distance.",
      "The fur was warm and coarser than she expected. She removed the thorn with two fingers. The cat’s breath moved the loose hair at her temple.",
      "For an instant her sight went very deep.",
      "She felt another attention arrive against her own: immense, particular, wholly uninterested in the person she had been trying to appear. Her palm prickled. She could have followed that presence farther.",
      "She let it go.",
      "The jaguar withdrew. Between the trees the cub made an impatient sound.",
      "Before she slept, Selene wrapped the thorn she had removed in paper, labelled it with the date, and put it in her bag.",
      "Then she wrote a second line beneath the first.",
      "I helped. I was also afraid.",
      "Both lines remained.",
      "On the next ridge, Solavila appeared beyond the cloud. Its towers shone with a light so even that, for a moment, she could not see where the sun touched them."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/11.webp",
        "alt": "Selene levers open a rusted drainage grate so a jaguar cub can climb from the shallow basin.",
        "caption": "The cub at the grate"
      },
      {
        "src": "/images/books/selene-y-brio/12.webp",
        "alt": "A golden jaguar mother lowers her brow to Selene's outstretched hand as Brío stands quietly behind her.",
        "caption": "Permission"
      }
    ]
  },
  {
    "id": "the-city-without-an-evening",
    "number": 7,
    "title": "The City Without an Evening",
    "subtitle": "Solavila · The Kingdom of Light",
    "paragraphs": [
      "The guard brushed mud from Selene’s boot before asking her name.",
      "She looked down, startled.",
      "“For the glass,” he explained.",
      "A pale bridge curved ahead of her, clean enough to hold the reflection of Brío’s white star. Beyond it rose terraces, shaded courtyards, water running through channels cut with extraordinary care. Nothing crowded its neighbour. Even the signs seemed to know how much space a person needed to read them.",
      "Selene loved it immediately.",
      "She disliked herself for how quickly.",
      "After weeks of wet blankets and smoke, the room assigned to her at the travellers’ house felt like an act of generosity. There was hot water. A towel with no mysterious stains. A desk facing a flowering tree.",
      "She washed her hair twice.",
      "The city called itself the western welcome of the Kingdom of Light. Travellers entered here to petition the Academy or seek the counsel of visiting Luminors. Selene’s petition joined a tray with thirty others. Iolen’s letter, bearing a different seal, received an answer within an hour.",
      "Proctor Vyne Halcen met her in the reserve house.",
      "He wore a plain dark coat and carried a pencil sharpened at both ends. His light was steady, pale blue, with a narrow amber chord beneath it. Selene remembered the courier’s wrist and declined to decide what that meant.",
      "Vyne listened to her account without interrupting.",
      "Then he showed her the hospital.",
      "Its cooling rooms held medicines brought from three realms. Beside them, a ward of sleeping patients lay beneath lamps fed by the reserve. An attendant checked each bed before touching a gauge.",
      "“Five years ago,” Vyne said, “a failure lasted through the night. We moved thirty-seven people by hand. We lost six.”",
      "He said their names. Selene could not have repeated all six afterward, but she remembered that one had the same name as her mother.",
      "“The reserve draws beyond its rest interval,” she said.",
      "“Yes.”",
      "“The river stations are failing.”",
      "“The old schedule no longer meets demand.”",
      "“Then change the demand.”",
      "“To what?”",
      "She looked back through the ward window.",
      "Vyne waited, and she understood that he had arranged the visit to make the question difficult. It was still a difficult question.",
      "In the control room he showed her the lattice: glass, stone, water, and cultivated roots arranged to carry Anima into the city’s stores. The hospital consumed a small, protected share. Above it, a much larger line maintained the towers’ uninterrupted radiance.",
      "“That can go dark,” Selene said.",
      "“The towers stabilise the distribution.”",
      "“Do they need to stay that bright?”",
      "“Not all of them.”",
      "“Then why do they?”",
      "For the first time his pencil stopped moving.",
      "“We have never reduced them under load.”",
      "He offered her a place on the inspection team, subject to supervised training. Until then, her pass would cover the viewing terrace only. Her unusual sight could identify strains the gauges missed. Training, accommodation, a modest salary. She would be useful here in ways she knew how to understand.",
      "Then he opened a narrow case.",
      "Inside lay a pair of smooth translucent shutters, worn near the temples rather than over the eyes.",
      "“They filter the peripheral signatures. Some of our readers use them.”",
      "Selene touched one.",
      "The room became quiet.",
      "The gauges remained visible. Vyne’s face remained a face. For a moment she could look at him without doing another kind of work at the same time.",
      "Her eyes filled.",
      "Vyne looked away, allowing her that much privacy.",
      "“They’re yours,” he said.",
      "“What do they cost?”",
      "“It narrows the peripheral light reaching your attention. It spends no Anima and takes none from anyone you look at. Remove it and the effect ends.”",
      "“And if I take the position?”",
      "“You would read the lattice. Trained operators would perform the workings. Later, if you chose to train as an operator, that work would spend your own Anima.”",
      "“So I can use this without joining you.”",
      "“Yes.”",
      "She had prepared herself to refuse a trap. A useful offer was harder.",
      "She took off the shutters carefully.",
      "“I’ll borrow the temporary ones.”",
      "“And the position?”",
      "She looked at the spotless window. Outside, the flowering tree held every blossom open.",
      "“I need to see the night shift first.”"
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/13.webp",
        "alt": "Selene and Brío enter Solavila across a pale stone-and-glass bridge above luminous terraces and waterways.",
        "caption": "Solavila"
      },
      {
        "src": "/images/books/selene-y-brio/14.webp",
        "alt": "Selene holds a translucent temple shutter at a white-stone desk while Proctor Vyne stands beside a root-and-glass mechanism.",
        "caption": "A moment of silence"
      }
    ]
  },
  {
    "id": "the-garden-that-could-not-sleep",
    "number": 8,
    "title": "The Garden That Could Not Sleep",
    "subtitle": "The reserve’s edge · A refusal",
    "paragraphs": [
      "At two in the morning, Selene found a gardener cutting the dead centres from perfect flowers.",
      "He dropped the brown pieces into a covered basket.",
      "“Why not take the whole bloom?”",
      "“People complain.”",
      "“About dead flowers?”",
      "“About empty branches.”",
      "The tree outside her room had split along three limbs. Its blossoms still shone. Beyond the garden, light covered the city’s streets so thoroughly that Selene could see neither stars nor the shadows of the people walking beneath the lamps.",
      "She borrowed a lantern and went to the stables.",
      "Brío lifted his head when she entered. She let him smell the shutters before putting them in her bag. His nostrils moved over her fingers. No sudden terror. No transformation. Just the warm, useful fact of him.",
      "They rode out before sunrise.",
      "At the reserve’s edge, a patrol stopped them. Vyne’s temporary pass admitted Selene to the viewing terrace. It did not admit her to the lower stations.",
      "“The order is for my safety?”",
      "“And the system’s.”",
      "She handed the pass back. “Then tell him I’m outside the system.”",
      "It was a fine line. She regretted it before the guard had finished writing it down.",
      "She went to the public landing instead.",
      "The ferrykeeper was unloading baskets of fish so small that three fitted across her palm. She looked at Selene’s clean shirt, then at her face.",
      "“You saw the hospital.”",
      "“Yes.”",
      "“People always return from the hospital as though we haven’t got sick people here.”",
      "Selene took the next basket without answering.",
      "Renata arrived that afternoon with Iolen and a cart full of tools. She also brought Tomás, his wrist bound but healing, and three station keepers whose wages had continued arriving after their stations closed.",
      "They spread the maps on an upturned boat.",
      "Each person had a different piece. Iolen knew the stone bypasses. The ferrykeeper knew the old flood marks. The station keepers knew which wheels were seized. Tomás knew the maintenance tunnels because he had spent two winters carrying replacement lenses through them.",
      "Selene could see the living current.",
      "It was useful. It was not enough.",
      "Together they found a route through the plans: open the western relief beds, drain the tower circuit in sections, preserve the hospital’s isolated reservoir, and return the night draw to the marsh. The work required the reserve-house crew. It required Vyne. The relief beds would also flood the city's lower garden and threaten two storehouses built where Iolen's old map showed open ground. They marked the buildings for evacuation.",
      "Renata volunteered to take the proposal.",
      "“He’ll say no,” Selene said.",
      "“Then he can say it to the people whose water he’s using.”",
      "They waited.",
      "At dusk, the marsh flowers began to glow. Huge white bowls opened above the black water, their edges bruised purple. Brío stood beside Selene on a low island while the last ibis crossed westward.",
      "Under the nearest flower, a fish lay belly-up.",
      "Selene removed the temporary shutters.",
      "The Anima current ran bright and wrong beneath the surface. Four short pulses. One long. Then the long pulse did not end.",
      "The roots tightened.",
      "A sound travelled across the marsh like cloth tearing from one horizon to the other. The flower above her folded sharply inward. Brío jerked his head up.",
      "From the city came the first alarm.",
      "Tomás ran from the landing with a message strip in his good hand.",
      "Vyne had agreed to an inspection at dawn.",
      "The reserve had begun its new permanent cycle at dusk. Vyne had authorised the automatic change three days earlier; the inspection had not suspended it. Once under load, the master valve could only be closed after the relief beds opened. His message included the valve sequence and his seal.",
      "Selene read the strip twice. Then she handed it to the ferrykeeper.",
      "“Can we open the relief beds before the city releases its emergency water?”",
      "The woman looked at the rising line on the stake.",
      "“If we start now.”",
      "Selene turned toward Brío. He was watching the slope that led away from the water.",
      "This time she followed his gaze."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/15.webp",
        "alt": "Selene rides Brío from the luminous city toward a dark wetland while a tool cart follows toward the river.",
        "caption": "Returning to the marsh"
      },
      {
        "src": "/images/books/selene-y-brio/16.webp",
        "alt": "A colossal white water flower folds inward above Selene and Brío on a raised island in the night marsh.",
        "caption": "The flower folds"
      }
    ]
  },
  {
    "id": "the-road-beneath-the-waterfall",
    "number": 9,
    "title": "The Road Beneath the Waterfall",
    "subtitle": "The western bypass · Choosing a way through",
    "paragraphs": [
      "Brío stopped at the mouth of the tunnel, and Selene got down.",
      "The alarm bell rang somewhere beyond the dark. Water dropped from the lintel onto the horse’s ears.",
      "Behind them, the landing crew were hauling the last boat above the flood mark. The western relief wheel lay through this service passage, beneath the old escarpment. Without it, opening the city gates would crush the settlement against its own embankment.",
      "Renata had gone to the reserve house with the valve sequence. Iolen and two keepers were already hauling an iron brace along the upper road. The tunnel saved twenty minutes, but its ledge could not carry their cart. Selene and Tomás would reach the wheel first and establish the old bell relay; the third keeper remained with the ferry crew.",
      "Selene loosened the girth and took off the saddlebags.",
      "“I can walk from here.”",
      "Tomás looked into the tunnel. “You won’t reach the far station before the release.”",
      "He could run the first section, but his wrist would not let him turn the heavy signalling crank. Brío could carry the wedge and tools and bring Selene to the wheel. He could also refuse.",
      "The horse lifted his head, listening.",
      "Selene took the bell rope where it ran beside the entrance. She followed it to a brass housing and wrapped her spare shirt around the clapper. The alarm became a dull knock.",
      "Brío breathed out.",
      "She walked him to the entrance and waited. She felt the wet ground through her boots. She let her own breath arrive without arranging it into something impressive.",
      "One ear came forward.",
      "They entered at a walk.",
      "The tunnel widened into a cavern behind the waterfall. Through the falling water Selene glimpsed a sky streaked with lightning. Pale roots descended into the rock, their Anima pulled taut toward the city. The sound was enormous, yet Brío’s breathing remained close enough to count without trying.",
      "At a fork, the official route dipped into rising water.",
      "Brío turned left.",
      "Tomás checked the marks on the wall. “Old inspection ledge. It might still connect.”",
      "“Might?”",
      "“I haven’t used it.”",
      "Selene examined the floor with the lantern. Dry grit. Recent hoofprints from the station mule. A repaired rail farther ahead.",
      "“We try it slowly.”",
      "The ledge brought them above the submerged corridor. At its far end, Tomás stayed with the signalling crank, above the ravine and in sight of the relief station. Its repeater line connected to the city bells. Selene remounted beyond the last low beam and asked Brío forward on the open service road.",
      "He went.",
      "They emerged beneath a sky torn with rain. The relief station stood on the opposite bank of a shallow stone spillway. Between it and Selene, the giant jaguar carried her cub by the scruff, crossing the last dry shelf toward high ground.",
      "Selene waited.",
      "The cat passed without looking at her. Its tracks showed where the water lay shallowest. She checked the footing, then let Brío approach.",
      "Together they crossed.",
      "At the station, the wheel would not turn.",
      "Selene measured the rising water with the ferrykeeper’s red cord. One knot vanished. Then another.",
      "She found the fault under the wheel housing: a root had forced a stone shoe sideways, trapping the spindle. A long crack ran through the supporting block.",
      "The living current shimmered along the root, splitting where it pressed against glass.",
      "She took out the stone of the veils.",
      "One breath.",
      "The lens separated the current from its reflection. The real strain ran beneath the spindle; the bright line above it was an echo in the wet glass.",
      "Second breath.",
      "She marked the lower seam with charcoal.",
      "The stone went cold.",
      "She pushed it back against her chest. No third breath would improve the mark now. She placed Iolen’s wedge against the seam and struck it with a maintenance hammer.",
      "The wedge moved.",
      "So did the crack.",
      "Selene stopped hitting.",
      "On the far side of the ravine, Tomás sounded the signal: the reserve-house crew were ready.",
      "She answered once. Wait.",
      "Then she put her palm on the stone and tried to remember exactly how little she could hold."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/17.webp",
        "alt": "Inside a cavern behind a waterfall, Selene leads Brío along a broad rock ledge threaded with pale roots.",
        "caption": "Behind the waterfall"
      },
      {
        "src": "/images/books/selene-y-brio/18.webp",
        "alt": "Selene and Brío wait beside a spillway as a golden jaguar carries her cub across a raised shelf to safety.",
        "caption": "The crossing she waits for"
      }
    ]
  },
  {
    "id": "a-city-learns-the-dark",
    "number": 10,
    "title": "A City Learns the Dark",
    "subtitle": "The relief station · The cost of acting",
    "paragraphs": [
      "The stone pressed back against Selene’s hand.",
      "She set her heels. She kept the intention small: this seam, this moment, long enough for the wedge to move.",
      "Anima passed through her arm with a force that made her teeth ache.",
      "The crack steadied.",
      "She drove the wedge once.",
      "The spindle shifted. Water struck the far side of the gate, and the crack began to open again.",
      "Selene took her hand away.",
      "For a second she could not feel her fingers.",
      "She had wanted to stay until the work was finished. Her hand was shaking too hard to close. Iolen’s voice, irritatingly ordinary, returned to her: That is the answer for today.",
      "She sounded the alarm for assistance.",
      "It was the signal she had least wanted to use.",
      "Across the ravine, Tomás repeated it. The repeater bells carried it to Renata at the reserve house and to Iolen, already coming down the upper road.",
      "Selene sat on the dry edge of the platform. Brío stood in the station's small stone-walled mule pen beside her, his bridle removed and the gate latched. She leaned her forehead against his shoulder.",
      "“I can’t hold it.”",
      "His skin twitched under a fly.",
      "She began to laugh, then cried instead.",
      "The wheel turned a fraction under the water’s pressure. Somewhere inside the stone, something clicked.",
      "She wiped her face with the clean part of her sleeve and took up the red cord. She could still measure. She could still send a signal. She did both.",
      "The level rose to the next knot.",
      "From the city, a new signal answered: HOSPITAL RESERVOIR ISOLATED.",
      "Then: TOWER CIRCUIT HELD.",
      "Vyne had chosen.",
      "The towers dimmed one by one. Their reflections shortened across the marsh. For the first time since Selene had entered Solavila, a patch of sky appeared between them.",
      "The wheel eased.",
      "Iolen arrived with two station keepers by the upper road, breathing hard and furious about the condition of the steps. He examined the charcoal mark, the wedge, and Selene’s hand.",
      "“You stopped.”",
      "“Yes.”",
      "“Good. Give me the cord.”",
      "He knelt against the stone while the keepers fitted an iron brace. Selene called the measurements. When the brace took the load, Iolen removed his palm. His whole body sagged. One keeper gave him an arm; the other braced her boots against the wheel.",
      "Together they turned it.",
      "The relief gate opened a handspan.",
      "Water entered the old beds in a heavy, controlled sheet. The first channel filled. The second took the overflow. Selene watched the Anima current loosen along the roots.",
      "“Hold there,” she said.",
      "The keeper looked at Iolen.",
      "He nodded toward Selene. “She can see that part.”",
      "Four short pulses.",
      "One long.",
      "Then a pause.",
      "Across the marsh, the flowers began to close.",
      "The city crew opened the next gate. The ferrykeeper’s lantern moved along the landing as people checked the moorings. Tomás sent the all-clear from the tunnel and then, because he had only one good hand and was tired of cranking, added a much less formal signal.",
      "Selene laughed so hard it hurt.",
      "They spent the rest of the night making sure the first success did not become a second flood.",
      "By dawn, two storehouses were damaged. The lower garden was gone. A station keeper had broken an ankle, and a week’s supply of fish spoiled before it could reach the market. The hospital lamps had stayed on.",
      "Vyne arrived carrying a ledger that had got wet at one corner.",
      "He asked for everyone’s names.",
      "“For the inquiry,” he said before Selene could speak. “Including mine.”",
      "She gave him the written account of the bridge accident, folded inside Iolen’s original letter. He read the first page, then placed it with his own report.",
      "The sun rose on a city less brilliant than the one she had entered.",
      "Below the relief station, the jaguar and her cub lay on a dry shelf above the river. The mother’s eyes followed a moving shadow in the reeds.",
      "Selene left them their distance.",
      "Her own hands remained bare of light.",
      "She used them to pass Iolen a cup of water."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/19.webp",
        "alt": "Exhausted, Selene kneels on a dry platform and withdraws her shaking hand from a cracked support block.",
        "caption": "Enough for today"
      },
      {
        "src": "/images/books/selene-y-brio/20.webp",
        "alt": "Selene and Brío watch Solavila's ivory towers dim beneath a star-filled sky as water flows into relief beds.",
        "caption": "The first dark towers"
      }
    ]
  },
  {
    "id": "the-open-courtyard",
    "number": 11,
    "title": "The Open Courtyard",
    "subtitle": "Crystalpeak · The Luminors",
    "paragraphs": [
      "The Luminor asked Selene to move her chair.",
      "“Into the light?”",
      "“Out of the doorway. Someone will trip.”",
      "Selene moved it.",
      "She had imagined this meeting often enough to be embarrassed by its ordinariness. The courtyard at Crystalpeak held three chairs, a fig tree, and a cat asleep on a folded coat. Beyond the open arch, bridges linked terraces suspended above cloud. Water vanished over their edges without reaching any bottom she could see.",
      "She had arrived after twelve days of recovery and testimony in Solavila, then a supervised passage through the Academy corridor. Brío travelled with the supply caravan and now occupied a stable with a view he appeared to consider inferior to its hay.",
      "Iolen introduced her to Ada Rell and Tovan Reed. Both had opened all ten Gates; both, he warned her, were quite capable of saying they did not know.",
      "Ada was an older woman with brown hands and silver hair cut at the jaw. Tovan, a quiet man in a green work coat, was mending the courtyard latch. Neither wore a crown.",
      "Their destellos were difficult to look at. The colours remained distinct without pulling apart. Selene felt the reach of that attention before the woman asked, “May I?”",
      "She nodded.",
      "The woman looked at her.",
      "Selene’s throat tightened. She resisted the urge to tell a better version of the story.",
      "“What do you want to learn?”",
      "“How to bear it.”",
      "“All of it?”",
      "“I don’t know how to choose.”",
      "The man at the door set down his tool. “That is something we can teach.”",
      "The first exercise used the courtyard fountain. Selene attended to one falling thread of water, then to the whole sound, then to the pressure of the chair beneath her. Ada asked her to shift her attention before she felt compelled to shift it.",
      "At first she could not. Attention stuck where fear put it.",
      "They practised. When Selene grew frustrated, they paused. Nobody called the pause a failure.",
      "Over the following weeks the exercises became harder. She learned to look at a destello without leaning into it, to withdraw from deep resonance before it became reciprocal contact, and to ask permission when a closer reading might expose something a person had not chosen to share. The gift did not become a language with a convenient dictionary. Amber still belonged to many moments. Light still required a life around it.",
      "One afternoon she asked the question she had brought from Caracas.",
      "“What colour am I?”",
      "Ada studied her.",
      "“If I answer, what will you do with it?”",
      "“Believe you.”",
      "“For how long?”",
      "Selene looked at the open doorway. “Until I thought it had changed.”",
      "The woman nodded.",
      "“Can it change?”",
      "“Yes.”",
      "“Then tell me something I can use.”",
      "“You tend to reach farther when you think you are being evaluated. It strains your breathing. When you help without watching for a verdict, your attention steadies.”",
      "Selene thought of the bowl. The bridge. Her hand leaving the cracked stone.",
      "“That sounds less beautiful than I hoped.”",
      "“It is more useful.”",
      "They laughed.",
      "At the end of the month she received an offer to stay for the Foundation term. No promise of mastery. No honorary rank. A room, instruction, work in the gardens, and enough time to learn deliberately.",
      "She accepted half the year.",
      "The Luminor lifted an eyebrow.",
      "“My family is in Caracas. Renata needs someone on the river route. I want to be here, but I’m not disappearing into a place because it finally understands one part of me.”",
      "“Write that into your agreement.”",
      "Selene did.",
      "On the last evening before her return, she rode Brío to an overlook above the citadel. The Kingdom of Light lay beneath them in terraces, valleys, and distant inhabited points. Darkness occupied most of the view. It gave each light somewhere to be.",
      "Tovan joined her at the rail.",
      "“Will it ever stop being difficult?” she asked.",
      "“Some of it.”",
      "“And the rest?”",
      "“You will have more choices.”",
      "Brío reached for a flowering branch. Selene moved it out of range.",
      "“For example,” the Luminor said.",
      "She laughed, and for once did not check the sound of it against anyone else’s light."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/21.webp",
        "alt": "Selene observes falling water beside a courtyard fountain while two simply dressed Luminors teach nearby.",
        "caption": "The open courtyard"
      },
      {
        "src": "/images/books/selene-y-brio/22.webp",
        "alt": "Selene sits on Brío at a broad overlook beside a Luminor, gazing across cloud terraces and deep inhabited valleys.",
        "caption": "Room for the stars"
      }
    ]
  },
  {
    "id": "the-road-she-chose",
    "number": 12,
    "title": "The Road She Chose",
    "subtitle": "Two homes · A beginning she could keep",
    "paragraphs": [
      "Mercedes criticised the repair to Selene’s sleeve before she began to cry. Selene had been away for ten weeks.",
      "“The stitches are too far apart.”",
      "“I was using a saddle needle.”",
      "“Clearly.”",
      "Then the old woman put both arms around her and held on.",
      "Her mother waited until Mercedes let go. She touched Selene’s cheek, the new callus at the base of her thumb, the place where the saddle had rubbed a seam into her trousers.",
      "“You look tired.”",
      "“I am.”",
      "“Happy?”",
      "“Sometimes.”",
      "Her mother kissed her forehead. “There’s food.”",
      "Caracas had continued without her. The building’s lift worked again, though only if the door was closed with a particular force. Her colleague’s sister had had a daughter. The project Selene left behind had acquired three new deadlines and a blue heading she disliked on sight.",
      "She went back to the office for a meeting.",
      "Light stirred around people as it always had. She used the temporary shutters for the crowded journey there, then put them away at her desk. Relief was a tool she could choose. She no longer needed to make refusing it a proof of strength.",
      "Her colleague caught her looking at the blue heading.",
      "“Too much?”",
      "“Yes,” Selene said. “That time I mean the layout.”",
      "They laughed.",
      "She negotiated fewer hours for the coming months. It cost money. She made a budget. The numbers would not become more agreeable because she had ridden through a magical forest.",
      "At home she sorted the photographs. Some were blurred. In one, Brío’s nose filled the entire frame. In another, a white flower shone over black water before the failure, already bruised at its edges.",
      "She placed that one beside the photograph she had taken after the gates opened: closed petals, plain darkness, a small boat with a single lamp.",
      "She sent both to her mother.",
      "Later, at Mercedes’s table, they spoke about the years of silence. The first conversation did not repair them. Neither did the second. On the third, Mercedes said, “I should have trusted you to be angry with me.”",
      "Selene looked at her grandmother’s hands.",
      "“Yes.”",
      "They made coffee.",
      "A month later, the passage opened again.",
      "Selene crossed with letters, replacement needles, and the coffee Iolen had requested after insisting he disliked it. Renata was waiting at the stable gate. Brío heard Selene before he saw her and lifted his head from the hay.",
      "She did not ask anyone what the movement meant.",
      "She went to him.",
      "The river route had changed. Tomás now supervised two new couriers and objected to Selene’s handwritten incident forms on the grounds that no one could read them. The ferrykeeper had replaced her measuring stake. Iolen’s terrace held through the first heavy rain.",
      "In Solavila, Vyne’s new schedule was posted at every station. It named the hours of rest, the emergency limits, and the people permitted to halt the draw. River crews now held one of the required keys. The inquiry continued. So did the repairs.",
      "Some towers stayed dark.",
      "People had started meeting beneath them to watch the stars.",
      "Selene rode out with Renata’s blessing and Brío’s evident interest in leaving the yard. Her first assignment was modest: inspect the western beds, deliver a letter, return before the evening storm. She would begin the Academy term in six weeks.",
      "On the high road she saw the jaguar again.",
      "The cub had grown into its paws. Mother and young crossed a distant ledge, paused where the sun reached the rock, and vanished into the green.",
      "Selene did not call.",
      "Beyond the ledge, a bank of flowers moved in the wind. The orchids were closing at last, and behind them a narrow trail caught the morning light. Brío lengthened his stride when she asked.",
      "For several minutes there was only the rhythm of the horse, the wet scent of leaves, and the sound of water below.",
      "Then, beneath the water's rhythm, another sound reached her.",
      "Far to the east, beyond the known passes, light moved along a mountain she had never seen on Renata’s maps. She lifted the warm lens for two breaths. The line resolved into a succession of living signatures, too distant to distinguish: something was moving through the forest high above the clouds.",
      "The stone went cold. She lowered it. The mountain remained, plain and far away.",
      "Brío stopped.",
      "Selene took a breath and looked at the sky. Rain would come by evening. There was a letter to deliver, a horse to feed, and a new sound she did not yet understand.",
      "She marked the mountain’s position in her notebook.",
      "Then she turned Brío toward the river.",
      "They would have time to learn its name."
    ],
    "images": [
      {
        "src": "/images/books/selene-y-brio/23.webp",
        "alt": "In a warm Caracas kitchen, Selene embraces her grandmother Mercedes while her mother rests a hand on her shoulder.",
        "caption": "Home can change"
      },
      {
        "src": "/images/books/selene-y-brio/24.webp",
        "alt": "Selene rides Brío at an easy canter beneath closing violet orchids, above a dawn-lit river and distant tepuis.",
        "caption": "The road she chose"
      }
    ]
  }
];
