"use client";

import { m, useInView } from "framer-motion";
import { MotionProvider } from "@/lib/motion";
import Image from "next/image";
import Link from "next/link";
import { useRef, useState, useEffect } from "react";
import {
  ArrowRight,
  ArrowUpRight,
  Diamond,
  Scroll,
  Crown,
  PaintBrush,
  Tree,
  Eye,
  Palette,
  Plus,
  Minus,
  Quotes,
} from "@/lib/phosphor-icons";
import { GlowCard } from "@/components/ui/glow-card";
import { HowItWorks } from "@/components/landing/how-it-works";
import { CTASection } from "@/components/landing/cta-section";
import { LivingLoreCTA } from "@/components/landing/living-lore-cta";
import { ThreeLayersSection } from "@/components/landing/three-layers-section";
import crystalImage from "@/assets/brand/arcanea-crystal.jpg";
import { getFeaturedLuminors } from "@/lib/luminor-images";

// ---------------------------------------------------------------------------
// Data
// ---------------------------------------------------------------------------


interface Guardian {
  name: string;
  gate: string;
  element: string;
  quote: string;
  image: string;
  glowColor: string;
  accentHex: string;
}

const FEATURED_GUARDIANS: Guardian[] = [
  {
    name: "Lyssandria",
    gate: "Foundation",
    element: "Earth",
    quote: "Build the foundation first. Everything else is architecture.",
    image: "/guardians/v3/lyssandria-hero-v3.webp",
    glowColor: "rgba(0, 188, 212, 0.18)",
    accentHex: "#00bcd4",
  },
  {
    name: "Draconia",
    gate: "Fire",
    element: "Fire",
    quote: "I do not ask if you are ready. I ask if you are willing.",
    image: "/guardians/v3/draconia-hero-v3.webp",
    glowColor: "rgba(239, 68, 68, 0.18)",
    accentHex: "#ef4444",
  },
  {
    name: "Lyria",
    gate: "Sight",
    element: "Void",
    quote: "Close your eyes. Now tell me what you see.",
    image: "/guardians/v3/lyria-hero-v3.webp",
    glowColor: "rgba(168, 85, 247, 0.18)",
    accentHex: "#a855f7",
  },
  {
    name: "Leyla",
    gate: "Flow",
    element: "Water",
    quote: "The river does not push. It finds the way.",
    image: "/guardians/v3/leyla-hero-v3.webp",
    glowColor: "rgba(59, 130, 246, 0.18)",
    accentHex: "#3b82f6",
  },
  {
    name: "Shinkami",
    gate: "Source",
    element: "Spirit",
    quote: "You are not the vessel. You are the water and the pouring.",
    image: "/guardians/v3/shinkami-hero-v3.webp",
    glowColor: "rgba(255, 215, 0, 0.15)",
    accentHex: "#ffd700",
  },
  {
    name: "Maylinn",
    gate: "Heart",
    element: "Air",
    quote: "What you create with love will outlast everything made from fear.",
    image: "/guardians/v3/maylinn-hero-v3.webp",
    glowColor: "rgba(34, 197, 94, 0.18)",
    accentHex: "#22c55e",
  },
];

const ALL_GUARDIANS = [
  {
    name: "Lyssandria",
    gate: "Foundation",
    image: "/guardians/v3/lyssandria-hero-v3.webp",
  },
  { name: "Leyla", gate: "Flow", image: "/guardians/v3/leyla-hero-v3.webp" },
  { name: "Draconia", gate: "Fire", image: "/guardians/v3/draconia-hero-v3.webp" },
  { name: "Maylinn", gate: "Heart", image: "/guardians/v3/maylinn-hero-v3.webp" },
  { name: "Alera", gate: "Voice", image: "/guardians/v3/alera-hero-v3.webp" },
  { name: "Lyria", gate: "Sight", image: "/guardians/v3/lyria-hero-v3.webp" },
  { name: "Aiyami", gate: "Crown", image: "/guardians/v3/aiyami-hero-v3.webp" },
  { name: "Elara", gate: "Starweave", image: "/guardians/v3/elara-hero-v3.webp" },
  { name: "Ino", gate: "Unity", image: "/guardians/v3/ino-hero-v3.webp" },
  { name: "Shinkami", gate: "Source", image: "/guardians/v3/shinkami-hero-v3.webp" },
];

const FEATURES = [
  {
    icon: Diamond,
    title: "16 Creative Intelligences",
    description:
      "Sixteen specialized AI minds across four teams — each trained on proprietary creative philosophy, not generic AI. Distinct expertise in music, writing, art, and world-building.",
    href: "/chat",
    accentHex: "#00bcd4",
    glowColor: "rgba(0, 188, 212, 0.15)",
  },
  {
    icon: Scroll,
    title: "Intelligence Library",
    description:
      "190K words of proprietary creative intelligence — not generic AI writing, original philosophy grounded in consciousness, creativity, and transformation. 17 collections, 34+ texts.",
    href: "/library",
    accentHex: "#ffd700",
    glowColor: "rgba(255, 215, 0, 0.12)",
  },
  {
    icon: Crown,
    title: "Training Academy",
    description:
      "10 progressive mastery gates, each with specialized AI training. A developmental framework from Apprentice to Luminor — earned through creation, not consumption.",
    href: "/academy",
    accentHex: "#0d47a1",
    glowColor: "rgba(13, 71, 161, 0.15)",
  },
  {
    icon: PaintBrush,
    title: "Creation Gallery",
    description:
      "364+ original artworks generated by the creative intelligence system — companion portraits, landscapes, creatures, and artifacts of the Arcanea universe.",
    href: "/gallery",
    accentHex: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.12)",
  },
  {
    icon: Tree,
    title: "Knowledge Graph",
    description:
      "An interactive force-directed map of every text, collection, and connection in the Library.",
    href: "/library/graph",
    accentHex: "#00897b",
    glowColor: "rgba(0, 137, 123, 0.15)",
  },
  {
    icon: Scroll,
    title: "Creative Intelligence",
    description:
      "The founding mythology that trains every AI in the system — Lumina, Nero, the Ten Guardians, and the cosmic architecture of creation.",
    href: "/lore",
    accentHex: "#a78bfa",
    glowColor: "rgba(167, 139, 250, 0.12)",
  },
];

const PATHWAYS = [
  {
    title: "Explore the Mythology",
    description:
      "Discover the cosmology, the Guardians, and the philosophical framework behind everything.",
    href: "/lore",
    image: "/guardians/v3/shinkami-hero-v3.webp",
  },
  {
    title: "Create in Studio",
    description:
      "Write, generate images, compose music, and build with multi-model AI flows.",
    href: "/studio",
    image: "/guardians/v3/lyssandria-hero-v3.webp",
  },
  {
    title: "Build Worlds",
    description:
      "Design places, systems, factions, and entire mythologies from scratch.",
    href: "/studio",
    image: "/guardians/v3/lyria-hero-v3.webp",
  },
  {
    title: "Compose Music",
    description:
      "Create original music with AI-guided composition and melody-driven prompts.",
    href: "/studio",
    image: "/guardians/v3/leyla-hero-v3.webp",
  },
  {
    title: "Start a Conversation",
    description:
      "Get feedback, brainstorm ideas, or work through a creative problem with a thinking partner.",
    href: "/chat",
    image: "/guardians/v3/draconia-hero-v3.webp",
  },
  {
    title: "Read the Library",
    description:
      "Laws, meditations, parables, and practical philosophy for creators.",
    href: "/library",
    image: "/guardians/v3/alera-hero-v3.webp",
  },
  {
    title: "Write with AI",
    description:
      "Co-author stories, chapters, and series with an AI writing partner.",
    href: "/chat/chronica",
    image: "/guardians/v3/maylinn-hero-v3.webp",
  },
];

const FAQ_ITEMS = [
  {
    q: "What makes Arcanea different from other AI tools?",
    a: "Sixteen specialized AI intelligences, each trained on 190K words of original creative philosophy — not generic AI. A three-layer intelligence architecture, 17 knowledge collections, and a 10-gate mastery framework. You pick the mind that fits your project.",
  },
  {
    q: "How do the AI intelligences work?",
    a: "Each intelligence is specialized for a creative domain — writing, research, design, music, strategy. Trained on proprietary philosophy, not generic datasets. Pick one, describe your project, and build together.",
  },
  {
    q: "What is the Intelligence Library?",
    a: "190K+ words of proprietary creative intelligence across 17 collections. Laws, meditations, parables, and dialogues — the knowledge foundation that trains every AI in the system.",
  },
  {
    q: "What is the Ten Gates system?",
    a: "A progression framework from Apprentice to Luminor. Each Gate maps to a creative capacity. Progress is earned through creation, not purchases.",
  },
  {
    q: "Is Arcanea free?",
    a: "Free to start, no credit card required. Full access to the Library, Gallery, and Academy. Three companions on the free plan.",
  },
  {
    q: "Is my work private?",
    a: "Yes. We do not train on your data. What you build stays yours -- keep it in Arcanea or export it.",
  },
];

// ---------------------------------------------------------------------------
// Utility: CountUp
// ---------------------------------------------------------------------------

function CountUp({ target, suffix = "" }: { target: number; suffix?: string }) {
  const ref = useRef<HTMLSpanElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });
  const [count, setCount] = useState(0);

  useEffect(() => {
    if (!isInView) return;
    const steps = 50;
    const increment = target / steps;
    let current = 0;
    const timer = setInterval(() => {
      current += increment;
      if (current >= target) {
        setCount(target);
        clearInterval(timer);
      } else {
        setCount(Math.floor(current));
      }
    }, 1600 / steps);
    return () => clearInterval(timer);
  }, [isInView, target]);

  return (
    <span ref={ref}>
      {count.toLocaleString()}
      {suffix}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Atmospheric Divider
// ---------------------------------------------------------------------------

function AtmosphericDivider({
  variant = "teal",
}: {
  variant?: "teal" | "purple" | "gold";
}) {
  const colors = {
    teal: "rgba(0,188,212,0.06)",
    purple: "rgba(13,71,161,0.06)",
    gold: "rgba(255,215,0,0.04)",
  };
  return (
    <div className="relative h-px">
      <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/[0.06] to-transparent" />
      <div
        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] h-[200px] pointer-events-none"
        style={{
          background: `radial-gradient(ellipse, ${colors[variant]}, transparent 70%)`,
        }}
      />
    </div>
  );
}

// ---------------------------------------------------------------------------
// SECTION 1: Metrics Strip — Iridescent Glass
// ---------------------------------------------------------------------------

function MetricsStrip() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-60px" });

  const metrics = [
    { value: 16, suffix: "", label: "AI Intelligences", color: "#00bcd4", icon: Eye },
    {
      value: 17,
      suffix: "",
      label: "Collections",
      color: "#ffd700",
      icon: Scroll,
    },
    {
      value: 190,
      suffix: "K+",
      label: "Words of Intelligence",
      color: "#0d47a1",
      icon: Diamond,
    },
    {
      value: 364,
      suffix: "+",
      label: "Original Artworks",
      color: "#00897b",
      icon: Palette,
    },
  ];

  return (
    <section ref={ref} className="py-20 md:py-28">
      <div className="max-w-5xl mx-auto px-6">
        <GlowCard
          glass="iridescent-glass"
          glowColor="rgba(0, 188, 212, 0.08)"
          glowSize={600}
          lift={false}
          className="border border-white/[0.08] p-8 md:p-12"
        >
          {/* Glass noise texture */}
          <div className="absolute inset-0 glass-noise opacity-[0.2] pointer-events-none rounded-2xl" />
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-12 relative">
            {metrics.map((metric, i) => {
              const Icon = metric.icon;
              return (
                <m.div
                  key={metric.label}
                  className="text-center"
                  initial={{ opacity: 0, y: 16 }}
                  animate={isInView ? { opacity: 1, y: 0 } : {}}
                  transition={{ duration: 0.5, delay: i * 0.1 }}
                >
                  <div
                    className="w-10 h-10 rounded-xl mx-auto mb-4 flex items-center justify-center"
                    style={{
                      background: `linear-gradient(135deg, ${metric.color}18, ${metric.color}08)`,
                      border: `1px solid ${metric.color}20`,
                    }}
                  >
                    <Icon className="w-5 h-5" style={{ color: metric.color }} />
                  </div>
                  <div
                    className="text-3xl md:text-5xl font-display font-bold tracking-tight mb-2"
                    style={{ color: metric.color }}
                  >
                    <CountUp target={metric.value} suffix={metric.suffix} />
                  </div>
                  <p className="text-xs text-white/35 tracking-wide uppercase font-mono">
                    {metric.label}
                  </p>
                </m.div>
              );
            })}
          </div>
        </GlowCard>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// SECTION 3: Three Pillars — Bento Grid with GlowCards
// ---------------------------------------------------------------------------

function ThreePillars({
  collectionsCount,
  textsCount,
  totalWords,
}: {
  collectionsCount: number;
  textsCount: number;
  totalWords: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section ref={ref} className="py-24 md:py-36 relative">
      {/* Atmospheric background */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-0 left-1/4 w-[600px] h-[400px] bg-[radial-gradient(ellipse,rgba(0,188,212,0.04),transparent_60%)] pointer-events-none" />
        <div className="absolute bottom-0 right-1/4 w-[500px] h-[400px] bg-[radial-gradient(ellipse,rgba(13,71,161,0.04),transparent_60%)] pointer-events-none" />
      </div>

      <div className="max-w-6xl mx-auto px-6">
        <m.div
          className="text-center mb-16 md:mb-20"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <p className="text-xs font-mono tracking-[0.3em] uppercase text-[#00bcd4]/50 mb-4">
            The System
          </p>
          <h2 className="text-3xl md:text-5xl lg:text-6xl font-display font-bold tracking-tight">
            Three pillars of a{" "}
            <span className="text-gradient-cosmic">creative philosophy</span>
          </h2>
        </m.div>

        <div className="grid md:grid-cols-2 gap-4 md:gap-5">
          {/* Guardians — large hero card */}
          <m.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            <Link href="/luminors" className="group block h-full">
              <GlowCard
                glass="none"
                glowColor="rgba(0, 188, 212, 0.14)"
                glowSize={500}
                className="h-full border border-white/[0.08] hover:border-[#00bcd4]/30 transition-all duration-500 overflow-hidden relative min-h-[420px]"
              >
                <div className="absolute inset-0 grid grid-cols-3 grid-rows-3 opacity-30 group-hover:opacity-50 transition-opacity duration-700">
                  {ALL_GUARDIANS.slice(0, 9).map((g) => (
                    <div key={g.name} className="relative overflow-hidden">
                      <Image
                        src={g.image}
                        alt={`${g.name} — ${g.gate} Gate Guardian`}
                        fill
                        loading="lazy"
                        className="object-cover group-hover:scale-105 transition-transform duration-1000"
                        sizes="200px"
                      />
                    </div>
                  ))}
                </div>
                <div className="absolute inset-0 bg-gradient-to-t from-cosmic-deep via-cosmic-deep/60 to-cosmic-deep/25" />
                {/* Iridescent shimmer overlay */}
                <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-700 bg-[linear-gradient(135deg,rgba(0,188,212,0.05)_0%,rgba(13,71,161,0.05)_50%,rgba(0,137,123,0.03)_100%)]" />
                <div className="relative h-full flex flex-col justify-end p-8 md:p-10 min-h-[420px]">
                  <p className="text-xs font-mono text-[#00bcd4]/80 tracking-wider uppercase mb-3">
                    16 Luminors
                  </p>
                  <h3 className="text-2xl md:text-3xl font-display font-bold mb-3 text-white">
                    Companions
                  </h3>
                  <p className="text-white/55 text-sm leading-relaxed max-w-sm mb-6 font-body">
                    Sixteen specialized AI intelligences across four teams, each
                    trained on proprietary creative philosophy. Find the mind that thinks like you.
                  </p>
                  <span className="inline-flex items-center gap-2 text-sm text-[#00bcd4]/70 group-hover:text-[#00bcd4] group-hover:gap-3 transition-all font-medium">
                    Meet them <ArrowRight className="w-4 h-4" />
                  </span>
                </div>
              </GlowCard>
            </Link>
          </m.div>

          {/* Right column: Library + Academy stacked */}
          <div className="flex flex-col gap-4 md:gap-5">
            <m.div
              initial={{ opacity: 0, y: 30 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="flex-1"
            >
              <Link href="/library" className="group block h-full">
                <GlowCard
                  glass="liquid-glass-elevated"
                  glowColor="rgba(255, 215, 0, 0.12)"
                  className="p-8 md:p-10 h-full relative overflow-hidden border border-white/[0.08] hover:border-gold-bright/25 transition-all duration-500"
                >
                  {/* Crystal texture background */}
                  <Image
                    src={crystalImage}
                    alt="Crystal texture background"
                    fill
                    loading="lazy"
                    className="object-cover opacity-[0.06] mix-blend-luminosity pointer-events-none"
                    sizes="400px"
                  />
                  <div
                    className="absolute -top-24 -right-24 w-72 h-72 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none"
                    style={{
                      background:
                        "radial-gradient(circle, rgba(255,215,0,0.12), transparent 70%)",
                    }}
                  />
                  <div className="relative">
                    <p className="text-xs font-mono text-gold-bright/70 tracking-wider uppercase mb-3">
                      {collectionsCount} Collections &middot; {textsCount} Texts
                    </p>
                    <h3 className="text-xl md:text-2xl font-display font-bold mb-3">
                      Intelligence Library
                    </h3>
                    <p className="text-white/50 text-sm leading-relaxed max-w-sm mb-5 font-body">
                      {totalWords.toLocaleString()} words of proprietary creative
                      intelligence — the knowledge foundation that trains every
                      AI in the system.
                    </p>
                    <span className="inline-flex items-center gap-2 text-sm text-gold-bright/60 group-hover:text-gold-bright group-hover:gap-3 transition-all font-medium">
                      Read <ArrowRight className="w-4 h-4" />
                    </span>
                  </div>
                </GlowCard>
              </Link>
            </m.div>

            <m.div
              initial={{ opacity: 0, y: 30 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="flex-1"
            >
              <Link href="/academy" className="group block h-full">
                <GlowCard
                  glass="liquid-glass-elevated"
                  glowColor="rgba(13, 71, 161, 0.12)"
                  className="p-8 md:p-10 h-full relative overflow-hidden border border-white/[0.08] hover:border-creation-prism-purple/25 transition-all duration-500"
                >
                  <div
                    className="absolute -top-24 -right-24 w-72 h-72 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none"
                    style={{
                      background:
                        "radial-gradient(circle, rgba(13,71,161,0.10), transparent 70%)",
                    }}
                  />
                  <div className="relative">
                    <p className="text-xs font-mono text-creation-prism-purple/70 tracking-wider uppercase mb-3">
                      Ten Gates of Mastery
                    </p>
                    <h3 className="text-xl md:text-2xl font-display font-bold mb-3">
                      Training Academy
                    </h3>
                    <p className="text-white/50 text-sm leading-relaxed max-w-sm mb-5 font-body">
                      10 progressive mastery gates with specialized AI training
                      at each level. Growth earned through creation.
                    </p>
                    <span className="inline-flex items-center gap-2 text-sm text-creation-prism-purple/60 group-hover:text-creation-prism-purple group-hover:gap-3 transition-all font-medium">
                      Begin <ArrowRight className="w-4 h-4" />
                    </span>
                  </div>
                </GlowCard>
              </Link>
            </m.div>
          </div>
        </div>
      </div>
    </section>
  );
}

function PathwaysGrid() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section ref={ref} className="py-24 md:py-32 relative overflow-hidden">
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[900px] h-[420px] bg-[radial-gradient(ellipse,rgba(0,188,212,0.05),transparent_60%)] pointer-events-none" />
      </div>

      <div className="max-w-6xl mx-auto px-6">
        <m.div
          className="text-center mb-12 md:mb-16"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <p className="text-xs font-mono tracking-[0.3em] uppercase text-white/32 mb-4">
            What You Can Build
          </p>
          <h2 className="text-3xl md:text-5xl font-display font-bold tracking-tight mb-5">
            Build an ecosystem,{" "}
            <span className="text-gradient-cosmic">not a landing page</span>
          </h2>
        </m.div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">
          {PATHWAYS.map((path, i) => (
            <m.div
              key={path.title}
              initial={{ opacity: 0, y: 22 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: i * 0.06 }}
            >
              <Link href={path.href} className="group block h-full">
                <GlowCard
                  glass="none"
                  glowColor="rgba(0,188,212,0.14)"
                  className="h-full border border-white/[0.08] hover:border-[#00bcd4]/35 transition-all duration-500 overflow-hidden"
                >
                  <div className="relative h-full min-h-[220px]">
                    <Image
                      src={path.image}
                      alt={path.title}
                      fill
                      className="object-cover object-top group-hover:scale-[1.04] transition-transform duration-700"
                      sizes="(max-width: 1024px) 50vw, 33vw"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/55 to-black/10" />
                    <div className="absolute inset-0 p-5 md:p-6 flex flex-col justify-end">
                      <h3 className="text-lg md:text-xl font-display font-semibold text-white mb-2">
                        {path.title}
                      </h3>
                      <p className="text-sm text-white/60 leading-relaxed mb-4">
                        {path.description}
                      </p>
                      <span className="inline-flex items-center gap-2 text-sm text-[#00bcd4]/75 group-hover:text-[#00bcd4] transition-colors">
                        Start <ArrowRight className="w-4 h-4" />
                      </span>
                    </div>
                  </div>
                </GlowCard>
              </Link>
            </m.div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// SECTION 4: Features — Premium Iridescent Glass Cards
// ---------------------------------------------------------------------------

function FeaturesGrid() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section ref={ref} className="py-24 md:py-36 relative overflow-hidden">
      {/* Multi-layer atmospheric background */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-1/3 left-0 w-[500px] h-[500px] bg-[radial-gradient(circle,rgba(0,188,212,0.04),transparent_60%)] pointer-events-none" />
        <div className="absolute bottom-1/3 right-0 w-[500px] h-[500px] bg-[radial-gradient(circle,rgba(13,71,161,0.04),transparent_60%)] pointer-events-none" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[400px] bg-[radial-gradient(ellipse,rgba(255,215,0,0.02),transparent_50%)] pointer-events-none" />
      </div>

      <div className="max-w-6xl mx-auto px-6">
        <m.div
          className="text-center mb-16 md:mb-20"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <p className="text-xs font-mono tracking-[0.3em] uppercase text-creation-prism-purple/50 mb-4">
            Explore
          </p>
          <h2 className="text-3xl md:text-5xl lg:text-6xl font-display font-bold tracking-tight mb-5">
            A universe, <span className="text-gradient-brand">not a tool</span>
          </h2>
          <p className="text-white/40 max-w-2xl mx-auto text-lg font-body">
            Every piece is original. Every feature connects to the mythology.
            Nothing is filler.
          </p>
        </m.div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">
          {FEATURES.map((f, i) => {
            const Icon = f.icon;
            return (
              <m.div
                key={f.title}
                initial={{ opacity: 0, y: 24 }}
                animate={isInView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.5, delay: i * 0.08 }}
              >
                <Link href={f.href} className="group block h-full">
                  <GlowCard
                    glass="iridescent-glass"
                    glowColor={f.glowColor}
                    glowSize={350}
                    className="p-7 h-full border border-white/[0.08] hover:border-white/[0.16] transition-all duration-500"
                  >
                    {/* Icon with gradient background */}
                    <div
                      className="w-12 h-12 rounded-xl flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-300"
                      style={{
                        background: `linear-gradient(135deg, ${f.accentHex}20, ${f.accentHex}08)`,
                        border: `1px solid ${f.accentHex}25`,
                      }}
                    >
                      <Icon
                        className="w-5 h-5"
                        style={{ color: f.accentHex }}
                      />
                    </div>
                    <h3 className="text-lg font-display font-bold mb-2 text-white group-hover:text-white transition-colors">
                      {f.title}
                    </h3>
                    <p className="text-sm text-white/40 leading-relaxed group-hover:text-white/55 transition-colors font-body">
                      {f.description}
                    </p>
                    <div
                      className="mt-5 inline-flex items-center gap-1.5 text-xs font-medium transition-all group-hover:gap-2.5"
                      style={{ color: `${f.accentHex}80` }}
                    >
                      Explore <ArrowRight className="w-3 h-3" />
                    </div>
                  </GlowCard>
                </Link>
              </m.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// CreatorVoices removed — will add back when we have real testimonials

// ---------------------------------------------------------------------------
// SECTION 4b: Gallery Showcase — Cinematic Image Strip
// ---------------------------------------------------------------------------

const GALLERY_IMAGES = [
  { src: "/guardians/v3/lyria-hero-v3.webp", name: "Lyria", caption: "The Sight Gate" },
  { src: "/guardians/v3/draconia-hero-v3.webp", name: "Draconia", caption: "The Fire Gate" },
  { src: "/guardians/v3/aiyami-hero-v3.webp", name: "Aiyami", caption: "The Crown Gate" },
  { src: "/guardians/v3/elara-hero-v3.webp", name: "Elara", caption: "The Starweave Gate" },
  { src: "/guardians/v3/shinkami-hero-v3.webp", name: "Shinkami", caption: "The Source Gate" },
  { src: "/guardians/v3/alera-hero-v3.webp", name: "Alera", caption: "The Voice Gate" },
  { src: "/guardians/v3/ino-hero-v3.webp", name: "Ino", caption: "The Unity Gate" },
  { src: "/guardians/v3/leyla-hero-v3.webp", name: "Leyla", caption: "The Flow Gate" },
];

function GalleryShowcase() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section ref={ref} className="py-20 md:py-28 relative overflow-hidden">
      {/* Atmospheric background */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[1000px] h-[500px] bg-[radial-gradient(ellipse,rgba(13,71,161,0.05),transparent_60%)] pointer-events-none" />
      </div>

      <div className="max-w-7xl mx-auto px-6">
        <m.div
          className="flex items-end justify-between mb-10"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <div>
            <p className="text-xs font-mono tracking-[0.3em] uppercase text-draconic-crimson/40 mb-3">
              Guardians + Luminor Agents
            </p>
            <h2 className="text-2xl md:text-4xl font-display font-bold">
              The <span className="text-gradient-brand">Gallery</span>
            </h2>
          </div>
          <Link
            href="/gallery"
            className="hidden md:inline-flex items-center gap-2 text-sm text-white/40 hover:text-[#00bcd4] transition-colors"
          >
            View all <ArrowUpRight className="w-3.5 h-3.5" />
          </Link>
        </m.div>
      </div>

      {/* Full-bleed horizontal scroll */}
      <m.div
        initial={{ opacity: 0 }}
        animate={isInView ? { opacity: 1 } : {}}
        transition={{ duration: 0.8, delay: 0.2 }}
        className="relative"
      >
        <div className="flex gap-4 overflow-x-auto scrollbar-hide px-6 pb-4 snap-x snap-mandatory">
          {GALLERY_IMAGES.map((img, i) => (
            <m.div
              key={img.name}
              className="group flex-shrink-0 snap-center"
              initial={{ opacity: 0, x: 40 }}
              animate={isInView ? { opacity: 1, x: 0 } : {}}
              transition={{ duration: 0.5, delay: 0.1 + i * 0.06 }}
            >
              <Link href="/gallery" className="block relative">
                <div className="relative w-[260px] md:w-[320px] aspect-[3/4] rounded-2xl overflow-hidden border border-white/[0.08] hover:border-white/[0.18] transition-all duration-500">
                  <Image
                    src={img.src}
                    alt={img.name}
                    fill
                    className="object-cover object-[center_40%] group-hover:scale-[1.06] transition-transform duration-700"
                    sizes="320px"
                  />
                  {/* Top gradient to mask infographic labels */}
                  <div className="absolute inset-0 bg-gradient-to-b from-black/50 via-transparent to-transparent z-[1]" />
                  {/* Gradient overlay */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent z-[1]" />
                  {/* Iridescent edge on hover */}
                  <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 bg-[linear-gradient(135deg,rgba(0,188,212,0.06)_0%,transparent_40%,transparent_60%,rgba(13,71,161,0.06)_100%)]" />
                  {/* Caption */}
                  <div className="absolute bottom-0 left-0 right-0 p-4">
                    <p className="text-sm font-display font-bold">{img.name}</p>
                    <p className="text-[11px] text-white/40 font-mono">
                      {img.caption}
                    </p>
                  </div>
                </div>
              </Link>
            </m.div>
          ))}
        </div>

        {/* Fade edges */}
        <div className="absolute top-0 left-0 bottom-4 w-12 bg-gradient-to-r from-cosmic-deep to-transparent pointer-events-none z-10" />
        <div className="absolute top-0 right-0 bottom-4 w-12 bg-gradient-to-l from-cosmic-deep to-transparent pointer-events-none z-10" />
      </m.div>

      {/* Mobile link */}
      <div className="mt-6 px-6 md:hidden">
        <Link
          href="/gallery"
          className="inline-flex items-center gap-2 text-sm text-[#00bcd4]/70"
        >
          Explore the full Gallery <ArrowRight className="w-4 h-4" />
        </Link>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// SECTION 5: Guardian Showcase — Cinematic Cards with Iridescent Borders
// ---------------------------------------------------------------------------

function GuardianShowcase() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section ref={ref} className="py-24 md:py-36 relative overflow-hidden">
      {/* Cinematic atmosphere */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[600px] bg-[radial-gradient(ellipse,rgba(0,188,212,0.05),transparent_55%)] pointer-events-none" />
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            background: "radial-gradient(ellipse 60% 40% at 50% 50%, rgba(13,71,161,0.05) 0%, transparent 60%)",
          }}
        />
      </div>

      <div className="max-w-6xl mx-auto px-6">
        <m.div
          className="flex items-end justify-between mb-14"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <div>
            <p className="text-xs font-mono tracking-[0.3em] uppercase text-white/30 mb-4">
              Featured
            </p>
            <h2 className="text-3xl md:text-5xl font-display font-bold tracking-tight">
              Meet the <span className="text-gradient-crystal">Guardians</span>
            </h2>
          </div>
          <Link
            href="/lore/guardians"
            className="hidden md:inline-flex items-center gap-2 text-sm text-white/40 hover:text-[#00bcd4] transition-colors"
          >
            View all ten <ArrowUpRight className="w-3.5 h-3.5" />
          </Link>
        </m.div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-5">
          {FEATURED_GUARDIANS.map((g, i) => (
            <m.div
              key={g.name}
              className="group"
              initial={{ opacity: 0, y: 30 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: i * 0.08 }}
            >
              <GlowCard
                glass="none"
                glowColor={g.glowColor}
                glowSize={320}
                className="card-3d border border-white/[0.08] hover:border-white/[0.20] transition-all duration-500"
              >
                <div className="relative aspect-[3/4] overflow-hidden rounded-2xl">
                  <Image
                    src={g.image}
                    alt={g.name}
                    fill
                    className="object-cover object-[center_40%] group-hover:scale-[1.05] transition-transform duration-700"
                    sizes="(max-width: 640px) 50vw, 33vw"
                  />
                  {/* Top gradient to mask infographic labels */}
                  <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-transparent z-[1]" />
                  {/* Multi-gradient overlay for depth */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/95 via-black/40 to-transparent z-[1]" />
                  {/* Accent color wash on hover */}
                  <div
                    className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500"
                    style={{
                      background: `linear-gradient(to top, ${g.accentHex}20, transparent 60%)`,
                    }}
                  />
                  {/* Iridescent shimmer on hover */}
                  <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-700 bg-[linear-gradient(135deg,rgba(0,188,212,0.04)_0%,rgba(13,71,161,0.04)_50%,rgba(0,137,123,0.02)_100%)]" />
                  {/* Content */}
                  <div className="absolute bottom-0 left-0 right-0 p-5 md:p-6">
                    <p
                      className="text-[10px] font-mono tracking-wider uppercase mb-1.5"
                      style={{ color: `${g.accentHex}99` }}
                    >
                      {g.gate} Gate &middot; {g.element}
                    </p>
                    <h3 className="text-lg md:text-xl font-display font-bold mb-2">
                      {g.name}
                    </h3>
                    <p className="text-xs text-white/40 leading-relaxed line-clamp-2 group-hover:text-white/65 transition-colors duration-300 font-body italic">
                      &ldquo;{g.quote}&rdquo;
                    </p>
                  </div>
                </div>
              </GlowCard>
            </m.div>
          ))}
        </div>

        {/* Mobile link */}
        <div className="mt-8 md:hidden">
          <Link
            href="/lore/guardians"
            className="inline-flex items-center gap-2 text-sm text-[#00bcd4]/70"
          >
            View all Guardians <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

        {/* Desktop portrait strip */}
        <m.div
          className="hidden md:flex items-center justify-center gap-2.5 mt-14"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
          transition={{ delay: 0.8 }}
        >
          {ALL_GUARDIANS.map((g) => (
            <Link
              key={g.name}
              href="/lore/guardians"
              title={`${g.name} — ${g.gate} Gate`}
            >
              <div className="relative w-9 h-9 rounded-lg overflow-hidden border border-white/[0.08] hover:border-[#00bcd4]/40 hover:scale-125 hover:shadow-[0_0_16px_rgba(0,188,212,0.15)] transition-all duration-300">
                <Image
                  src={g.image}
                  alt={g.name}
                  fill
                  className="object-cover"
                  sizes="36px"
                />
              </div>
            </Link>
          ))}
          <span className="text-[10px] text-white/25 ml-3 font-mono tracking-wider">
            10 gates
          </span>
        </m.div>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// SECTION 7: Library Quote — Gradient Border Treatment
// ---------------------------------------------------------------------------

function LibraryQuote({
  collectionsCount,
  textsCount,
  totalWords,
}: {
  collectionsCount: number;
  textsCount: number;
  totalWords: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section ref={ref} className="py-24 md:py-36 relative">
      {/* Ambient glow */}
      <div
        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] pointer-events-none -z-10"
        style={{
          background:
            "radial-gradient(ellipse, rgba(13,71,161,0.06), transparent 60%)",
        }}
      />

      <div className="max-w-3xl mx-auto px-6">
        <m.div
          className="relative"
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8 }}
        >
          {/* Gradient border wrapper */}
          <div className="gradient-border">
            <GlowCard
              glass="liquid-glass-elevated"
              glowColor="rgba(13, 71, 161, 0.08)"
              glowSize={500}
              lift={false}
              className="rounded-[calc(1.5rem-1px)]"
            >
              <div className="p-8 md:p-12 lg:p-16">
                <div className="flex items-center gap-3 mb-8">
                  <Quotes className="w-6 h-6 text-creation-prism-purple/30" />
                  <div className="w-12 h-[2px] bg-gradient-to-r from-[#00bcd4] via-[#1a237e] to-[#00897b] rounded-full" />
                </div>

                <blockquote className="text-lg md:text-xl lg:text-2xl text-white/75 leading-relaxed font-display italic space-y-4">
                  <p>
                    &ldquo;Before the first word, there was silence. Before the
                    first creation, there was intention.
                  </p>
                  <p>
                    This is the First Law: What you contemplate at dawn shapes
                    all that follows. The creative life does not begin with
                    inspiration — it begins with the decision to create.&rdquo;
                  </p>
                </blockquote>

                <div className="flex items-center justify-between mt-8 pt-6 border-t border-white/[0.06]">
                  <p className="text-sm text-white/30 font-body italic">
                    The Laws of Arcanea, I. The Law of First Light
                  </p>
                  <Link
                    href="/library"
                    className="inline-flex items-center gap-2 text-sm text-white/40 hover:text-[#00bcd4] transition-colors"
                  >
                    Read more <ArrowRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </div>
            </GlowCard>
          </div>

          <p className="text-center mt-8 text-xs text-white/20 font-mono tracking-wider">
            {collectionsCount} collections &middot; {textsCount} texts &middot;{" "}
            {totalWords.toLocaleString()} words
          </p>
        </m.div>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// SECTION 8: Philosophy — What Arcanea Believes
// ---------------------------------------------------------------------------

function PhilosophySection() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  const principles = [
    {
      title: "Creation first",
      text: "Every feature exists to help you make something. We do not gamify attention — we serve the creative act.",
      accentHex: "#00bcd4",
    },
    {
      title: "Intelligence with personality",
      text: "Not generic chatbots. Each companion has a philosophy, voice, and domain. Choose the one that sees your challenge clearly.",
      accentHex: "#0d47a1",
    },
    {
      title: "Mythology as framework",
      text: "The lore is not decoration. It is a developmental system — a language for the stages of creative growth that every maker passes through.",
      accentHex: "#ffd700",
    },
    {
      title: "Depth you earn",
      text: "The surface is simple. The deeper you go, the more the system reveals. Frequencies, Gates, Elements, Ranks — discovered, never forced.",
      accentHex: "#00897b",
    },
  ];

  return (
    <section ref={ref} className="py-24 md:py-36 relative">
      {/* Atmospheric */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-0 right-1/4 w-[600px] h-[400px] bg-[radial-gradient(ellipse,rgba(13,71,161,0.04),transparent_60%)] pointer-events-none" />
        <div className="absolute bottom-0 left-1/4 w-[500px] h-[400px] bg-[radial-gradient(ellipse,rgba(0,188,212,0.03),transparent_60%)] pointer-events-none" />
      </div>

      <div className="max-w-5xl mx-auto px-6">
        <m.div
          className="text-center mb-16 md:mb-20"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <p className="text-xs font-mono tracking-[0.3em] uppercase text-gold-bright/40 mb-4">
            Philosophy
          </p>
          <h2 className="text-3xl md:text-5xl lg:text-6xl font-display font-bold tracking-tight mb-4">
            What we <span className="text-gradient-gold">believe</span>
          </h2>
        </m.div>

        <div className="grid md:grid-cols-2 gap-4 md:gap-5">
          {principles.map((p, i) => (
            <m.div
              key={p.title}
              initial={{ opacity: 0, y: 20 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: i * 0.1 }}
            >
              <GlowCard
                glass="liquid-glass"
                glowColor={`${p.accentHex}10`}
                lift={false}
                className="p-7 h-full border border-white/[0.08] hover:border-white/[0.14] transition-all duration-500"
              >
                <div
                  className="w-8 h-[3px] rounded-full mb-5"
                  style={{
                    background: `linear-gradient(90deg, ${p.accentHex}, transparent)`,
                  }}
                />
                <h3
                  className="text-lg font-display font-bold mb-3"
                  style={{ color: `${p.accentHex}dd` }}
                >
                  {p.title}
                </h3>
                <p className="text-sm text-white/45 leading-relaxed font-body">
                  {p.text}
                </p>
              </GlowCard>
            </m.div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// SECTION 9: FAQ — Clean, Premium Accordion
// ---------------------------------------------------------------------------

function FAQItem({
  item,
  index,
}: {
  item: (typeof FAQ_ITEMS)[0];
  index: number;
}) {
  const [open, setOpen] = useState(false);

  return (
    <m.div
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-60px" }}
      transition={{ duration: 0.4, delay: index * 0.06 }}
    >
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="w-full text-left py-6 flex items-start justify-between gap-4 border-b border-white/[0.06] group cursor-pointer"
      >
        <span className="text-base font-medium text-white/80 group-hover:text-white transition-colors leading-snug">
          {item.q}
        </span>
        <span className="flex-shrink-0 mt-0.5 w-6 h-6 rounded-full border border-white/[0.10] flex items-center justify-center group-hover:border-white/[0.20] transition-colors">
          {open ? (
            <Minus className="w-3 h-3 text-white/40" />
          ) : (
            <Plus className="w-3 h-3 text-white/40" />
          )}
        </span>
      </button>
      <m.div
        initial={false}
        animate={{
          height: open ? "auto" : 0,
          opacity: open ? 1 : 0,
        }}
        transition={{ duration: 0.3, ease: "easeInOut" }}
        className="overflow-hidden"
      >
        <p className="py-5 text-sm text-white/45 leading-relaxed max-w-2xl font-body">
          {item.a}
        </p>
      </m.div>
    </m.div>
  );
}

function FAQInline() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section ref={ref} className="py-24 md:py-32">
      <div className="max-w-3xl mx-auto px-6">
        <m.div
          className="text-center mb-14"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <p className="text-xs font-mono tracking-[0.3em] uppercase text-white/30 mb-4">
            Questions
          </p>
          <h2 className="text-3xl md:text-4xl font-display font-bold tracking-tight">
            Frequently asked
          </h2>
        </m.div>

        <div>
          {FAQ_ITEMS.map((item, i) => (
            <FAQItem key={item.q} item={item} index={i} />
          ))}
        </div>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// SECTION 4c: Companion Showcase — 6 AI-generated companion portraits
// ---------------------------------------------------------------------------

const ELEMENT_COLORS: Record<string, { accent: string; glow: string }> = {
  Fire: { accent: "#ef4444", glow: "rgba(239, 68, 68, 0.25)" },
  Water: { accent: "#3b82f6", glow: "rgba(59, 130, 246, 0.25)" },
  Earth: { accent: "#22c55e", glow: "rgba(34, 197, 94, 0.25)" },
  Wind: { accent: "#a78bfa", glow: "rgba(167, 139, 250, 0.25)" },
  Void: { accent: "#8b5cf6", glow: "rgba(139, 92, 246, 0.25)" },
  Spirit: { accent: "#ffd700", glow: "rgba(255, 215, 0, 0.25)" },
};

function CompanionShowcase() {
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });
  const companions = getFeaturedLuminors(6);

  return (
    <section ref={ref} className="py-24 md:py-36 relative overflow-hidden">
      {/* Atmospheric background */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-1/4 left-1/3 w-[600px] h-[400px] bg-[radial-gradient(ellipse,rgba(0,188,212,0.04),transparent_60%)] pointer-events-none" />
        <div className="absolute bottom-1/4 right-1/3 w-[500px] h-[400px] bg-[radial-gradient(ellipse,rgba(255,215,0,0.03),transparent_60%)] pointer-events-none" />
      </div>

      <div className="max-w-6xl mx-auto px-6">
        <m.div
          className="text-center mb-14 md:mb-20"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <p className="text-xs font-mono tracking-[0.3em] uppercase text-[#00bcd4]/50 mb-4">
            20 Spirits
          </p>
          <h2 className="text-3xl md:text-5xl lg:text-6xl font-display font-bold tracking-tight mb-5">
            Creative{" "}
            <span className="text-gradient-cosmic">Companions</span>
          </h2>
          <p className="text-white/40 max-w-2xl mx-auto text-lg font-body">
            Twenty AI-generated spirits — each aligned to an element and a Gate.
            Portraits of the creative forces that walk beside you.
          </p>
        </m.div>

        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-4 md:gap-5">
          {companions.map((c, i) => {
            const colors = ELEMENT_COLORS[c.element] ?? ELEMENT_COLORS.Spirit;
            return (
              <m.div
                key={c.id}
                initial={{ opacity: 0, y: 24 }}
                animate={isInView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.5, delay: i * 0.08 }}
              >
                <Link
                  href={`/gallery/luminors`}
                  className="group block"
                >
                  <div className="relative aspect-square rounded-2xl overflow-hidden border border-white/[0.06] hover:border-white/[0.16] transition-all duration-500">
                    <Image
                      src={c.image}
                      alt={`${c.name} — ${c.title}`}
                      fill
                      className="object-cover group-hover:scale-105 transition-transform duration-700"
                      sizes="(max-width: 640px) 50vw, (max-width: 768px) 33vw, 16vw"
                    />
                    {/* Gradient overlay */}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
                    {/* Hover glow */}
                    <div
                      className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none"
                      style={{
                        background: `radial-gradient(circle at 50% 80%, ${colors.glow}, transparent 70%)`,
                      }}
                    />
                    {/* Text overlay */}
                    <div className="absolute bottom-0 left-0 right-0 p-3">
                      <p className="text-sm font-display font-bold text-white truncate">
                        {c.name}
                      </p>
                      <p className="text-[11px] text-white/50 truncate">
                        {c.title}
                      </p>
                      <p
                        className="text-[10px] font-mono mt-1 uppercase tracking-wider"
                        style={{ color: colors.accent }}
                      >
                        {c.element}
                      </p>
                    </div>
                  </div>
                </Link>
              </m.div>
            );
          })}
        </div>

        {/* View all link */}
        <m.div
          className="text-center mt-10"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
          transition={{ duration: 0.5, delay: 0.6 }}
        >
          <Link
            href="/gallery/luminors"
            className="inline-flex items-center gap-2 text-sm text-[#00bcd4]/70 hover:text-[#00bcd4] hover:gap-3 transition-all font-medium"
          >
            View all 20 <ArrowRight className="w-4 h-4" />
          </Link>
        </m.div>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Exported below-fold composition
// ---------------------------------------------------------------------------

export interface V3BelowFoldProps {
  collectionsCount: number;
  textsCount: number;
  totalWords: number;
}

export function V3BelowFold({
  collectionsCount,
  textsCount,
  totalWords,
}: V3BelowFoldProps) {
  return (
    <MotionProvider>
      <>
        {/* 1. Guardian showcase — visual proof */}
        <GuardianShowcase />

        <AtmosphericDivider variant="teal" />

        {/* 2. How it works — 4 clear steps */}
        <HowItWorks />

        <AtmosphericDivider variant="gold" />

        {/* 3. Product hierarchy — explicit staging */}
        <ThreeLayersSection />

        {/* 4. FAQ — objection handling */}
        <FAQInline />

        {/* 4. Built With — tech trust strip */}
        <section className="py-12 md:py-16">
          <div className="max-w-4xl mx-auto px-6">
            <p className="text-[10px] font-mono tracking-[0.3em] uppercase text-white/20 text-center mb-5">
              Built With
            </p>
            <div className="flex flex-wrap justify-center gap-x-6 gap-y-3 text-xs font-mono text-white/25">
              <span>Next.js 16</span>
              <span className="text-white/10">·</span>
              <span>React 19</span>
              <span className="text-white/10">·</span>
              <span>Supabase</span>
              <span className="text-white/10">·</span>
              <span>Vercel</span>
              <span className="text-white/10">·</span>
              <span>Claude</span>
              <span className="text-white/10">·</span>
              <span>Gemini</span>
            </div>
          </div>
        </section>

        {/* 5. Living Lore — interactive narrative CTA */}
        <section className="py-12 md:py-16">
          <div className="max-w-4xl mx-auto px-6">
            <LivingLoreCTA />
          </div>
        </section>

        <AtmosphericDivider variant="purple" />

        {/* 6. Final CTA */}
        <CTASection />
      </>
    </MotionProvider>
  );
}
