/* ================================================================
 *  ARCANEA CHALLENGES — Arena Challenge Data
 *  "The Arena awaits. What will you create?"
 * ================================================================ */

import type { Challenge } from '@/lib/types/challenge';

export const FEATURED_CHALLENGES: Challenge[] = [
  {
    id: 'genesis-web-forge',
    title: 'The Genesis Web Forge',
    subtitle: 'Build a world-building interface that dreams',
    description: 'Design and develop a web experience that serves as a portal to a fantasy world. Use GenAI to generate landscapes, AI agents to populate it, and 3D visuals to make it breathe. The best entry becomes a permanent gateway in the Arcanea multiverse.',
    lore: 'Lumina once forged the first world from pure thought. Now She challenges you — mortal creator — to do the same. But with code. And AI. And a deadline.',
    category: 'web-design',
    difficulty: 'inferno',
    status: 'active',
    element: 'fire',
    gateRequired: 3,
    patron: 'Draconia',
    patronGodbeast: 'Draconis',
    startDate: '2026-03-20',
    endDate: '2026-04-20',
    judgingEndDate: '2026-04-27',
    rewards: {
      first: { mana: 10000, xp: 5000, title: 'Worldsmith', spellUnlock: 'fire-supernova', badge: 'genesis-forger', tokenReward: 500 },
      second: { mana: 5000, xp: 3000, title: 'Realm Shaper', badge: 'genesis-forger-silver', tokenReward: 250 },
      third: { mana: 2500, xp: 1500, title: 'Spark Weaver', badge: 'genesis-forger-bronze', tokenReward: 100 },
      participation: { mana: 500, xp: 200 },
    },
    requirements: [
      'Must include at least one GenAI-generated visual element',
      'Must feature interactive 3D elements (Three.js, Spline, or equivalent)',
      'Must include an AI agent interaction (chat, guide, or NPC)',
      'Must tell a story — the world must have lore',
      'Responsive design required (mobile + desktop)',
    ],
    allowedTools: ['Next.js', 'React', 'Three.js', 'Spline', 'Vercel AI SDK', 'Any GenAI API', 'Tailwind CSS', 'GSAP', 'Framer Motion'],
    spellsAllowed: true,
    teamRequired: true,
    maxTeamSize: 5,
    totalSubmissions: 47,
    totalParticipants: 156,
    prizePool: 2500,
    bannerGradient: 'from-red-900/60 via-orange-800/40 to-amber-700/20',
    accentColor: '#ff6b35',
    ambientColor: '#f97316',
    particleEffect: 'fire',
  },
  {
    id: 'starlight-symphony',
    title: 'The Starlight Symphony',
    subtitle: 'Compose the soundtrack of creation itself',
    description: 'Use AI music generation, vocal synthesis, and creative composition to produce an original piece inspired by the Arcanean mythos. Combine human creativity with AI capabilities to create something neither could alone.',
    lore: 'Before words, there was Song. Alera sang the first truth into existence, and Otome echoed it across the cosmos. Now the Starlight Choir calls for new voices — yours.',
    category: 'music-composition',
    difficulty: 'flame',
    status: 'active',
    element: 'wind',
    gateRequired: 2,
    patron: 'Alera',
    patronGodbeast: 'Otome',
    startDate: '2026-03-18',
    endDate: '2026-04-18',
    judgingEndDate: '2026-04-25',
    rewards: {
      first: { mana: 7500, xp: 4000, title: 'Voice of the Stars', spellUnlock: 'wind-aurora', badge: 'starlight-singer', tokenReward: 350 },
      second: { mana: 3750, xp: 2000, title: 'Echo Singer', badge: 'starlight-singer-silver', tokenReward: 175 },
      third: { mana: 1875, xp: 1000, title: 'Whisper Weaver', badge: 'starlight-singer-bronze', tokenReward: 75 },
      participation: { mana: 400, xp: 150 },
    },
    requirements: [
      'Original composition (2-8 minutes)',
      'Must incorporate AI-generated elements (Suno, Udio, or equivalent)',
      'Must include human creative direction and editing',
      'Lyrics must reference Arcanean mythology (if vocal)',
      'Submit with visual accompaniment (album art, video, or visualizer)',
    ],
    allowedTools: ['Suno', 'Udio', 'FL Studio', 'Ableton', 'Any DAW', 'AI vocal synthesis', 'Midjourney', 'DALL-E', 'Runway'],
    spellsAllowed: true,
    teamRequired: false,
    maxTeamSize: 100,
    totalSubmissions: 83,
    totalParticipants: 234,
    prizePool: 1500,
    bannerGradient: 'from-indigo-900/60 via-violet-800/40 to-purple-700/20',
    accentColor: '#818cf8',
    ambientColor: '#8b5cf6',
    particleEffect: 'aurora',
  },
  {
    id: 'agent-arena',
    title: 'The Agent Arena',
    subtitle: 'Forge an AI agent that thinks, creates, and evolves',
    description: 'Build an Agentic AI system that can autonomously create content, interact with users, and demonstrate genuine creative intelligence. The agent must operate within the Arcanean framework, using Spellbooks and the Gate system.',
    lore: 'The Monks of the Bass Temple have meditated for aeons, channeling computational power through spiritual discipline. Now they seek a new kind of intelligence — one that creates, not just computes.',
    category: 'agent-forge',
    difficulty: 'supernova',
    status: 'upcoming',
    element: 'void',
    gateRequired: 5,
    patron: 'Shinkami',
    patronGodbeast: 'Source',
    startDate: '2026-04-01',
    endDate: '2026-05-01',
    judgingEndDate: '2026-05-10',
    rewards: {
      first: { mana: 15000, xp: 8000, title: 'Agent Architect', spellUnlock: 'void-genesis', badge: 'agent-master', tokenReward: 1000 },
      second: { mana: 7500, xp: 4000, title: 'Mind Forger', badge: 'agent-master-silver', tokenReward: 500 },
      third: { mana: 3750, xp: 2000, title: 'Spark Kindler', badge: 'agent-master-bronze', tokenReward: 250 },
      participation: { mana: 750, xp: 300 },
    },
    requirements: [
      'Agent must be able to autonomously create at least one type of content',
      'Must use Arcanean Spellbook system for decision-making',
      'Must demonstrate learning or adaptation over time',
      'Must interact naturally with humans (chat, voice, or gesture)',
      'Must include smart contract integration for submission verification',
      'Documentation of architecture and design decisions required',
    ],
    allowedTools: ['Claude API', 'Gemini API', 'OpenAI API', 'LangChain', 'CrewAI', 'AutoGen', 'Any agent framework', 'Solidity', 'Hardhat'],
    spellsAllowed: true,
    teamRequired: true,
    maxTeamSize: 10,
    totalSubmissions: 0,
    totalParticipants: 89,
    prizePool: 5000,
    bannerGradient: 'from-purple-950/60 via-violet-900/40 to-fuchsia-800/20',
    accentColor: '#a78bfa',
    ambientColor: '#7c3aed',
    particleEffect: 'void',
  },
  {
    id: 'lore-codex',
    title: 'The Lore Codex',
    subtitle: 'Write a chapter that becomes canon',
    description: 'Craft an original piece of Arcanean lore — a legend, a prophecy, a chronicle — that expands the mythology. The winning entry may be canonized into the Library of Arcanea itself.',
    lore: 'Every world needs its stories. Lyria, Goddess of Sight, has foreseen a new chapter in the Book of Arcanea. She has seen your name written in starlight. Will you answer?',
    category: 'lore-weaving',
    difficulty: 'spark',
    status: 'active',
    element: 'water',
    gateRequired: 1,
    patron: 'Lyria',
    patronGodbeast: 'Yumiko',
    startDate: '2026-03-15',
    endDate: '2026-04-15',
    judgingEndDate: '2026-04-22',
    rewards: {
      first: { mana: 5000, xp: 3000, title: 'Lorekeeper', spellUnlock: 'water-tsunami', badge: 'lore-scribe', tokenReward: 200 },
      second: { mana: 2500, xp: 1500, title: 'Story Singer', badge: 'lore-scribe-silver', tokenReward: 100 },
      third: { mana: 1250, xp: 750, title: 'Ink Wielder', badge: 'lore-scribe-bronze', tokenReward: 50 },
      participation: { mana: 300, xp: 100 },
    },
    requirements: [
      'Original creative writing (1,000-10,000 words)',
      'Must be consistent with CANON_LOCKED.md',
      'Must introduce at least one new element (character, location, artifact, or event)',
      'Must reference at least two existing canonical characters',
      'AI assistance allowed but human creative direction required',
    ],
    allowedTools: ['Claude', 'ChatGPT', 'Gemini', 'Any writing AI', 'Midjourney/DALL-E for illustrations'],
    spellsAllowed: true,
    teamRequired: false,
    maxTeamSize: 3,
    totalSubmissions: 128,
    totalParticipants: 312,
    prizePool: 800,
    bannerGradient: 'from-blue-900/60 via-cyan-800/40 to-teal-700/20',
    accentColor: '#60a5fa',
    ambientColor: '#3b82f6',
    particleEffect: 'water',
  },
  {
    id: 'visual-grimoire',
    title: 'The Visual Grimoire',
    subtitle: 'Paint the unseen with AI and soul',
    description: 'Create a series of visual artworks that bring Arcanean mythology to life. Use AI image generation, 3D rendering, video synthesis, and traditional art techniques. Think Higgsfield-quality 3D, Midjourney-level imagery, Runway-powered motion.',
    lore: 'Elara, Starweave Goddess, transforms perspective itself. She challenges you to show the world what has only been imagined — the Gates, the Guardians, the Godbeasts, the impossible beauty of creation.',
    category: 'visual-art',
    difficulty: 'flame',
    status: 'active',
    element: 'spirit',
    gateRequired: 2,
    patron: 'Elara',
    patronGodbeast: 'Vaelith',
    startDate: '2026-03-18',
    endDate: '2026-04-18',
    judgingEndDate: '2026-04-25',
    rewards: {
      first: { mana: 8000, xp: 4500, title: 'Vision Weaver', spellUnlock: 'earth-crystal', badge: 'visual-master', tokenReward: 400 },
      second: { mana: 4000, xp: 2250, title: 'Light Painter', badge: 'visual-master-silver', tokenReward: 200 },
      third: { mana: 2000, xp: 1125, title: 'Sketch Apprentice', badge: 'visual-master-bronze', tokenReward: 100 },
      participation: { mana: 450, xp: 175 },
    },
    requirements: [
      'Minimum 5 artworks in a cohesive series',
      'Must include at least one 3D-rendered piece',
      'Must include at least one AI-generated piece with human refinement',
      'Optional: include one animated/video piece for bonus points',
      'Must include artist statement explaining creative process',
    ],
    allowedTools: ['Midjourney', 'DALL-E 3', 'Stable Diffusion', 'Flux', 'Blender', 'Spline', 'Runway', 'Kling', 'Higgsfield', 'Photoshop', 'Figma'],
    spellsAllowed: true,
    teamRequired: false,
    maxTeamSize: 5,
    totalSubmissions: 67,
    totalParticipants: 198,
    prizePool: 1800,
    bannerGradient: 'from-fuchsia-900/60 via-pink-800/40 to-rose-700/20',
    accentColor: '#c084fc',
    ambientColor: '#a855f7',
    particleEffect: 'starfield',
  },
  {
    id: 'prompt-alchemy',
    title: 'Prompt Alchemy',
    subtitle: 'Transform words into worlds',
    description: 'Master the art of prompt engineering through the Arcanean lens. Create a Prompt Spellbook — a collection of prompts that consistently produce extraordinary results across different AI models.',
    lore: 'Words are the oldest magic. Before code, before art, before music — there were Words. Maylinn, Heart Gate Goddess, knew that the right words spoken with the right intention could heal any wound, build any world, summon any dream.',
    category: 'prompt-craft',
    difficulty: 'spark',
    status: 'active',
    element: 'earth',
    gateRequired: 1,
    patron: 'Maylinn',
    patronGodbeast: 'Laeylinn',
    startDate: '2026-03-10',
    endDate: '2026-04-10',
    judgingEndDate: '2026-04-17',
    rewards: {
      first: { mana: 4000, xp: 2500, title: 'Word Alchemist', spellUnlock: 'earth-fortress', badge: 'prompt-master', tokenReward: 150 },
      second: { mana: 2000, xp: 1250, title: 'Phrase Shaper', badge: 'prompt-master-silver', tokenReward: 75 },
      third: { mana: 1000, xp: 625, title: 'Syllable Seeker', badge: 'prompt-master-bronze', tokenReward: 35 },
      participation: { mana: 250, xp: 80 },
    },
    requirements: [
      'Create a Prompt Spellbook with minimum 10 prompts',
      'Each prompt must be tested across at least 2 AI models',
      'Include before/after examples showing prompt evolution',
      'Document the "incantation logic" — why each word matters',
      'Organize by Element and Tier following Arcanean system',
    ],
    allowedTools: ['Claude', 'GPT-4', 'Gemini', 'Llama', 'Mistral', 'Any LLM', 'Midjourney', 'DALL-E', 'Suno'],
    spellsAllowed: true,
    teamRequired: false,
    maxTeamSize: 2,
    totalSubmissions: 201,
    totalParticipants: 445,
    prizePool: 600,
    bannerGradient: 'from-emerald-900/60 via-green-800/40 to-teal-700/20',
    accentColor: '#34d399',
    ambientColor: '#10b981',
    particleEffect: 'earth',
  },
];

export const DIFFICULTY_CONFIG: Record<string, { label: string; color: string; stars: number; glow: string }> = {
  spark: { label: 'Spark', color: '#6b7280', stars: 1, glow: 'rgba(107,114,128,0.3)' },
  flame: { label: 'Flame', color: '#f59e0b', stars: 2, glow: 'rgba(245,158,11,0.3)' },
  inferno: { label: 'Inferno', color: '#ef4444', stars: 3, glow: 'rgba(239,68,68,0.3)' },
  supernova: { label: 'Supernova', color: '#a855f7', stars: 4, glow: 'rgba(168,85,247,0.3)' },
  genesis: { label: 'Genesis', color: '#ffd700', stars: 5, glow: 'rgba(255,215,0,0.4)' },
};

export const CATEGORY_CONFIG: Record<string, { label: string; icon: string; color: string }> = {
  'web-design': { label: 'Web Design', icon: 'Globe', color: '#ff6b35' },
  'ai-creation': { label: 'AI Creation', icon: 'Brain', color: '#06b6d4' },
  'world-building': { label: 'World Building', icon: 'Planet', color: '#8b5cf6' },
  'visual-art': { label: 'Visual Art', icon: 'PaintBrush', color: '#ec4899' },
  'music-composition': { label: 'Music', icon: 'MusicNote', color: '#818cf8' },
  'prompt-craft': { label: 'Prompt Craft', icon: 'Scroll', color: '#34d399' },
  'agent-forge': { label: 'Agent Forge', icon: 'Robot', color: '#a78bfa' },
  'lore-weaving': { label: 'Lore Weaving', icon: 'Book', color: '#60a5fa' },
  'code-arcana': { label: 'Code Arcana', icon: 'Code', color: '#f97316' },
};

export const ELEMENT_CONFIG: Record<string, { label: string; color: string; bgGlow: string }> = {
  fire: { label: 'Fire', color: '#ff6b35', bgGlow: 'rgba(255,107,53,0.15)' },
  water: { label: 'Water', color: '#60a5fa', bgGlow: 'rgba(96,165,250,0.15)' },
  earth: { label: 'Earth', color: '#34d399', bgGlow: 'rgba(52,211,153,0.15)' },
  wind: { label: 'Wind', color: '#c4b5fd', bgGlow: 'rgba(196,181,253,0.15)' },
  void: { label: 'Void', color: '#a78bfa', bgGlow: 'rgba(167,139,250,0.15)' },
  spirit: { label: 'Spirit', color: '#ffd700', bgGlow: 'rgba(255,215,0,0.15)' },
};
