import type { AppTileProps } from "@/components/premium";

export type Category =
  | "All"
  | "Featured"
  | "Creative AI"
  | "Coding"
  | "Distribution"
  | "Community"
  | "Game Engines"
  | "Storage"
  | "Web3";

export interface AppEntry extends Omit<AppTileProps, "index"> {
  featured?: boolean;
  filterCategory: Category;
}

export const APPS: AppEntry[] = [
  // ── Coding ──────────────────────────────────────────────────────────────
  {
    name: "Claude Code",
    tagline: "Agents in your IDE via MCP. Luminor rules, hooks, and skills.",
    category: "Coding",
    filterCategory: "Coding",
    glyph: "✶",
    color: "#f97316",
    status: "live",
    installed: true,
    featured: true,
    capabilities: ["MCP Server", "Agent Hooks", "Skill Packs"],
    href: "/apps/claude-code",
  },
  {
    name: "VS Code",
    tagline: "Arcanea agents extension with in-editor Luminor sidebar.",
    category: "Coding",
    filterCategory: "Coding",
    glyph: "◧",
    color: "#007acc",
    status: "live",
    capabilities: ["Agents Extension", "Inline Chat", "File Context"],
    href: "/apps/vscode",
  },
  {
    name: "Cursor",
    tagline: "Native MCP integration — rules, context, and agent routing.",
    category: "Coding",
    filterCategory: "Coding",
    glyph: "⎈",
    color: "#ffffff",
    status: "live",
    capabilities: ["MCP Native", "Rules Sync", "Context Injection"],
    href: "/apps/cursor",
  },
  {
    name: "Windsurf",
    tagline: "Rules and context files for Windsurf's Cascade engine.",
    category: "Coding",
    filterCategory: "Coding",
    glyph: "⎔",
    color: "#00bcd4",
    status: "beta",
    capabilities: ["Rules Sync", "Context Files", "Cascade Hooks"],
    href: "/apps/windsurf",
  },
  {
    name: "Antigravity",
    tagline: "Browser-native IDE with Luminor agents running in-tab.",
    category: "Coding",
    filterCategory: "Coding",
    glyph: "↟",
    color: "#a855f7",
    status: "soon",
    capabilities: ["In-Browser Agents", "Realtime Collab", "MCP Bridge"],
    href: "/apps/antigravity",
  },
  {
    name: "GitHub",
    tagline: "27 open repos, PR reviews, and automated releases via Lumina.",
    category: "Coding",
    filterCategory: "Coding",
    glyph: "◉",
    color: "#ffffff",
    status: "live",
    installed: true,
    capabilities: ["PR Automation", "Release Manager", "Code Review"],
    href: "/apps/github",
  },
  {
    name: "Vercel",
    tagline: "Preview deployments — every world fork gets a live URL.",
    category: "Coding",
    filterCategory: "Coding",
    glyph: "▲",
    color: "#e2e8f0",
    status: "live",
    capabilities: ["Preview URLs", "Edge Config", "CI Hooks"],
    href: "/apps/vercel",
  },

  // ── Creative AI ─────────────────────────────────────────────────────────
  {
    name: "Suno",
    tagline: "AI music generation — tracks, albums, world soundtracks.",
    category: "Creative AI",
    filterCategory: "Creative AI",
    glyph: "♪",
    color: "#f472b6",
    status: "live",
    featured: true,
    capabilities: ["Generation", "Licensing", "World Sync"],
    href: "/apps/suno",
  },
  {
    name: "Nano Banana 2",
    tagline: "Premium image generation with Guardian style presets.",
    category: "Creative AI",
    filterCategory: "Creative AI",
    glyph: "◈",
    color: "#fbbf24",
    status: "live",
    featured: true,
    capabilities: ["Image Gen", "Style Presets", "Batch Export"],
    href: "/apps/nano-banana-2",
  },
  {
    name: "ElevenLabs",
    tagline: "Voice synthesis — Luminor voices, audiobooks, narration.",
    category: "Creative AI",
    filterCategory: "Creative AI",
    glyph: "▶",
    color: "#a855f7",
    status: "live",
    capabilities: ["Voice Cloning", "Audiobook Gen", "Luminor Voices"],
    href: "/apps/elevenlabs",
  },
  {
    name: "Runway",
    tagline: "Video generation for cinematic world intros and trailers.",
    category: "Creative AI",
    filterCategory: "Creative AI",
    glyph: "▸",
    color: "#00ff88",
    status: "beta",
    capabilities: ["Video Gen", "Trailer Engine", "Scene Bridge"],
    href: "/apps/runway",
  },
  {
    name: "Hedra",
    tagline: "Avatar animation — bring Guardian characters to life.",
    category: "Creative AI",
    filterCategory: "Creative AI",
    glyph: "◐",
    color: "#7fffd4",
    status: "beta",
    capabilities: ["Avatar Animation", "Lip Sync", "Guardian Skins"],
    href: "/apps/hedra",
  },
  {
    name: "Midjourney",
    tagline: "Style reference and concept art for worlds and characters.",
    category: "Creative AI",
    filterCategory: "Creative AI",
    glyph: "✦",
    color: "#e2e8f0",
    status: "soon",
    capabilities: ["Style Refs", "Character Art", "World Concepts"],
    href: "/apps/midjourney",
  },

  // ── Distribution ────────────────────────────────────────────────────────
  {
    name: "Blotato",
    tagline: "Multi-channel social posting — one creation, everywhere.",
    category: "Distribution",
    filterCategory: "Distribution",
    glyph: "◬",
    color: "#ef4444",
    status: "live",
    capabilities: ["Multi-Post", "Thread Engine", "Analytics"],
    href: "/apps/blotato",
  },
  {
    name: "Postiz",
    tagline: "Scheduling pipeline — drop your creation, Postiz handles the rest.",
    category: "Distribution",
    filterCategory: "Distribution",
    glyph: "◱",
    color: "#3b82f6",
    status: "live",
    capabilities: ["Scheduling", "Calendar", "Repurpose"],
    href: "/apps/postiz",
  },
  {
    name: "n8n",
    tagline: "Workflow automation — Arcanea events trigger any action.",
    category: "Distribution",
    filterCategory: "Distribution",
    glyph: "⏚",
    color: "#ea580c",
    status: "live",
    capabilities: ["Webhooks", "Node Engine", "Multi-Step Flows"],
    href: "/apps/n8n",
  },
  {
    name: "Zapier",
    tagline: "Trigger automation — connect Arcanea to 6,000+ apps.",
    category: "Distribution",
    filterCategory: "Distribution",
    glyph: "⚡",
    color: "#ff4a00",
    status: "soon",
    capabilities: ["Triggers", "Actions", "Multi-Step Zaps"],
    href: "/apps/zapier",
  },
  {
    name: "Linear",
    tagline: "Project sync — Arcanea AIPs and tasks become Linear issues.",
    category: "Distribution",
    filterCategory: "Distribution",
    glyph: "▰",
    color: "#5e6ad2",
    status: "live",
    capabilities: ["Issue Sync", "AIP Tracker", "Sprint Board"],
    href: "/apps/linear",
  },
  {
    name: "Stripe",
    tagline: "Payments — Founding Circle subscriptions and creator royalties.",
    category: "Distribution",
    filterCategory: "Distribution",
    glyph: "◱",
    color: "#635bff",
    status: "live",
    capabilities: ["Subscriptions", "Creator Payouts", "Webhook Engine"],
    href: "/apps/stripe",
  },

  // ── Community ───────────────────────────────────────────────────────────
  {
    name: "Discord",
    tagline: "Creator community — lore, contests, and live Luminor sessions.",
    category: "Community",
    filterCategory: "Community",
    glyph: "◎",
    color: "#5865F2",
    status: "live",
    installed: true,
    featured: true,
    capabilities: ["Server Bots", "Role Sync", "Live Sessions"],
    href: "/apps/discord",
  },
  {
    name: "Reddit",
    tagline: "r/Arcanea — community hub, AMA, feedback threads.",
    category: "Community",
    filterCategory: "Community",
    glyph: "◐",
    color: "#ff4500",
    status: "live",
    capabilities: ["Post Sync", "Flair System", "AMA Engine"],
    href: "/apps/reddit",
  },
  {
    name: "Whop",
    tagline: "Membership tiers — Founding Circle access and premium channels.",
    category: "Community",
    filterCategory: "Community",
    glyph: "⎊",
    color: "#f59e0b",
    status: "live",
    capabilities: ["Tier Access", "Gated Content", "Stripe Sync"],
    href: "/apps/whop",
  },
  {
    name: "Telegram",
    tagline: "Creator bots — Luminor Q&A and world-update notifications.",
    category: "Community",
    filterCategory: "Community",
    glyph: "✈",
    color: "#0088cc",
    status: "beta",
    capabilities: ["Bot Framework", "World Alerts", "Group Sync"],
    href: "/apps/telegram",
  },

  // ── Game Engines ────────────────────────────────────────────────────────
  {
    name: "Unreal Engine",
    tagline: "Export world data to Unreal scenes — characters, locations, lore.",
    category: "Game Engines",
    filterCategory: "Game Engines",
    glyph: "⧉",
    color: "#a0a0a0",
    status: "beta",
    capabilities: ["World Export", "Asset Pipeline", "Level Builder"],
    href: "/apps/unreal",
  },
  {
    name: "Unity",
    tagline: "Prefab pipeline — Arcanea assets drop into Unity projects.",
    category: "Game Engines",
    filterCategory: "Game Engines",
    glyph: "◇",
    color: "#e2e8f0",
    status: "beta",
    capabilities: ["Prefab Export", "Scene Bridge", "C# SDK"],
    href: "/apps/unity",
  },
  {
    name: "Godot",
    tagline: "Scene bridge — import worlds directly as Godot scene trees.",
    category: "Game Engines",
    filterCategory: "Game Engines",
    glyph: "◈",
    color: "#3d8fcc",
    status: "soon",
    capabilities: ["Scene Import", "GDScript Bindings", "Asset Sync"],
    href: "/apps/godot",
  },
  {
    name: "Roblox Studio",
    tagline: "Experience export — Arcanea worlds as Roblox experiences.",
    category: "Game Engines",
    filterCategory: "Game Engines",
    glyph: "◼",
    color: "#ef4444",
    status: "soon",
    capabilities: ["Experience Export", "Lua Scripts", "Asset Pack"],
    href: "/apps/roblox",
  },

  // ── Storage ─────────────────────────────────────────────────────────────
  {
    name: "Google Drive",
    tagline: "Vault sync — export all creations to Drive automatically.",
    category: "Storage",
    filterCategory: "Storage",
    glyph: "G",
    color: "#4285f4",
    status: "live",
    capabilities: ["Auto Sync", "Folder Structure", "Shared Drives"],
    href: "/apps/google-drive",
  },
  {
    name: "Notion",
    tagline: "Docs sync — Arcanea lore and world notes in your workspace.",
    category: "Storage",
    filterCategory: "Storage",
    glyph: "◰",
    color: "#e2e8f0",
    status: "live",
    capabilities: ["Page Sync", "Database Blocks", "Template Export"],
    href: "/apps/notion",
  },
  {
    name: "Supabase",
    tagline: "Database and auth — all world data lives in Supabase.",
    category: "Storage",
    filterCategory: "Storage",
    glyph: "◎",
    color: "#3ecf8e",
    status: "live",
    installed: true,
    capabilities: ["DB + Auth", "Realtime", "pgvector Search"],
    href: "/apps/supabase",
  },
  {
    name: "Obsidian",
    tagline: "Personal vault — world graphs as linked Obsidian notes.",
    category: "Storage",
    filterCategory: "Storage",
    glyph: "⬡",
    color: "#7c3aed",
    status: "beta",
    capabilities: ["Graph Export", "Markdown Sync", "Dataview Queries"],
    href: "/apps/obsidian",
  },
  {
    name: "Arweave",
    tagline: "Permanent storage — on-chain archival for your creations.",
    category: "Storage",
    filterCategory: "Storage",
    glyph: "∞",
    color: "#9ca3af",
    status: "beta",
    capabilities: ["Permanent Archive", "Content Hash", "IPFS Bridge"],
    href: "/apps/arweave",
  },
  {
    name: "Syncthing",
    tagline: "P2P device sync — offline-first creative vault across devices.",
    category: "Storage",
    filterCategory: "Storage",
    glyph: "⟳",
    color: "#22c55e",
    status: "soon",
    capabilities: ["P2P Sync", "Offline First", "Conflict Resolve"],
    href: "/apps/syncthing",
  },

  // ── Web3 ────────────────────────────────────────────────────────────────
  {
    name: "Base",
    tagline: "L2 deployments — mint, transfer, and royalties on Base.",
    category: "Web3",
    filterCategory: "Web3",
    glyph: "◉",
    color: "#0052ff",
    status: "live",
    capabilities: ["Mint Engine", "Royalties", "x402 Payments"],
    href: "/apps/base",
  },
  {
    name: "Story Protocol",
    tagline: "IP licensing — register your creations as programmable IP.",
    category: "Web3",
    filterCategory: "Web3",
    glyph: "✍",
    color: "#e2e8f0",
    status: "beta",
    capabilities: ["IP Registration", "License Terms", "Revenue Split"],
    href: "/apps/story-protocol",
  },
  {
    name: "Lens",
    tagline: "Social graph — creators as first-class on-chain identities.",
    category: "Web3",
    filterCategory: "Web3",
    glyph: "❁",
    color: "#22c55e",
    status: "soon",
    capabilities: ["Social Graph", "Profile NFT", "Follow API"],
    href: "/apps/lens",
  },
  {
    name: "Farcaster",
    tagline: "Decentralized feed — publish directly to the Farcaster protocol.",
    category: "Web3",
    filterCategory: "Web3",
    glyph: "△",
    color: "#855dcd",
    status: "beta",
    capabilities: ["Cast Engine", "Frame Builder", "Channel Sync"],
    href: "/apps/farcaster",
  },
];

export const CATEGORIES: Category[] = [
  "All",
  "Featured",
  "Creative AI",
  "Coding",
  "Distribution",
  "Community",
  "Game Engines",
  "Storage",
  "Web3",
];

export const HERO_STATS = [
  { value: "37+", label: "apps", color: "#7fffd4" },
  { value: "8", label: "categories", color: "#00bcd4" },
  { value: "MIT", label: "license", color: "#c084fc" },
  { value: "BYOK", label: "model agnostic", color: "#ffd700" },
];

export const FEATURED_NAMES = ["Claude Code", "Suno", "Nano Banana 2", "Discord"];
