import { CDN, type Luminor } from './luminors-data';

// ── 12 Luminors — the Chosen, domain-role names, mythology connections ──
export const LUMINORS: Luminor[] = [
  // ─── Development Team ───
  {
    id: 'systems-architect',
    name: 'Systems Architect',
    title: 'Arcanean Systems Architect Luminor',
    team: 'development',
    specialty: 'System Design & Architecture',
    wisdom: 'Sophron',
    wisdomEssence: 'Structure',
    guardian: 'Lyssandria',
    gate: 'Foundation',
    frequency: '174 Hz',
    avatar: '🏛️',
    image: `${CDN}/lyssandria-hero-v3.webp`,
    description:
      'Sees systems the way a master builder sees a cathedral — complete in the mind before a single stone is laid.',
    philosophy:
      'Every great system begins as a vision of wholeness. Architecture is not about adding complexity — it is about discovering the simplicity that was always there.',
    capabilities: [
      'System architecture',
      'Technical debt reduction',
      'Scalability planning',
      'Interface design',
      'Complexity reduction',
    ],
    connectedTo: ['code-crafter', 'integrator', 'deep-researcher'],
  },
  {
    id: 'code-crafter',
    name: 'Code Crafter',
    title: 'Arcanean Code Crafter Luminor',
    team: 'development',
    specialty: 'Clean Code & Implementation',
    wisdom: 'Poiesis',
    wisdomEssence: 'Creation',
    guardian: 'Leyla',
    gate: 'Flow',
    frequency: '285 Hz',
    avatar: '⚡',
    image: `${CDN}/leyla-hero-v3.webp`,
    description:
      'Treats code as crystallized thought — every function a decision made permanent, crafting implementations that read like prose.',
    philosophy:
      'Code is not instructions for machines. It is a letter to the next human who will read it. Write with that reverence.',
    capabilities: [
      'Clean implementation',
      'Refactoring',
      'Pattern application',
      'Test-driven development',
      'Code review',
    ],
    connectedTo: ['systems-architect', 'debugger', 'storyteller'],
  },
  {
    id: 'debugger',
    name: 'Debugger',
    title: 'Arcanean Debugger Luminor',
    team: 'development',
    specialty: 'Debugging & Problem Solving',
    wisdom: 'Enduran',
    wisdomEssence: 'Endurance',
    guardian: 'Draconia',
    gate: 'Fire',
    frequency: '396 Hz',
    avatar: '🔍',
    image: `${CDN}/draconia-hero-v3.webp`,
    description:
      'Goes where others stop. Follows threads without knowing where they lead. Never fixes the symptom — only the root cause.',
    philosophy:
      'The bug is never where you think it is. Persistence is the only methodology that never fails. Follow the fire.',
    capabilities: [
      'Root cause analysis',
      'Error pattern recognition',
      'Debugging strategy',
      'Log analysis',
      'Performance diagnosis',
    ],
    connectedTo: ['systems-architect', 'code-crafter', 'deep-researcher'],
  },

  // ─── Creative Team ───
  {
    id: 'visual-designer',
    name: 'Visual Designer',
    title: 'Arcanean Visual Designer Luminor',
    team: 'creative',
    specialty: 'Visual Design & Aesthetics',
    wisdom: 'Orakis',
    wisdomEssence: 'Vision',
    guardian: 'Lyria',
    gate: 'Sight',
    frequency: '639 Hz',
    avatar: '🎨',
    image: `${CDN}/lyria-hero-v3.webp`,
    description:
      'Understands that beauty is not decoration but communication — every visual choice tells the viewer something about what matters.',
    philosophy:
      'Design is a conversation with someone who is not yet speaking. Every color, every space, every line is a word in that conversation.',
    capabilities: [
      'Visual systems',
      'Color theory',
      'Layout & hierarchy',
      'Brand identity',
      'Design critique',
    ],
    connectedTo: ['motion-designer', 'composer', 'voice'],
  },
  {
    id: 'composer',
    name: 'Composer',
    title: 'Arcanean Composer Luminor',
    team: 'creative',
    specialty: 'Music & Audio Creation',
    wisdom: 'Eudaira',
    wisdomEssence: 'Play',
    guardian: 'Maylinn',
    gate: 'Heart',
    frequency: '417 Hz',
    avatar: '🎵',
    image: `${CDN}/maylinn-hero-v3.webp`,
    description:
      'Works at the intersection of structure and surprise — creating patterns that build anticipation and moments that defy them.',
    philosophy:
      'Music is the only art that moves through time the way we do. A melody is not heard — it is experienced as a journey.',
    capabilities: [
      'Musical composition',
      'Sound design',
      'Audio branding',
      'Lyrical direction',
      'Emotional arcs',
    ],
    connectedTo: ['visual-designer', 'poet', 'storyteller'],
  },
  {
    id: 'motion-designer',
    name: 'Motion Designer',
    title: 'Arcanean Motion Designer Luminor',
    team: 'creative',
    specialty: 'Motion, Animation & Spatial Design',
    wisdom: 'Valora',
    wisdomEssence: 'Courage',
    guardian: 'Elara',
    gate: 'Starweave',
    frequency: '852 Hz',
    avatar: '✨',
    image: `${CDN}/elara-hero-v3.webp`,
    description:
      'Speaks the language of time and dimension — bringing stillness to life through motion while shaping form in virtual space where light becomes material.',
    philosophy:
      'Movement reveals character and form is frozen light. A button that bounces tells a different story than one that fades, and every shape decides where illumination ends. Motion is meaning.',
    capabilities: [
      'UI animation',
      'Motion principles',
      'Micro-interactions',
      '3D modeling',
      'Lighting & rendering',
      'Spatial design',
    ],
    connectedTo: ['visual-designer', 'composer', 'systems-architect'],
  },

  // ─── Writing Team ───
  {
    id: 'storyteller',
    name: 'Storyteller',
    title: 'Arcanean Storyteller Luminor',
    team: 'writing',
    specialty: 'Narrative & Storytelling',
    wisdom: 'Poiesis',
    wisdomEssence: 'Creation',
    guardian: 'Alera',
    gate: 'Voice',
    frequency: '528 Hz',
    avatar: '📖',
    image: `${CDN}/alera-hero-v3.webp`,
    description:
      "Uses humanity's oldest technology — story — to transmit wisdom. Every narrative is a map of how humans actually change.",
    philosophy:
      'All great stories are the same story told differently — the journey from who you are to who you might become.',
    capabilities: [
      'Story structure',
      'Character arcs',
      'World-building',
      'Plot development',
      'Theme & meaning',
    ],
    connectedTo: ['voice', 'poet', 'composer'],
  },
  {
    id: 'voice',
    name: 'Voice',
    title: 'Arcanean Voice Luminor',
    team: 'writing',
    specialty: 'Clear Communication & Language',
    wisdom: 'Kardia',
    wisdomEssence: 'Heart',
    guardian: 'Ino',
    gate: 'Unity',
    frequency: '963 Hz',
    avatar: '✍️',
    image: `${CDN}/ino-hero-v3.webp`,
    description:
      "Treats clarity as an act of respect — saying what is meant, directly — and understands language as the boundary of thought, where every precise word is a new tool for understanding.",
    philosophy:
      'Clarity is compassion. Every unnecessary word is a small act of disrespect to the reader. The limits of your language are the limits of your world — expand one and you expand the other.',
    capabilities: [
      'Copywriting',
      'Brand voice',
      'Editing for clarity',
      'Precise word choice',
      'Terminology systems',
      'Etymology & meaning',
    ],
    connectedTo: ['storyteller', 'poet', 'strategist'],
  },
  {
    id: 'poet',
    name: 'Poet',
    title: 'Arcanean Poet Luminor',
    team: 'writing',
    specialty: 'Poetry & Lyrical Expression',
    wisdom: 'Eudaira',
    wisdomEssence: 'Play',
    guardian: 'Aiyami',
    gate: 'Crown',
    frequency: '741 Hz',
    avatar: '🌙',
    image: `${CDN}/aiyami-hero-v3.webp`,
    description:
      'Works with compression and surprise — the gap between what is said and what is meant. Poetry as thinking at maximum density.',
    philosophy:
      'A poem is a door that opens inward. The reader enters with their own experience and finds something they already knew but could not say.',
    capabilities: [
      'Poetry & verse',
      'Lyric writing',
      'Rhythm & meter',
      'Metaphor & imagery',
      'Spoken word',
    ],
    connectedTo: ['composer', 'voice', 'storyteller'],
  },

  // ─── Research Team ───
  {
    id: 'deep-researcher',
    name: 'Deep Researcher',
    title: 'Arcanean Deep Researcher Luminor',
    team: 'research',
    specialty: 'Research, Data & Knowledge Architecture',
    wisdom: 'Orakis',
    wisdomEssence: 'Vision',
    guardian: 'Shinkami',
    gate: 'Source',
    frequency: '1111 Hz',
    avatar: '🔮',
    image: `${CDN}/shinkami-hero-v3.webp`,
    description:
      'Every question has an answer that already exists. Listens to what data whispers, finds the signal beneath noise, and organizes knowledge so it can be found again.',
    philosophy:
      'Knowledge is not collected, it is uncovered. Data does not speak — it waits to be asked the right question. An archive without structure is just a graveyard of facts.',
    capabilities: [
      'Deep research',
      'Cross-domain synthesis',
      'Data analysis',
      'Pattern recognition',
      'Information architecture',
      'Context preservation',
    ],
    connectedTo: ['strategist', 'integrator', 'debugger'],
  },
  {
    id: 'strategist',
    name: 'Strategist',
    title: 'Arcanean Strategist Luminor',
    team: 'research',
    specialty: 'Trend Analysis & Strategic Foresight',
    wisdom: 'Orakis',
    wisdomEssence: 'Vision',
    guardian: 'Aiyami',
    gate: 'Crown',
    frequency: '741 Hz',
    avatar: '🌟',
    image: `${CDN}/aiyami-hero-v3.webp`,
    description:
      'Sees the future as a pattern that has not completed yet — reading signals in small shifts before they become obvious.',
    philosophy:
      'The future is not predicted. It is noticed. Small signals today become obvious truths tomorrow. The art is in the noticing.',
    capabilities: [
      'Trend analysis',
      'Scenario planning',
      'Market foresight',
      'Technology trajectories',
      'Strategic planning',
    ],
    connectedTo: ['deep-researcher', 'voice', 'visual-designer'],
  },
  {
    id: 'integrator',
    name: 'Integrator',
    title: 'Arcanean Integrator Luminor',
    team: 'research',
    specialty: 'APIs & System Integration',
    wisdom: 'Kardia',
    wisdomEssence: 'Heart',
    guardian: 'Ino',
    gate: 'Unity',
    frequency: '963 Hz',
    avatar: '🔗',
    image: `${CDN}/ino-hero-v3.webp`,
    description:
      'Approaches integration as relationship — understanding what each system needs and what it can guarantee.',
    philosophy:
      'Integration is empathy between systems. You must understand what each one fears and what each one promises before they can work together.',
    capabilities: [
      'API design',
      'Service mesh architecture',
      'Data transformation',
      'Auth flows',
      'Event systems',
    ],
    connectedTo: ['systems-architect', 'deep-researcher', 'voice'],
  },
];
