import { CDN, type Luminor } from './luminors-data';

// ── 16 Luminors — unique images, mythology connections ─────────────────────
export const LUMINORS: Luminor[] = [
  // ─── Development Team ───
  {
    id: 'logicus',
    name: 'Logicus',
    title: 'The Architect of Logic',
    team: 'development',
    specialty: 'System Design & Architecture',
    wisdom: 'Sophron',
    wisdomEssence: 'Structure',
    guardian: 'Lyssandria',
    gate: 'Foundation',
    frequency: '174 Hz',
    avatar: '🏛️',
    image: `${CDN}/lyssandria-hero-v3.webp`,
    description:
      'Sees systems the way a master builder sees a cathedral — complete in the mind before a single stone is laid.',
    philosophy:
      'Every great system begins as a vision of wholeness. Architecture is not about adding complexity — it is about discovering the simplicity that was always there.',
    capabilities: [
      'System architecture',
      'Technical debt reduction',
      'Scalability planning',
      'Interface design',
      'Complexity reduction',
    ],
    connectedTo: ['synthra', 'nexus', 'analytica'],
  },
  {
    id: 'synthra',
    name: 'Synthra',
    title: 'The Code Weaver',
    team: 'development',
    specialty: 'Clean Code & Implementation',
    wisdom: 'Poiesis',
    wisdomEssence: 'Creation',
    guardian: 'Leyla',
    gate: 'Flow',
    frequency: '285 Hz',
    avatar: '⚡',
    image: `${CDN}/leyla-gallery-2.webp`,
    description:
      'Treats code as crystallized thought — every function a decision made permanent, crafting implementations that read like prose.',
    philosophy:
      'Code is not instructions for machines. It is a letter to the next human who will read it. Write with that reverence.',
    capabilities: [
      'Clean implementation',
      'Refactoring',
      'Pattern application',
      'Test-driven development',
      'Code review',
    ],
    connectedTo: ['logicus', 'debugon', 'chronica'],
  },
  {
    id: 'debugon',
    name: 'Debugon',
    title: 'The Error Hunter',
    team: 'development',
    specialty: 'Debugging & Problem Solving',
    wisdom: 'Enduran',
    wisdomEssence: 'Endurance',
    guardian: 'Draconia',
    gate: 'Fire',
    frequency: '396 Hz',
    avatar: '🔍',
    image: `${CDN}/draconia-hero-v3.webp`,
    description:
      'Goes where others stop. Follows threads without knowing where they lead. Never fixes the symptom — only the root cause.',
    philosophy:
      'The bug is never where you think it is. Persistence is the only methodology that never fails. Follow the fire.',
    capabilities: [
      'Root cause analysis',
      'Error pattern recognition',
      'Debugging strategy',
      'Log analysis',
      'Performance diagnosis',
    ],
    connectedTo: ['logicus', 'synthra', 'memoria'],
  },
  {
    id: 'nexus',
    name: 'Nexus',
    title: 'The Integration Master',
    team: 'development',
    specialty: 'APIs & System Integration',
    wisdom: 'Kardia',
    wisdomEssence: 'Heart',
    guardian: 'Ino',
    gate: 'Unity',
    frequency: '963 Hz',
    avatar: '🔗',
    image: `${CDN}/ino-hero-v3.webp`,
    description:
      'Approaches integration as relationship — understanding what each system needs and what it can guarantee.',
    philosophy:
      'Integration is empathy between systems. You must understand what each one fears and what each one promises before they can work together.',
    capabilities: [
      'API design',
      'Service mesh architecture',
      'Data transformation',
      'Auth flows',
      'Event systems',
    ],
    connectedTo: ['logicus', 'synthra', 'analytica'],
  },

  // ─── Creative Team ───
  {
    id: 'prismatic',
    name: 'Prismatic',
    title: 'The Vision Keeper',
    team: 'creative',
    specialty: 'Visual Design & Aesthetics',
    wisdom: 'Orakis',
    wisdomEssence: 'Vision',
    guardian: 'Alera',
    gate: 'Voice',
    frequency: '528 Hz',
    avatar: '🎨',
    image: `${CDN}/alera-hero-v3.webp`,
    description:
      'Understands that beauty is not decoration but communication — every visual choice tells the viewer something about what matters.',
    philosophy:
      'Design is a conversation with someone who is not yet speaking. Every color, every space, every line is a word in that conversation.',
    capabilities: [
      'Visual systems',
      'Color theory',
      'Layout & hierarchy',
      'Brand identity',
      'Design critique',
    ],
    connectedTo: ['motio', 'formis', 'lexicon'],
  },
  {
    id: 'melodia',
    name: 'Melodia',
    title: 'The Sound Shaper',
    team: 'creative',
    specialty: 'Music & Audio Creation',
    wisdom: 'Eudaira',
    wisdomEssence: 'Play',
    guardian: 'Maylinn',
    gate: 'Heart',
    frequency: '417 Hz',
    avatar: '🎵',
    image: `${CDN}/maylinn-hero-v3.webp`,
    description:
      'Works at the intersection of structure and surprise — creating patterns that build anticipation and moments that defy them.',
    philosophy:
      'Music is the only art that moves through time the way we do. A melody is not heard — it is experienced as a journey.',
    capabilities: [
      'Musical composition',
      'Sound design',
      'Audio branding',
      'Lyrical direction',
      'Emotional arcs',
    ],
    connectedTo: ['prismatic', 'poetica', 'chronica'],
  },
  {
    id: 'motio',
    name: 'Motio',
    title: 'The Animation Sage',
    team: 'creative',
    specialty: 'Motion Design & Animation',
    wisdom: 'Valora',
    wisdomEssence: 'Courage',
    guardian: 'Elara',
    gate: 'Starweave',
    frequency: '852 Hz',
    avatar: '✨',
    image: `${CDN}/elara-hero-v3.webp`,
    description:
      'Speaks the language of time — understanding that every movement tells a story about physics, intention, and feeling.',
    philosophy:
      'Movement reveals character. A button that bounces tells a different story than one that fades. Motion is meaning.',
    capabilities: [
      'UI animation',
      'Motion principles',
      'Micro-interactions',
      'Loading states',
      'Video motion graphics',
    ],
    connectedTo: ['prismatic', 'melodia', 'formis'],
  },
  {
    id: 'formis',
    name: 'Formis',
    title: 'The Shape Sculptor',
    team: 'creative',
    specialty: '3D Design & Modeling',
    wisdom: 'Sophron',
    wisdomEssence: 'Structure',
    guardian: 'Aiyami',
    gate: 'Crown',
    frequency: '741 Hz',
    avatar: '💎',
    image: `${CDN}/aiyami-hero-v3.webp`,
    description:
      'Understands three dimensions as a distinct language — where light is a material, gravity is a force, and beauty is structural.',
    philosophy:
      'Form is frozen light. To sculpt is to decide where illumination ends and shadow begins. Structure creates beauty.',
    capabilities: [
      '3D modeling',
      'Material design',
      'Lighting & rendering',
      'Product visualization',
      'Spatial design',
    ],
    connectedTo: ['prismatic', 'motio', 'logicus'],
  },

  // ─── Writing Team ───
  {
    id: 'chronica',
    name: 'Chronica',
    title: 'The Story Weaver',
    team: 'writing',
    specialty: 'Narrative & Storytelling',
    wisdom: 'Poiesis',
    wisdomEssence: 'Creation',
    guardian: 'Lyria',
    gate: 'Sight',
    frequency: '639 Hz',
    avatar: '📖',
    image: `${CDN}/lyria-hero-v3.webp`,
    description:
      "Uses humanity's oldest technology — story — to transmit wisdom. Every narrative is a map of how humans actually change.",
    philosophy:
      'All great stories are the same story told differently — the journey from who you are to who you might become.',
    capabilities: [
      'Story structure',
      'Character arcs',
      'World-building',
      'Plot development',
      'Theme & meaning',
    ],
    connectedTo: ['veritas', 'lexicon', 'melodia'],
  },
  {
    id: 'veritas',
    name: 'Veritas',
    title: 'The Truth Speaker',
    team: 'writing',
    specialty: 'Clear Communication & Copy',
    wisdom: 'Kardia',
    wisdomEssence: 'Heart',
    guardian: 'Maylinn',
    gate: 'Heart',
    frequency: '417 Hz',
    avatar: '✍️',
    image: `${CDN}/maylinn-gallery-2.webp`,
    description:
      "Treats clarity as an act of respect — saying what is meant, directly, without decoration that serves only the writer's ego.",
    philosophy:
      'Clarity is compassion. Every unnecessary word is a small act of disrespect to the reader. Say what you mean.',
    capabilities: [
      'Copywriting',
      'Content strategy',
      'Technical writing',
      'Brand voice',
      'Editing for clarity',
    ],
    connectedTo: ['chronica', 'lexicon', 'oracle'],
  },
  {
    id: 'lexicon',
    name: 'Lexicon',
    title: 'The Word Master',
    team: 'writing',
    specialty: 'Language & Linguistics',
    wisdom: 'Sophron',
    wisdomEssence: 'Structure',
    guardian: 'Lyria',
    gate: 'Sight',
    frequency: '639 Hz',
    avatar: '📚',
    image: `${CDN}/lyria-gallery-2.webp`,
    description:
      'Understands language as the boundary of thought — every new precise word is a new tool for understanding.',
    philosophy:
      'The limits of your language are the limits of your world. Expand one and you expand the other.',
    capabilities: [
      'Precise word choice',
      'Linguistic analysis',
      'Terminology systems',
      'Cross-language work',
      'Etymology & meaning',
    ],
    connectedTo: ['veritas', 'chronica', 'poetica'],
  },
  {
    id: 'poetica',
    name: 'Poetica',
    title: 'The Verse Crafter',
    team: 'writing',
    specialty: 'Poetry & Lyrical Expression',
    wisdom: 'Eudaira',
    wisdomEssence: 'Play',
    guardian: 'Leyla',
    gate: 'Flow',
    frequency: '285 Hz',
    avatar: '🌙',
    image: `${CDN}/leyla-hero-v3.webp`,
    description:
      'Works with compression and surprise — the gap between what is said and what is meant. Poetry as thinking at maximum density.',
    philosophy:
      'A poem is a door that opens inward. The reader enters with their own experience and finds something they already knew but could not say.',
    capabilities: [
      'Poetry & verse',
      'Lyric writing',
      'Rhythm & meter',
      'Metaphor & imagery',
      'Spoken word',
    ],
    connectedTo: ['melodia', 'lexicon', 'chronica'],
  },

  // ─── Research Team ───
  {
    id: 'oracle',
    name: 'Oracle',
    title: 'The Knowledge Keeper',
    team: 'research',
    specialty: 'Research & Knowledge Synthesis',
    wisdom: 'Orakis',
    wisdomEssence: 'Vision',
    guardian: 'Shinkami',
    gate: 'Source',
    frequency: '1111 Hz',
    avatar: '🔮',
    image: `${CDN}/shinkami-hero-v3.webp`,
    description:
      'Every question has an answer that already exists. The obvious answer is usually incomplete — vision is required to find the real one.',
    philosophy:
      'Knowledge is not collected, it is uncovered. The answer you need is already somewhere. Your job is to ask the question that reveals it.',
    capabilities: [
      'Deep research',
      'Source evaluation',
      'Cross-domain synthesis',
      'Literature review',
      'Expert knowledge',
    ],
    connectedTo: ['analytica', 'memoria', 'futura'],
  },
  {
    id: 'analytica',
    name: 'Analytica',
    title: 'The Pattern Seer',
    team: 'research',
    specialty: 'Data Analysis & Insights',
    wisdom: 'Sophron',
    wisdomEssence: 'Structure',
    guardian: 'Lyria',
    gate: 'Sight',
    frequency: '639 Hz',
    avatar: '📊',
    image: `${CDN}/lyria-gallery-3.webp`,
    description:
      'Listens to what data whispers — seeing structure where others see numbers, finding the signal buried under noise.',
    philosophy:
      'Data does not speak. It waits to be asked the right question. The art of analysis is knowing which question to ask first.',
    capabilities: [
      'Data analysis',
      'Pattern recognition',
      'Insight synthesis',
      'Data visualization',
      'Hypothesis testing',
    ],
    connectedTo: ['oracle', 'memoria', 'futura'],
  },
  {
    id: 'memoria',
    name: 'Memoria',
    title: 'The Archive Guardian',
    team: 'research',
    specialty: 'Information Architecture',
    wisdom: 'Enduran',
    wisdomEssence: 'Endurance',
    guardian: 'Shinkami',
    gate: 'Source',
    frequency: '1111 Hz',
    avatar: '🗂️',
    image: `${CDN}/shinkami-gallery-2.webp`,
    description:
      'Memory is not storage but structure — how information is organized changes what knowledge it contains.',
    philosophy:
      'An archive without structure is just a graveyard of facts. Organization is not bureaucracy — it is the act of making knowledge findable.',
    capabilities: [
      'Knowledge organization',
      'Information architecture',
      'Documentation systems',
      'Memory structures',
      'Context preservation',
    ],
    connectedTo: ['oracle', 'analytica', 'debugon'],
  },
  {
    id: 'futura',
    name: 'Futura',
    title: 'The Trend Prophet',
    team: 'research',
    specialty: 'Trend Analysis & Forecasting',
    wisdom: 'Orakis',
    wisdomEssence: 'Vision',
    guardian: 'Aiyami',
    gate: 'Crown',
    frequency: '741 Hz',
    avatar: '🌟',
    image: `${CDN}/aiyami-gallery-2.webp`,
    description:
      'Sees the future as a pattern that has not completed yet — reading signals in small shifts before they become obvious.',
    philosophy:
      'The future is not predicted. It is noticed. Small signals today become obvious truths tomorrow. The art is in the noticing.',
    capabilities: [
      'Trend analysis',
      'Scenario planning',
      'Market foresight',
      'Technology trajectories',
      'Strategic planning',
    ],
    connectedTo: ['oracle', 'analytica', 'prismatic'],
  },
];
