/** Media library CSS custom properties, mirrored in tokens.css for non-React clients. */
export const mediaLibraryTokens = {
  "--arc-space-fluid-stage-inset": "clamp(1.25rem, 3vw, 2.25rem)",
  "--arc-space-media-heading-gap": "1.5rem",
  "--arc-space-media-heading-bottom": "1.75rem",
  "--arc-space-media-layout-gap": "clamp(1.25rem, 2.5vw, 2rem)",
  "--arc-space-media-controls-inset": "clamp(1rem, 3vw, 2rem)",
  "--arc-space-media-empty-gap": "clamp(1rem, 4vw, 3rem)",
  "--arc-space-media-page-gutter": "1rem",
  "--arc-space-media-page-gutter-wide": "1.5rem",
  "--arc-space-media-page-top": "2.25rem",
  "--arc-space-media-page-bottom": "5rem",
  "--arc-type-media-kicker": "0.82rem",
  "--arc-type-media-heading": "clamp(2rem, 3.5vw, 3.25rem)",
  "--arc-type-media-caption": "clamp(1.15rem, 2vw, 1.45rem)",
  "--arc-type-media-empty": "clamp(1.65rem, 2.5vw, 2.25rem)",
  "--arc-type-media-page-title": "2.25rem",
  "--arc-type-media-page-title-wide": "3rem",
  "--arc-type-media-section-title": "1.5rem",
  "--arc-type-media-section-title-wide": "1.875rem",
  "--arc-type-media-body": "0.875rem",
  "--arc-type-media-note": "0.75rem",
  "--arc-line-media-note": "1.25rem",
  "--arc-line-media-body": "1.5rem",
  "--arc-line-media-reading": "1.75rem",
  "--arc-line-media-heading": "1.07",
  "--arc-line-media-intro": "1.6",
  "--arc-line-media-caption": "1.3",
  "--arc-line-media-transcript": "1.65",
  "--arc-track-media-heading": "-0.025em",
  "--arc-weight-media-regular": "400",
  "--arc-weight-media-semibold": "600",
  "--arc-size-media-page-max": "80rem",
  "--arc-size-media-description-max": "42rem",
  "--arc-size-media-signin-copy-max": "36rem",
  "--arc-size-media-loading": "26rem",
  "--arc-size-media-sidebar-min": "15rem",
  "--arc-size-media-preview-min": "18rem",
  "--arc-size-media-rail-max": "35rem",
  "--arc-size-media-rail-item-min": "78px",
  "--arc-size-media-thumb-width": "64px",
  "--arc-size-media-thumb-height": "58px",
  "--arc-size-media-row-icon": "3.5rem",
  "--arc-size-media-empty-min": "19rem",
  "--arc-size-media-mobile-preview-min": "15rem",
  "--arc-size-media-mobile-empty-min": "13rem",
  "--arc-size-media-mobile-card": "min(14rem, 70vw)",
  "--arc-size-interactive-min": "44px",
  "--arc-media-space-020": "0.2rem",
  "--arc-media-space-025": "0.25rem",
  "--arc-media-space-030": "0.3rem",
  "--arc-media-space-035": "0.35rem",
  "--arc-media-space-040": "0.4rem",
  "--arc-media-space-050": "0.5rem",
  "--arc-media-space-055": "0.55rem",
  "--arc-media-space-060": "0.6rem",
  "--arc-media-space-065": "0.65rem",
  "--arc-media-space-070": "0.7rem",
  "--arc-media-space-075": "0.75rem",
  "--arc-media-space-080": "0.8rem",
  "--arc-media-space-085": "0.85rem",
  "--arc-media-space-100": "1rem",
  "--arc-media-space-125": "1.25rem",
  "--arc-media-space-150": "1.5rem",
  "--arc-media-space-200": "2rem",
  "--arc-media-space-300": "3rem",
  "--arc-media-type-078": "0.78rem",
  "--arc-media-type-080": "0.8rem",
  "--arc-media-type-085": "0.85rem",
  "--arc-media-type-088": "0.88rem",
  "--arc-media-type-090": "0.9rem",
  "--arc-media-type-095": "0.95rem",
  "--arc-media-rule-width": "1px",
  "--arc-media-focus-width": "2px",
  "--arc-media-focus-offset": "3px",
  "--arc-size-media-transcript-max": "18rem",
  "--arc-size-media-content-max": "32rem",
  "--arc-ratio-media-preview": "16 / 10",
  "--arc-ratio-media-preview-mobile": "4 / 3",
  "--arc-grid-media-main": "1.65fr",
  "--arc-grid-media-sidebar": "0.65fr",
  "--arc-grid-media-empty-main": "1.4fr",
  "--arc-grid-media-empty-sidebar": "0.6fr",
  "--arc-opacity-media-artwork": "0.4",
  "--arc-mix-media-controls": "88%",
  "--arc-offset-media-underline": "0.2em",
  "--arc-layer-media-controls": "1",
} as const;
