// Re-export all graph data from the split modules.
// This file is kept for backward compatibility — new code should import from './data'.
export {
  COLORS,
  nodeStyle,
  edgeStyle,
  ecosystemNodes,
  ecosystemEdges,
  ecosystemLegend,
  intelligenceNodes,
  intelligenceEdges,
  intelligenceLegend,
  memoryNodes,
  memoryEdges,
  memoryLegend,
  agentNodes,
  agentEdges,
  agentLegend,
  roadmapNodes,
  roadmapEdges,
  roadmapLegend,
  businessNodes,
  businessEdges,
  businessLegend,
} from './data';
