/**
 * Grimoire Formatter
 *
 * Transforms a raw GrimoireResult into a publication-quality markdown document.
 * Sections are ordered and numbered with Roman numerals. Missing sections are
 * omitted from the output rather than shown as errors.
 */

import type { GrimoireResult } from './orchestrator';

// ---------------------------------------------------------------------------
// Section display order and Roman numeral labels
// ---------------------------------------------------------------------------

const SECTION_ORDER: string[] = [
  'world-overview',
  'magic-system',
  'characters',
  'factions',
  'chapter-1',
  'chapter-2',
  'chapter-3',
  'chapter-4',
  'chapter-5',
  'visual-direction',
  'soundtrack',
  'publishing-plan',
  'world-bible',
];

const ROMAN: Record<number, string> = {
  1: 'I',
  2: 'II',
  3: 'III',
  4: 'IV',
  5: 'V',
  6: 'VI',
  7: 'VII',
  8: 'VIII',
  9: 'IX',
  10: 'X',
  11: 'XI',
  12: 'XII',
  13: 'XIII',
};

function toRoman(n: number): string {
  return ROMAN[n] ?? String(n);
}

// ---------------------------------------------------------------------------
// Section title map — human-readable display names
// ---------------------------------------------------------------------------

const SECTION_TITLES: Record<string, string> = {
  'world-overview': 'World Overview',
  'magic-system': 'The Power System',
  'characters': 'Characters',
  'factions': 'Factions & Power Structures',
  'chapter-1': 'Chapter 1',
  'chapter-2': 'Chapter 2',
  'chapter-3': 'Chapter 3',
  'chapter-4': 'Chapter 4',
  'chapter-5': 'Chapter 5',
  'visual-direction': 'Visual Direction',
  'soundtrack': 'Soundtrack Concept',
  'publishing-plan': 'Publishing Plan',
  'world-bible': 'Complete World Bible',
};

// Sections that render as chapters in the Chapters group
const CHAPTER_IDS = new Set(['chapter-1', 'chapter-2', 'chapter-3', 'chapter-4', 'chapter-5']);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return iso;
  }
}

function tierLabel(tier: string): string {
  const labels: Record<string, string> = {
    apprentice: 'Apprentice',
    mage: 'Mage',
    archmage: 'Archmage',
  };
  return labels[tier] ?? tier;
}

function stripErrorSections(content: string): boolean {
  return content.startsWith('[Section unavailable:') || content.startsWith('[Section generation failed:');
}

// ---------------------------------------------------------------------------
// Main formatter
// ---------------------------------------------------------------------------

export function formatGrimoire(
  result: GrimoireResult,
  answers: Record<string, string>,
): string {
  const { sections, metadata } = result;
  const sectionMap = new Map(sections.map((s) => [s.id, s]));

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push(`# ${metadata.worldName} — A Grimoire`);
  lines.push('');
  lines.push('> Generated by the Arcanea Intelligence System');
  lines.push(`> Tier: ${tierLabel(metadata.tier)}`);
  lines.push(`> Date: ${formatDate(metadata.generatedAt)}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Table of Contents ────────────────────────────────────────────────────
  lines.push('## Table of Contents');
  lines.push('');

  let sectionIndex = 0;
  const chapterSections = SECTION_ORDER.filter((id) => CHAPTER_IDS.has(id) && sectionMap.has(id));
  const hasChapters = chapterSections.length > 0;
  let chaptersGrouped = false;

  for (const sectionId of SECTION_ORDER) {
    const section = sectionMap.get(sectionId);
    if (!section || stripErrorSections(section.content)) continue;

    if (CHAPTER_IDS.has(sectionId)) {
      if (!chaptersGrouped) {
        sectionIndex += 1;
        lines.push(`${toRoman(sectionIndex)}. Chapters (${chapterSections.length})`);
        chaptersGrouped = true;
      }
      continue;
    }

    sectionIndex += 1;
    const displayTitle = SECTION_TITLES[sectionId] ?? section.title;
    lines.push(`${toRoman(sectionIndex)}. ${displayTitle}`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Sections ─────────────────────────────────────────────────────────────
  sectionIndex = 0;
  chaptersGrouped = false;
  let chapterSubIndex = 0;

  for (const sectionId of SECTION_ORDER) {
    const section = sectionMap.get(sectionId);
    if (!section || stripErrorSections(section.content)) continue;

    const displayTitle = SECTION_TITLES[sectionId] ?? section.title;

    if (CHAPTER_IDS.has(sectionId)) {
      if (!chaptersGrouped) {
        sectionIndex += 1;
        lines.push(`## ${toRoman(sectionIndex)}. Chapters`);
        lines.push('');
        chaptersGrouped = true;
      }

      chapterSubIndex += 1;
      lines.push(`### Chapter ${chapterSubIndex}`);
      lines.push('');
      lines.push(section.content.trim());
      lines.push('');
      lines.push('---');
      lines.push('');
      continue;
    }

    sectionIndex += 1;
    lines.push(`## ${toRoman(sectionIndex)}. ${displayTitle}`);
    lines.push('');
    lines.push(section.content.trim());
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  lines.push('');
  lines.push('*Forged by the Guardians of Arcanea*');
  lines.push('*arcanea.ai/agents/grimoire*');
  lines.push('');

  // ── Metadata block (hidden — useful for debugging/archiving) ─────────────
  lines.push('<!-- grimoire-meta');
  lines.push(`worldName: ${metadata.worldName}`);
  lines.push(`tier: ${metadata.tier}`);
  lines.push(`agentsUsed: ${metadata.agentsUsed}`);
  lines.push(`tokensUsed: ${metadata.tokensUsed}`);
  lines.push(`generatedAt: ${metadata.generatedAt}`);
  if (answers['email']) lines.push(`email: ${answers['email']}`);
  lines.push('-->');

  return lines.join('\n');
}
