"use client"

import { useState } from "react"
import {
  Lightning,
  CaretDown,
  Copy,
  Check,
  ArrowsClockwise,
  Sparkle,
} from '@/lib/phosphor-icons'
import { cn } from "@/lib/utils"

interface CodeTabProps {
  generationState: "idle" | "generating" | "complete" | "error"
}

const languages = [
  "TypeScript", "Python", "Rust", "Go", "Solidity", "C++", "JavaScript", "Swift",
]

const aiCompletions = [
  "Generate a runic cipher encryption function",
  "Create a mythology database schema",
  "Build a divine attribute system class",
  "Implement a prophecy pattern matcher",
]

const defaultCode = `// Arcane Cipher — Mythological Encryption Engine
// Generated by Arcanea Studio AI

import { RuneAlphabet, DivineKey } from './arcane-types';

/**
 * The SerpentCipher uses ancient runic substitution
 * combined with celestial key rotation.
 */
export class SerpentCipher {
  private readonly runeMap: Map<string, string>;
  private rotationSeed: number;

  constructor(private readonly divineKey: DivineKey) {
    this.runeMap = RuneAlphabet.buildSubstitutionTable(divineKey);
    this.rotationSeed = divineKey.celestialOffset;
  }

  encode(plaintext: string): string {
    return plaintext
      .split('')
      .map((char, idx) => {
        const rune = this.runeMap.get(char.toLowerCase());
        const shifted = this.celestialShift(rune ?? char, idx);
        return char === char.toUpperCase() ? shifted.toUpperCase() : shifted;
      })
      .join('');
  }

  private celestialShift(char: string, position: number): string {
    const offset = (this.rotationSeed + position) % 26;
    const code = char.charCodeAt(0);
    if (code >= 97 && code <= 122) {
      return String.fromCharCode(((code - 97 + offset) % 26) + 97);
    }
    return char;
  }

  decode(ciphertext: string): string {
    // Reverse the celestial rotation to restore plaintext
    return ciphertext
      .split('')
      .map((char, idx) => {
        const offset = (this.rotationSeed + idx) % 26;
        const code = char.toLowerCase().charCodeAt(0);
        if (code >= 97 && code <= 122) {
          const decoded = String.fromCharCode(
            ((code - 97 - offset + 26) % 26) + 97
          );
          return char === char.toUpperCase() ? decoded.toUpperCase() : decoded;
        }
        return char;
      })
      .join('');
  }
}
`

// Extremely simplified syntax highlighting
function highlight(code: string, language: string): React.ReactNode[] {
  const lines = code.split('\n')
  const keywords = ['import', 'export', 'const', 'let', 'class', 'function', 'return', 'private', 'readonly', 'new', 'this', 'if', 'map', 'from', 'constructor', 'string', 'number', 'void']
  const builtins = ['Map', 'String', 'Array']

  return lines.map((line, lineIdx) => {
    const isComment = line.trimStart().startsWith('//')
    const isJSDoc = line.trimStart().startsWith('*') || line.trimStart().startsWith('/**')
    const isImport = line.startsWith('import') || line.startsWith('export')

    let color = '#e8e6f0'
    if (isComment || isJSDoc) color = '#7c7a8e'
    else if (isImport) color = '#a78bfa'

    return (
      <div key={lineIdx} className="flex gap-4">
        <span className="select-none text-right text-[rgba(255,255,255,0.2)] font-mono text-xs shrink-0 w-7 leading-6">
          {lineIdx + 1}
        </span>
        <span className="leading-6 whitespace-pre" style={{ color }}>
          {line}
        </span>
      </div>
    )
  })
}

export function CodeTab({ generationState }: CodeTabProps) {
  const [code, setCode] = useState(defaultCode)
  const [selectedLang, setSelectedLang] = useState("TypeScript")
  const [showLangDropdown, setShowLangDropdown] = useState(false)
  const [selectedPrompt, setSelectedPrompt] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const lineCount = code.split('\n').length

  return (
    <div className="flex flex-col h-full">
      {/* Editor Toolbar */}
      <div className="flex items-center gap-2 px-4 py-2.5 border-b border-[rgba(139,92,246,0.1)] bg-[rgba(10,10,15,0.5)]">
        {/* Language selector */}
        <div className="relative">
          <button
            onClick={() => setShowLangDropdown(!showLangDropdown)}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-[rgba(139,92,246,0.1)] border border-[rgba(139,92,246,0.2)] text-xs text-[#a78bfa] hover:bg-[rgba(139,92,246,0.15)] transition-colors"
          >
            {selectedLang}
            <CaretDown size={11} />
          </button>
          {showLangDropdown && (
            <div className="absolute top-full left-0 mt-1 w-40 rounded-xl border border-[rgba(139,92,246,0.2)] bg-[#13131c] shadow-2xl shadow-black/50 z-50 overflow-hidden">
              {languages.map((lang) => (
                <button
                  key={lang}
                  onClick={() => { setSelectedLang(lang); setShowLangDropdown(false) }}
                  className={cn(
                    "w-full text-left px-3 py-2 text-xs transition-colors hover:bg-[rgba(139,92,246,0.1)]",
                    selectedLang === lang ? "text-[#a78bfa] bg-[rgba(139,92,246,0.08)]" : "text-foreground"
                  )}
                >
                  {lang}
                </button>
              ))}
            </div>
          )}
        </div>

        <div className="h-4 w-px bg-[rgba(255,255,255,0.08)]" />

        <span className="text-[10px] text-muted-foreground font-mono">{lineCount} lines</span>

        <div className="ml-auto flex items-center gap-2">
          {/* AI inline completion indicator */}
          {generationState === "generating" && (
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[rgba(139,92,246,0.1)] border border-[rgba(139,92,246,0.2)]">
              <Sparkle size={10} className="text-[#8b5cf6] animate-spin" style={{ animationDuration: "1.5s" }} />
              <span className="text-[10px] text-[#8b5cf6] font-mono">AI completing…</span>
            </div>
          )}
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.08)] text-xs text-muted-foreground hover:text-foreground hover:border-[rgba(139,92,246,0.2)] transition-all"
          >
            {copied ? (
              <>
                <Check size={12} className="text-[#7fffd4]" />
                <span className="text-[#7fffd4]">Copied</span>
              </>
            ) : (
              <>
                <Copy size={12} />
                Copy
              </>
            )}
          </button>
        </div>
      </div>

      {/* Code Editor */}
      <div className="flex-1 overflow-auto relative">
        {generationState === "generating" ? (
          <div className="p-6 space-y-1.5">
            {Array.from({ length: 35 }).map((_, i) => (
              <div key={i} className="flex gap-4 items-center">
                <span className="text-[rgba(255,255,255,0.15)] font-mono text-xs w-7 text-right shrink-0">
                  {i + 1}
                </span>
                <div
                  className="h-3.5 rounded shimmer"
                  style={{
                    width: `${30 + Math.sin(i * 0.7) * 40 + Math.random() * 20}%`,
                    animationDelay: `${i * 0.04}s`,
                    opacity: i < 20 ? 1 : (35 - i) / 15,
                  }}
                />
              </div>
            ))}
            {/* Cursor blink at end */}
            <div className="flex gap-4 items-center">
              <span className="text-[rgba(255,255,255,0.15)] font-mono text-xs w-7 text-right shrink-0">36</span>
              <div className="w-2 h-4 bg-[#8b5cf6] animate-pulse rounded-sm" />
            </div>
          </div>
        ) : (
          <div className="p-4 font-mono text-xs bg-transparent">
            {highlight(code, selectedLang)}
            {/* Blinking cursor at end of last visible line */}
          </div>
        )}
        {/* Syntax glow overlay */}
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_80%_60%_at_0%_0%,rgba(139,92,246,0.03)_0%,transparent_60%)]" />
      </div>

      {/* AI Completion Bar */}
      <div className="px-5 py-3 border-t border-[rgba(139,92,246,0.1)] bg-[rgba(10,10,15,0.3)]">
        <div className="flex items-center gap-2 flex-wrap">
          <div className="flex items-center gap-1.5 text-[10px] text-[#ffd700] font-mono shrink-0">
            <Lightning size={11} weight="fill" />
            Generate:
          </div>
          {aiCompletions.map((c) => (
            <button
              key={c}
              onClick={() => setSelectedPrompt(c)}
              className={cn(
                "px-2.5 py-1 rounded-full text-[11px] border transition-all duration-200",
                selectedPrompt === c
                  ? "bg-[rgba(139,92,246,0.2)] border-[rgba(139,92,246,0.4)] text-[#a78bfa]"
                  : "bg-[rgba(255,255,255,0.03)] border-[rgba(255,255,255,0.08)] text-muted-foreground hover:text-foreground hover:border-[rgba(139,92,246,0.2)]"
              )}
            >
              {c}
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}
