/**
 * Narrative Plotting and Beat Sheet Templates
 * Frameworks for world-class novel plotting: Save the Cat, 10 Gates, Hero's Journey, Story Circle
 */

import type { NarrativeStructure } from './types';

export const NARRATIVE_STRUCTURES: Record<string, NarrativeStructure> = {
  'save-the-cat': {
    id: 'save-the-cat',
    name: 'Save the Cat! Novel Beat Sheet',
    description: '15-beat classic narrative rhythm by Blake Snyder & Jessica Brody',
    beats: [
      {
        id: 'stc-1',
        beatName: 'Opening Image',
        act: 'Act I',
        targetPercent: 1,
        description: 'A visual snapshot of the protagonist and their flawed "before" world.',
        guidingQuestion: 'What does the character’s ordinary world look like, and what internal lack is visible?',
        examples: 'Kael chiseling stone on the docks of Port Oakhaven, dreaming of the academies.',
      },
      {
        id: 'stc-2',
        beatName: 'Theme Stated',
        act: 'Act I',
        targetPercent: 5,
        description: 'A subtle statement by someone else hinting at what the hero must learn.',
        guidingQuestion: 'What universal truth does the story argue, which the hero currently rejects?',
        examples: 'Master Theron: "Strength is not how many elements you hold, but what you protect with them."',
      },
      {
        id: 'stc-3',
        beatName: 'Set-Up',
        act: 'Act I',
        targetPercent: 10,
        description: 'Exploring the hero’s status quo, their wound, mask, and primary relationships.',
        guidingQuestion: 'What are the 6 things that need fixing in the hero’s life?',
        examples: 'Kael concealing his five-element resonance while working to pay off his guild debt.',
      },
      {
        id: 'stc-4',
        beatName: 'Catalyst / Inciting Incident',
        act: 'Act I',
        targetPercent: 12,
        description: 'A life-altering event breaks the status quo. No returning to the old life.',
        guidingQuestion: 'What disruptive force shatters the hero’s ordinary world?',
        examples: 'The storm surge awakens ancient glyphs beneath the quay; Kael is discovered by the High Luminary.',
      },
      {
        id: 'stc-5',
        beatName: 'Debate',
        act: 'Act I',
        targetPercent: 20,
        description: 'Doubt, hesitation, resistance. The hero questions if they can take the leap.',
        guidingQuestion: 'What fears or stakes make the hero hesitate before accepting the call?',
        examples: 'Kael fears he will be executed as a heretic or lose his sister if he goes to the capital.',
      },
      {
        id: 'stc-6',
        beatName: 'Break into Two',
        act: 'Act II-A',
        targetPercent: 25,
        description: 'The hero makes an active choice to enter the unfamiliar upside-down world.',
        guidingQuestion: 'What concrete threshold does the hero cross into the new world?',
        examples: 'Kael boards the Starlight Sky-Caravel headed for the Three Academies.',
      },
      {
        id: 'stc-7',
        beatName: 'B Story',
        act: 'Act II-A',
        targetPercent: 30,
        description: 'Introduction of the key relationship/mentor/rival who carries the spiritual theme.',
        guidingQuestion: 'Who represents the spiritual journey and challenges the hero’s worldview?',
        examples: 'Meeting Sable, an exiled Gate-Touched rogue who questions Academy dogma.',
      },
      {
        id: 'stc-8',
        beatName: 'Fun and Games (Promise of the Premise)',
        act: 'Act II-A',
        targetPercent: 50,
        description: 'The core entertainment of the book: trials, training, initial victories.',
        guidingQuestion: 'What scenes deliver the trailer moments the reader bought the book for?',
        examples: 'Joint Academy trials, elemental duels, discovering secret chambers beneath the Spire.',
      },
      {
        id: 'stc-9',
        beatName: 'Midpoint',
        act: 'Act II-A',
        targetPercent: 50,
        description: 'A false victory or false defeat that raises stakes from wanting to needing.',
        guidingQuestion: 'What major revelation or public event shifts the story from passive to active?',
        examples: 'Kael wins the First Triennium, but the victory reveals the seal on the Abyssal Gate is cracking.',
      },
      {
        id: 'stc-10',
        beatName: 'Bad Guys Close In',
        act: 'Act II-B',
        targetPercent: 62,
        description: 'External opposition mounts; internal flaws fracture alliances.',
        guidingQuestion: 'How do internal distrust and external antagonists squeeze the hero?',
        examples: 'The Inquisitors discover Sable’s past; rival students sabotage Kael’s bond with the Godbeast.',
      },
      {
        id: 'stc-11',
        beatName: 'All Is Lost',
        act: 'Act II-B',
        targetPercent: 75,
        description: 'The lowest point. The scent of death. The old way of living is completely dead.',
        guidingQuestion: 'What total collapse or tragic loss strips away the hero’s ego/mask?',
        examples: 'The Luminary is assassinated, the Academies are locked down, and Kael is framed.',
      },
      {
        id: 'stc-12',
        beatName: 'Dark Night of the Soul',
        act: 'Act II-B',
        targetPercent: 80,
        description: 'Processing the loss. The hero admits their wound and embraces the Truth.',
        guidingQuestion: 'What epiphany bridges the hero from despair to their ultimate realization?',
        examples: 'In the dungeon beneath the Starweave Spire, Kael realizes he cannot save the realm alone.',
      },
      {
        id: 'stc-13',
        beatName: 'Break into Three',
        act: 'Act III',
        targetPercent: 85,
        description: 'A new synthesis emerges. The hero combines the old skill with the new spiritual truth.',
        guidingQuestion: 'What new plan integrates the theme to confront the ultimate obstacle?',
        examples: 'Kael rallies the outcasts from all three academies to forge a unified resonance.',
      },
      {
        id: 'stc-14',
        beatName: 'Finale',
        act: 'Act III',
        targetPercent: 95,
        description: 'Executing the plan, confronting the antagonist, resolving the high-stakes conflict.',
        guidingQuestion: 'How does the climax test the hero’s internal transformation and save the day?',
        examples: 'The battle at the Abyss Gate where Kael uses compassion instead of raw destructive force.',
      },
      {
        id: 'stc-15',
        beatName: 'Final Image',
        act: 'Act III',
        targetPercent: 100,
        description: 'Mirror to the Opening Image. Demonstrates the permanent transformation.',
        guidingQuestion: 'What visual shows how fundamentally the hero and world have changed?',
        examples: 'Kael standing on the open plaza, stone walls replaced by bridges of living starlight.',
      },
    ],
  },
  'ten-gates': {
    id: 'ten-gates',
    name: 'The Ten Gates Transcendent Spine',
    description: 'Arcanean progression structure from Foundation to Source & Unity',
    beats: [
      {
        id: 'gate-1',
        beatName: 'Gate 1: Foundation (Earth / 174 Hz)',
        act: 'Act I: Awakening',
        targetPercent: 10,
        description: 'Grounding, survival, identity roots, the physical constraint of the mortal plane.',
        guidingQuestion: 'What physical world boundary anchors the protagonist?',
        examples: 'The apprentice surviving the quarry collapse.',
      },
      {
        id: 'gate-2',
        beatName: 'Gate 2: Flow (Water / 285 Hz)',
        act: 'Act I: Awakening',
        targetPercent: 20,
        description: 'Emotional awakening, adaptability, desires, the dissolution of rigid barriers.',
        guidingQuestion: 'What emotional current sweeps the character into uncharted waters?',
        examples: 'Navigating the mysterious oceanic currents of the Sunken Spire.',
      },
      {
        id: 'gate-3',
        beatName: 'Gate 3: Fire (Solar / 396 Hz)',
        act: 'Act II: The Crucible',
        targetPercent: 30,
        description: 'Willpower, confrontation, ambition, direct friction against fate and authority.',
        guidingQuestion: 'What ignited challenge demands raw courage and decisive action?',
        examples: 'Facing the Dragon Crucible trial.',
      },
      {
        id: 'gate-4',
        beatName: 'Gate 4: Heart (Air / 417 Hz)',
        act: 'Act II: The Crucible',
        targetPercent: 40,
        description: 'Compassion, forgiveness, the vulnerability of true connection and sacrifice.',
        guidingQuestion: 'Where must compassion overcome vengeance?',
        examples: 'Spared enemy becomes an irreplaceable companion.',
      },
      {
        id: 'gate-5',
        beatName: 'Gate 5: Voice (Ether / 528 Hz)',
        act: 'Act II: The Crucible',
        targetPercent: 50,
        description: 'Truth, expression, breaking the silence, uttering the unvarnished reality.',
        guidingQuestion: 'What dangerous truth must be spoken in front of the Grand Council?',
        examples: 'Unmasking the corruption within the Luminary order.',
      },
      {
        id: 'gate-6',
        beatName: 'Gate 6: Sight (Light / 639 Hz)',
        act: 'Act II: The Crucible',
        targetPercent: 60,
        description: 'Intuition, vision, seeing past illusion, piercing the veil of deception.',
        guidingQuestion: 'What ancient illusion is shattered upon opening the Inner Eye?',
        examples: 'Glimpsing the true geometry of the universe beyond the physical stars.',
      },
      {
        id: 'gate-7',
        beatName: 'Gate 7: Crown (Cosmic / 741 Hz)',
        act: 'Act III: Ascension',
        targetPercent: 75,
        description: 'Wisdom, metacognition, sovereignty, accepting the weight of leadership.',
        guidingQuestion: 'How does the protagonist step into their higher authority without tyranny?',
        examples: 'Refusing the crown of domination to become a servant of the light.',
      },
      {
        id: 'gate-8',
        beatName: 'Gate 8: Starweave (Void Resonance / 852 Hz)',
        act: 'Act III: Ascension',
        targetPercent: 85,
        description: 'Cross-dimensional synthesis, weaving destiny threads, quantum entanglement.',
        guidingQuestion: 'How are severed timelines and fractured souls woven into a single destiny?',
        examples: 'Binding disparate elements into the cosmic tapestry.',
      },
      {
        id: 'gate-9',
        beatName: 'Gate 9: Source (Pure Light / 963 Hz)',
        act: 'Act III: Ascension',
        targetPercent: 95,
        description: 'Transcendence, origin, direct communion with primordial creation force.',
        guidingQuestion: 'What ego must be dissolved in the presence of pure creation?',
        examples: 'Entering the heart of Shinkami to reboot the planetary mana field.',
      },
      {
        id: 'gate-10',
        beatName: 'Gate 10: Unity (Non-Dual Omnipresence)',
        act: 'Act III: Epilogue',
        targetPercent: 100,
        description: 'The complete circle: the creator, creation, and witness are unified.',
        guidingQuestion: 'What new epoch begins when all ten gates resonate in perfect harmony?',
        examples: 'The realm renewed; the apprentice returns as guardian of the living weave.',
      },
    ],
  },
};
