/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-expressions, @typescript-eslint/ban-ts-comment, @typescript-eslint/no-require-imports, @typescript-eslint/no-unsafe-function-type, react-hooks/exhaustive-deps, react-hooks/set-state-in-effect, react-hooks/rules-of-hooks, react-hooks/purity, react-hooks/refs, react-hooks/static-components, react-hooks/immutability, react-hooks/preserve-manual-memoization, jsx-a11y/alt-text, @next/next/no-img-element, @next/next/no-html-link-for-pages, react/no-unescaped-entities */
// ---------------------------------------------------------------------------
// create-templates.ts — Static mock data for the Create Hub template gallery.
// No imports needed — pure data. Safe to import from client or server.
// ---------------------------------------------------------------------------

import type { TemplateCardProps } from "@/components/premium/template-card";

export interface TemplateEntry extends TemplateCardProps {
  category: "world" | "character" | "story" | "agent" | "music" | "image";
}

export const TEMPLATE_DATA: TemplateEntry[] = [
  // --- Worlds ---
  {
    category: "world",
    title: "The Shardlands",
    type: "world",
    subtitle: "Fractured reality, crystal storms, six rival factions",
    previewGradient: "from-[var(--arc-brand-atlantean-teal)]/20 via-[var(--arc-brand-cosmic-blue)]/30 to-[var(--arc-brand-cosmic-blue)]/40",
    stats: [{ label: "used", value: "3.4K" }, { label: "chars", value: "42" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    badge: "Popular",
    href: "/worlds/create",
    isPremium: false,
    isNew: false,
  },
  {
    category: "world",
    title: "Tidesong Archipelago",
    type: "world",
    subtitle: "Ocean-realm, living coral cities, tidal magic system",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/40 via-[var(--arc-brand-cosmic-blue)]/30 to-[var(--arc-brand-atlantean-teal)]/20",
    stats: [{ label: "used", value: "1.8K" }, { label: "chars", value: "29" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    href: "/worlds/create",
    isNew: true,
  },
  {
    category: "world",
    title: "Ash & Ember",
    type: "world",
    subtitle: "Post-volcanic empire, fire-priests, obsidian fortresses",
    previewGradient: "from-[var(--arc-fire)]/30 via-[var(--arc-earth)]/40 to-[var(--arc-cosmic-void)]/50",
    stats: [{ label: "used", value: "2.1K" }, { label: "chars", value: "35" }],
    accentColor: "var(--arc-fire)",
    badge: "Trending",
    href: "/worlds/create",
  },
  {
    category: "world",
    title: "Verdant Dominion",
    type: "world",
    subtitle: "Living forest empire, druid councils, ancient root-networks",
    previewGradient: "from-[var(--arc-cosmic-void)]/40 via-[var(--arc-cosmic-void)]/30 to-[var(--arc-cosmic-void)]/50",
    stats: [{ label: "used", value: "980" }, { label: "chars", value: "21" }],
    accentColor: "var(--arc-wind)",
    href: "/worlds/create",
    isPremium: true,
  },
  // --- Sci-fi worlds ---
  {
    category: "world",
    title: "Orbital Nine",
    type: "world",
    subtitle: "Space station politics, nine factions, zero-g combat",
    previewGradient: "from-[var(--arc-cosmic-void)]/60 via-[var(--arc-cosmic-void)]/40 to-[var(--arc-void)]/20",
    stats: [{ label: "used", value: "4.2K" }, { label: "chars", value: "55" }],
    accentColor: "var(--arc-void)",
    badge: "Popular",
    href: "/worlds/create",
  },
  {
    category: "world",
    title: "Belt Sovereign",
    type: "world",
    subtitle: "Asteroid belt miner clans, corp war, scarcity magic",
    previewGradient: "from-[var(--arc-cosmic-void)]/60 via-[var(--arc-cosmic-void)]/50 to-[var(--arc-brand-arcanean-gold)]/10",
    stats: [{ label: "used", value: "670" }, { label: "chars", value: "18" }],
    accentColor: "var(--arc-brand-arcanean-gold)",
    href: "/worlds/create",
    isNew: true,
  },
  // --- Mystery worlds ---
  {
    category: "world",
    title: "The Velvet Unknown",
    type: "world",
    subtitle: "1930s occult city, glamour as currency, five hidden societies",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/40 via-[var(--arc-cosmic-void)]/50 to-[var(--arc-earth)]/30",
    stats: [{ label: "used", value: "1.5K" }, { label: "chars", value: "33" }],
    accentColor: "var(--arc-void)",
    href: "/worlds/create",
    isPremium: true,
  },
  {
    category: "world",
    title: "Solvent Protocol",
    type: "world",
    subtitle: "Cyberpunk noir, memory black market, deep-net arcane code",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/40 via-[var(--arc-cosmic-void)]/60 to-[var(--arc-brand-atlantean-teal)]/15",
    stats: [{ label: "used", value: "2.9K" }, { label: "chars", value: "47" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    badge: "Trending",
    href: "/worlds/create",
  },
  // --- Characters ---
  {
    category: "character",
    title: "Morally Grey Villain",
    type: "character",
    subtitle: "Three-act motivation arc, dual morality, redemption thread",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/40 via-[var(--arc-cosmic-void)]/60 to-[var(--arc-fire)]/15",
    stats: [{ label: "used", value: "6.1K" }, { label: "scenes", value: "12" }],
    accentColor: "var(--arc-fire)",
    badge: "Popular",
    href: "/worlds/create?tab=character",
  },
  {
    category: "character",
    title: "Reluctant Hero",
    type: "character",
    subtitle: "Refusal arc, mentor bond, flaw-driven growth progression",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/30 via-[var(--arc-brand-cosmic-blue)]/40 to-[var(--arc-brand-atlantean-teal)]/10",
    stats: [{ label: "used", value: "4.8K" }, { label: "scenes", value: "10" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    href: "/worlds/create?tab=character",
    isNew: false,
  },
  {
    category: "character",
    title: "Cosmic Trickster",
    type: "character",
    subtitle: "Chaos-aligned, riddle speech, unpredictable loyalty",
    previewGradient: "from-[var(--arc-brand-arcanean-gold)]/15 via-[var(--arc-earth)]/30 to-[var(--arc-brand-cosmic-blue)]/40",
    stats: [{ label: "used", value: "2.3K" }, { label: "scenes", value: "8" }],
    accentColor: "var(--arc-brand-arcanean-gold)",
    href: "/worlds/create?tab=character",
    isPremium: true,
  },
  {
    category: "character",
    title: "The Exiled Scholar",
    type: "character",
    subtitle: "Forbidden knowledge, hunted arc, complex loyalty map",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/50 via-[var(--arc-brand-cosmic-blue)]/30 to-[var(--arc-brand-cosmic-blue)]/20",
    stats: [{ label: "used", value: "1.1K" }, { label: "scenes", value: "9" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    href: "/worlds/create?tab=character",
    isNew: true,
  },
  // --- Stories ---
  {
    category: "story",
    title: "Hollow Oath",
    type: "story",
    subtitle: "Broken promise drives the arc, three timelines, morally resonant",
    previewGradient: "from-[var(--arc-cosmic-void)]/60 via-[var(--arc-cosmic-void)]/50 to-[var(--arc-brand-atlantean-teal)]/10",
    stats: [{ label: "used", value: "780" }, { label: "acts", value: "3" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    href: "/chat?mode=story",
    isNew: true,
  },
  {
    category: "story",
    title: "Neon Detective",
    type: "story",
    subtitle: "Cyberpunk noir mystery, corrupt city, unreliable narrator",
    previewGradient: "from-[var(--arc-cosmic-void)]/70 via-[var(--arc-brand-cosmic-blue)]/30 to-[var(--arc-fire)]/15",
    stats: [{ label: "used", value: "3.2K" }, { label: "acts", value: "5" }],
    accentColor: "var(--arc-fire)",
    badge: "Popular",
    href: "/chat?mode=story",
  },
  {
    category: "story",
    title: "Three-Act Fantasy",
    type: "story",
    subtitle: "Classic hero journey, mentor/shadow pairing, resolution gate",
    previewGradient: "from-[var(--arc-void)]/30 via-[var(--arc-brand-cosmic-blue)]/40 to-[var(--arc-brand-arcanean-gold)]/10",
    stats: [{ label: "used", value: "5.6K" }, { label: "acts", value: "3" }],
    accentColor: "var(--arc-void)",
    href: "/chat?mode=story",
    isPremium: false,
  },
  {
    category: "story",
    title: "Sci-Fi Thriller",
    type: "story",
    subtitle: "First contact, paranoia escalation, hard-sci-fi grounding",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/50 via-[var(--arc-brand-cosmic-blue)]/30 to-[var(--arc-brand-atlantean-teal)]/10",
    stats: [{ label: "used", value: "2.0K" }, { label: "acts", value: "4" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    href: "/chat?mode=story",
    isNew: true,
  },
  // --- Agents ---
  {
    category: "agent",
    title: "World Lore Keeper",
    type: "agent",
    subtitle: "Tracks canon, resolves contradictions, builds lore graph",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/40 via-[var(--arc-brand-cosmic-blue)]/50 to-[var(--arc-brand-cosmic-blue)]/20",
    stats: [{ label: "used", value: "890" }, { label: "tools", value: "7" }],
    accentColor: "var(--arc-void)",
    href: "/agents/create",
    isNew: true,
  },
  {
    category: "agent",
    title: "Story Editor",
    type: "agent",
    subtitle: "Pacing analysis, prose polish, voice consistency reviewer",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/50 via-[var(--arc-brand-cosmic-blue)]/30 to-[var(--arc-brand-atlantean-teal)]/10",
    stats: [{ label: "used", value: "1.4K" }, { label: "tools", value: "5" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    href: "/agents/create",
  },
  // --- Music ---
  {
    category: "music",
    title: "Epic Orchestral Theme",
    type: "music",
    subtitle: "Hero arc, full strings, brass resolve, battle swell",
    previewGradient: "from-[var(--arc-earth)]/40 via-[var(--arc-earth)]/30 to-[var(--arc-brand-arcanean-gold)]/15",
    stats: [{ label: "used", value: "2.7K" }, { label: "mins", value: "4" }],
    accentColor: "var(--arc-brand-arcanean-gold)",
    badge: "Popular",
    href: "/music",
  },
  {
    category: "music",
    title: "Ambient World Score",
    type: "music",
    subtitle: "Atmospheric, layered pads, slow evolution, world identity",
    previewGradient: "from-[var(--arc-brand-cosmic-blue)]/30 via-[var(--arc-brand-cosmic-blue)]/30 to-[var(--arc-brand-atlantean-teal)]/10",
    stats: [{ label: "used", value: "1.2K" }, { label: "mins", value: "6" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    href: "/music",
    isNew: true,
  },
  // --- Images ---
  {
    category: "image",
    title: "Fantasy Portrait",
    type: "image",
    subtitle: "Character art, cinematic lighting, detailed costume guide",
    previewGradient: "from-[var(--arc-void)]/30 via-[var(--arc-brand-cosmic-blue)]/40 to-[var(--arc-brand-arcanean-gold)]/10",
    stats: [{ label: "used", value: "8.3K" }, { label: "styles", value: "6" }],
    accentColor: "var(--arc-void)",
    badge: "Popular",
    href: "/imagine",
  },
  {
    category: "image",
    title: "World Map Art",
    type: "image",
    subtitle: "Cartographic fantasy, hand-drawn aesthetic, continent layout",
    previewGradient: "from-[var(--arc-cosmic-void)]/40 via-[var(--arc-cosmic-void)]/50 to-[var(--arc-brand-arcanean-gold)]/10",
    stats: [{ label: "used", value: "3.9K" }, { label: "styles", value: "4" }],
    accentColor: "var(--arc-wind)",
    href: "/imagine",
    isPremium: true,
  },
];

export const CATEGORY_FILTERS = [
  { id: "all", label: "All" },
  { id: "world", label: "Worlds" },
  { id: "character", label: "Characters" },
  { id: "story", label: "Stories" },
  { id: "agent", label: "Agents" },
  { id: "music", label: "Music" },
  { id: "image", label: "Images" },
] as const;

export type CategoryFilterId = (typeof CATEGORY_FILTERS)[number]["id"];

// Quick-start creation types shown above the template gallery
export const QUICK_START_ITEMS = [
  {
    id: "world",
    label: "Start a World",
    symbol: "W",
    description: "Blank canvas",
    href: "/worlds/create",
    gradient: "from-[var(--arc-brand-atlantean-teal)]/20 via-[var(--arc-brand-cosmic-blue)]/15 to-[var(--arc-brand-atlantean-teal)]/5",
    glowColor: "var(--arc-brand-atlantean-teal)",
    accentColor: "var(--arc-brand-atlantean-teal)",
  },
  {
    id: "character",
    label: "Start a Character",
    symbol: "C",
    description: "Blank canvas",
    href: "/worlds/create?tab=character",
    gradient: "from-[var(--arc-brand-atlantean-teal)]/15 via-[var(--arc-brand-atlantean-teal)]/10 to-[var(--arc-brand-cosmic-blue)]/5",
    glowColor: "var(--arc-brand-atlantean-teal)",
    accentColor: "var(--arc-brand-atlantean-teal)",
  },
  {
    id: "story",
    label: "Start a Story",
    symbol: "S",
    description: "Blank canvas",
    href: "/chat?mode=story",
    gradient: "from-[var(--arc-brand-arcanean-gold)]/15 via-[var(--arc-earth)]/10 to-[var(--arc-cosmic-void)]/20",
    glowColor: "var(--arc-brand-arcanean-gold)",
    accentColor: "var(--arc-brand-arcanean-gold)",
  },
  {
    id: "agent",
    label: "Build an Agent",
    symbol: "A",
    description: "Blank canvas",
    href: "/agents/create",
    gradient: "from-[var(--arc-void)]/15 via-[var(--arc-brand-cosmic-blue)]/10 to-[var(--arc-cosmic-void)]/20",
    glowColor: "var(--arc-void)",
    accentColor: "var(--arc-void)",
  },
  {
    id: "music",
    label: "Generate Music",
    symbol: "M",
    description: "Blank canvas",
    href: "/music",
    gradient: "from-[var(--arc-fire)]/15 via-[var(--arc-earth)]/10 to-[var(--arc-cosmic-void)]/20",
    glowColor: "var(--arc-fire)",
    accentColor: "var(--arc-void)",
  },
  {
    id: "image",
    label: "Generate Art",
    symbol: "I",
    description: "Blank canvas",
    href: "/imagine",
    gradient: "from-[var(--arc-brand-atlantean-teal)]/15 via-[var(--arc-brand-cosmic-blue)]/10 to-[var(--arc-cosmic-void)]/20",
    glowColor: "var(--arc-brand-atlantean-teal)",
    accentColor: "var(--arc-text-primary)",
  },
] as const;

// Recent creations mock — placeholder until auth is wired
export const RECENT_MOCK = [
  {
    title: "The Shattered Meridian",
    type: "world" as const,
    subtitle: "Your world · 3 hours ago",
    previewGradient: "from-[var(--arc-brand-atlantean-teal)]/15 via-[var(--arc-brand-cosmic-blue)]/25 to-[var(--arc-brand-cosmic-blue)]/25",
    stats: [{ label: "chars", value: "7" }, { label: "lore", value: "12" }],
    accentColor: "var(--arc-brand-atlantean-teal)",
    href: "/worlds/create",
    badge: "Draft",
  },
  {
    title: "Veyra Solcroft",
    type: "character" as const,
    subtitle: "Your character · Yesterday",
    previewGradient: "from-[var(--arc-brand-arcanean-gold)]/15 via-[var(--arc-earth)]/20 to-[var(--arc-cosmic-void)]/30",
    stats: [{ label: "scenes", value: "4" }],
    accentColor: "var(--arc-brand-arcanean-gold)",
    href: "/worlds/create?tab=character",
    badge: "Draft",
  },
  {
    title: "The Iron Covenant",
    type: "story" as const,
    subtitle: "Your story · 2 days ago",
    previewGradient: "from-[var(--arc-cosmic-void)]/60 via-[var(--arc-cosmic-void)]/50 to-[var(--arc-fire)]/10",
    stats: [{ label: "acts", value: "2" }, { label: "scenes", value: "8" }],
    accentColor: "var(--arc-fire)",
    href: "/chat?context=iron-covenant",
  },
  {
    title: "Obsidian Soundscape",
    type: "music" as const,
    subtitle: "Your track · 3 days ago",
    previewGradient: "from-[var(--arc-cosmic-void)]/60 via-[var(--arc-cosmic-void)]/70 to-[var(--arc-brand-arcanean-gold)]/10",
    stats: [{ label: "mins", value: "3.2" }],
    accentColor: "var(--arc-brand-arcanean-gold)",
    href: "/music",
  },
];
