// ---------------------------------------------------------------------------
// create-templates.ts — Static mock data for the Create Hub template gallery.
// No imports needed — pure data. Safe to import from client or server.
// ---------------------------------------------------------------------------

import type { TemplateCardProps } from "@/components/premium/template-card";

export interface TemplateEntry extends TemplateCardProps {
  category: "world" | "character" | "story" | "agent" | "music" | "image";
}

export const TEMPLATE_DATA: TemplateEntry[] = [
  // --- Worlds ---
  {
    category: "world",
    title: "The Shardlands",
    type: "world",
    subtitle: "Fractured reality, crystal storms, six rival factions",
    previewGradient: "from-[#7fffd4]/20 via-[#0d47a1]/30 to-[#4a148c]/40",
    stats: [{ label: "used", value: "3.4K" }, { label: "chars", value: "42" }],
    accentColor: "#7fffd4",
    badge: "Popular",
    href: "/worlds/templates/shardlands",
    isPremium: false,
    isNew: false,
  },
  {
    category: "world",
    title: "Tidesong Archipelago",
    type: "world",
    subtitle: "Ocean-realm, living coral cities, tidal magic system",
    previewGradient: "from-[#0d47a1]/40 via-[#006064]/30 to-[#00bcd4]/20",
    stats: [{ label: "used", value: "1.8K" }, { label: "chars", value: "29" }],
    accentColor: "#00bcd4",
    href: "/worlds/templates/tidesong-archipelago",
    isNew: true,
  },
  {
    category: "world",
    title: "Ash & Ember",
    type: "world",
    subtitle: "Post-volcanic empire, fire-priests, obsidian fortresses",
    previewGradient: "from-[#ef4444]/30 via-[#7c2d12]/40 to-[#1c1917]/50",
    stats: [{ label: "used", value: "2.1K" }, { label: "chars", value: "35" }],
    accentColor: "#f97316",
    badge: "Trending",
    href: "/worlds/templates/ash-ember",
  },
  {
    category: "world",
    title: "Verdant Dominion",
    type: "world",
    subtitle: "Living forest empire, druid councils, ancient root-networks",
    previewGradient: "from-[#14532d]/40 via-[#166534]/30 to-[#052e16]/50",
    stats: [{ label: "used", value: "980" }, { label: "chars", value: "21" }],
    accentColor: "#22c55e",
    href: "/worlds/templates/verdant-dominion",
    isPremium: true,
  },
  // --- Sci-fi worlds ---
  {
    category: "world",
    title: "Orbital Nine",
    type: "world",
    subtitle: "Space station politics, nine factions, zero-g combat",
    previewGradient: "from-[#0f172a]/60 via-[#1e293b]/40 to-[#7c3aed]/20",
    stats: [{ label: "used", value: "4.2K" }, { label: "chars", value: "55" }],
    accentColor: "#a855f7",
    badge: "Popular",
    href: "/worlds/templates/orbital-nine",
  },
  {
    category: "world",
    title: "Belt Sovereign",
    type: "world",
    subtitle: "Asteroid belt miner clans, corp war, scarcity magic",
    previewGradient: "from-[#1c1917]/60 via-[#292524]/50 to-[#ffd700]/10",
    stats: [{ label: "used", value: "670" }, { label: "chars", value: "18" }],
    accentColor: "#ffd700",
    href: "/worlds/templates/belt-sovereign",
    isNew: true,
  },
  // --- Mystery worlds ---
  {
    category: "world",
    title: "The Velvet Unknown",
    type: "world",
    subtitle: "1930s occult city, glamour as currency, five hidden societies",
    previewGradient: "from-[#4c1d95]/40 via-[#1f2937]/50 to-[#831843]/30",
    stats: [{ label: "used", value: "1.5K" }, { label: "chars", value: "33" }],
    accentColor: "#c084fc",
    href: "/worlds/templates/velvet-unknown",
    isPremium: true,
  },
  {
    category: "world",
    title: "Solvent Protocol",
    type: "world",
    subtitle: "Cyberpunk noir, memory black market, deep-net arcane code",
    previewGradient: "from-[#0d47a1]/40 via-[#0f172a]/60 to-[#00bcd4]/15",
    stats: [{ label: "used", value: "2.9K" }, { label: "chars", value: "47" }],
    accentColor: "#38bdf8",
    badge: "Trending",
    href: "/worlds/templates/solvent-protocol",
  },
  // --- Characters ---
  {
    category: "character",
    title: "Morally Grey Villain",
    type: "character",
    subtitle: "Three-act motivation arc, dual morality, redemption thread",
    previewGradient: "from-[#4c1d95]/40 via-[#1f2937]/60 to-[#ef4444]/15",
    stats: [{ label: "used", value: "6.1K" }, { label: "scenes", value: "12" }],
    accentColor: "#ef4444",
    badge: "Popular",
    href: "/worlds/templates/char-grey-villain",
  },
  {
    category: "character",
    title: "Reluctant Hero",
    type: "character",
    subtitle: "Refusal arc, mentor bond, flaw-driven growth progression",
    previewGradient: "from-[#0d47a1]/30 via-[#1e40af]/40 to-[#7fffd4]/10",
    stats: [{ label: "used", value: "4.8K" }, { label: "scenes", value: "10" }],
    accentColor: "#7fffd4",
    href: "/worlds/templates/char-reluctant-hero",
    isNew: false,
  },
  {
    category: "character",
    title: "Cosmic Trickster",
    type: "character",
    subtitle: "Chaos-aligned, riddle speech, unpredictable loyalty",
    previewGradient: "from-[#ffd700]/15 via-[#92400e]/30 to-[#4c1d95]/40",
    stats: [{ label: "used", value: "2.3K" }, { label: "scenes", value: "8" }],
    accentColor: "#ffd700",
    href: "/worlds/templates/char-cosmic-trickster",
    isPremium: true,
  },
  {
    category: "character",
    title: "The Exiled Scholar",
    type: "character",
    subtitle: "Forbidden knowledge, hunted arc, complex loyalty map",
    previewGradient: "from-[#134e4a]/50 via-[#0f766e]/30 to-[#0d47a1]/20",
    stats: [{ label: "used", value: "1.1K" }, { label: "scenes", value: "9" }],
    accentColor: "#14b8a6",
    href: "/worlds/templates/char-exiled-scholar",
    isNew: true,
  },
  // --- Stories ---
  {
    category: "story",
    title: "Hollow Oath",
    type: "story",
    subtitle: "Broken promise drives the arc, three timelines, morally resonant",
    previewGradient: "from-[#1c1917]/60 via-[#27272a]/50 to-[#7fffd4]/10",
    stats: [{ label: "used", value: "780" }, { label: "acts", value: "3" }],
    accentColor: "#7fffd4",
    href: "/worlds/templates/story-hollow-oath",
    isNew: true,
  },
  {
    category: "story",
    title: "Neon Detective",
    type: "story",
    subtitle: "Cyberpunk noir mystery, corrupt city, unreliable narrator",
    previewGradient: "from-[#0f172a]/70 via-[#0d47a1]/30 to-[#ec4899]/15",
    stats: [{ label: "used", value: "3.2K" }, { label: "acts", value: "5" }],
    accentColor: "#ec4899",
    badge: "Popular",
    href: "/worlds/templates/story-neon-detective",
  },
  {
    category: "story",
    title: "Three-Act Fantasy",
    type: "story",
    subtitle: "Classic hero journey, mentor/shadow pairing, resolution gate",
    previewGradient: "from-[#7c3aed]/30 via-[#0d47a1]/40 to-[#ffd700]/10",
    stats: [{ label: "used", value: "5.6K" }, { label: "acts", value: "3" }],
    accentColor: "#c084fc",
    href: "/worlds/templates/story-three-act-fantasy",
    isPremium: false,
  },
  {
    category: "story",
    title: "Sci-Fi Thriller",
    type: "story",
    subtitle: "First contact, paranoia escalation, hard-sci-fi grounding",
    previewGradient: "from-[#0c4a6e]/50 via-[#0369a1]/30 to-[#7fffd4]/10",
    stats: [{ label: "used", value: "2.0K" }, { label: "acts", value: "4" }],
    accentColor: "#38bdf8",
    href: "/worlds/templates/story-scifi-thriller",
    isNew: true,
  },
  // --- Agents ---
  {
    category: "agent",
    title: "World Lore Keeper",
    type: "agent",
    subtitle: "Tracks canon, resolves contradictions, builds lore graph",
    previewGradient: "from-[#4c1d95]/40 via-[#2e1065]/50 to-[#0d47a1]/20",
    stats: [{ label: "used", value: "890" }, { label: "tools", value: "7" }],
    accentColor: "#a855f7",
    href: "/agents/templates/world-lore-keeper",
    isNew: true,
  },
  {
    category: "agent",
    title: "Story Editor",
    type: "agent",
    subtitle: "Pacing analysis, prose polish, voice consistency reviewer",
    previewGradient: "from-[#134e4a]/50 via-[#0f766e]/30 to-[#7fffd4]/10",
    stats: [{ label: "used", value: "1.4K" }, { label: "tools", value: "5" }],
    accentColor: "#14b8a6",
    href: "/agents/templates/story-editor",
  },
  // --- Music ---
  {
    category: "music",
    title: "Epic Orchestral Theme",
    type: "music",
    subtitle: "Hero arc, full strings, brass resolve, battle swell",
    previewGradient: "from-[#7c2d12]/40 via-[#92400e]/30 to-[#ffd700]/15",
    stats: [{ label: "used", value: "2.7K" }, { label: "mins", value: "4" }],
    accentColor: "#ffd700",
    badge: "Popular",
    href: "/music/templates/epic-orchestral",
  },
  {
    category: "music",
    title: "Ambient World Score",
    type: "music",
    subtitle: "Atmospheric, layered pads, slow evolution, world identity",
    previewGradient: "from-[#0d47a1]/30 via-[#0e7490]/30 to-[#7fffd4]/10",
    stats: [{ label: "used", value: "1.2K" }, { label: "mins", value: "6" }],
    accentColor: "#00bcd4",
    href: "/music/templates/ambient-world-score",
    isNew: true,
  },
  // --- Images ---
  {
    category: "image",
    title: "Fantasy Portrait",
    type: "image",
    subtitle: "Character art, cinematic lighting, detailed costume guide",
    previewGradient: "from-[#7c3aed]/30 via-[#4c1d95]/40 to-[#ffd700]/10",
    stats: [{ label: "used", value: "8.3K" }, { label: "styles", value: "6" }],
    accentColor: "#c084fc",
    badge: "Popular",
    href: "/imagine/templates/fantasy-portrait",
  },
  {
    category: "image",
    title: "World Map Art",
    type: "image",
    subtitle: "Cartographic fantasy, hand-drawn aesthetic, continent layout",
    previewGradient: "from-[#14532d]/40 via-[#064e3b]/50 to-[#ffd700]/10",
    stats: [{ label: "used", value: "3.9K" }, { label: "styles", value: "4" }],
    accentColor: "#22c55e",
    href: "/imagine/templates/world-map-art",
    isPremium: true,
  },
];

export const CATEGORY_FILTERS = [
  { id: "all", label: "All" },
  { id: "world", label: "Worlds" },
  { id: "character", label: "Characters" },
  { id: "story", label: "Stories" },
  { id: "agent", label: "Agents" },
  { id: "music", label: "Music" },
  { id: "image", label: "Images" },
] as const;

export type CategoryFilterId = (typeof CATEGORY_FILTERS)[number]["id"];

// Quick-start creation types shown above the template gallery
export const QUICK_START_ITEMS = [
  {
    id: "world",
    label: "Start a World",
    symbol: "W",
    description: "Blank canvas",
    href: "/worlds/create",
    gradient: "from-[#00bcd4]/20 via-[#0d47a1]/15 to-[#7fffd4]/5",
    glowColor: "#00bcd4",
    accentColor: "#7fffd4",
  },
  {
    id: "character",
    label: "Start a Character",
    symbol: "C",
    description: "Blank canvas",
    href: "/worlds/create?tab=character",
    gradient: "from-[#7fffd4]/15 via-[#00bcd4]/10 to-[#0d47a1]/5",
    glowColor: "#7fffd4",
    accentColor: "#7fffd4",
  },
  {
    id: "story",
    label: "Start a Story",
    symbol: "S",
    description: "Blank canvas",
    href: "/chat?mode=story",
    gradient: "from-[#f59e0b]/15 via-[#92400e]/10 to-[#1c1917]/20",
    glowColor: "#f59e0b",
    accentColor: "#fbbf24",
  },
  {
    id: "agent",
    label: "Build an Agent",
    symbol: "A",
    description: "Blank canvas",
    href: "/agents/create",
    gradient: "from-[#a855f7]/15 via-[#4c1d95]/10 to-[#0f172a]/20",
    glowColor: "#a855f7",
    accentColor: "#c084fc",
  },
  {
    id: "music",
    label: "Generate Music",
    symbol: "M",
    description: "Blank canvas",
    href: "/music",
    gradient: "from-[#ec4899]/15 via-[#be185d]/10 to-[#1f2937]/20",
    glowColor: "#ec4899",
    accentColor: "#f472b6",
  },
  {
    id: "image",
    label: "Generate Art",
    symbol: "I",
    description: "Blank canvas",
    href: "/imagine",
    gradient: "from-[#38bdf8]/15 via-[#0369a1]/10 to-[#0f172a]/20",
    glowColor: "#38bdf8",
    accentColor: "#7dd3fc",
  },
] as const;

// Recent creations mock — placeholder until auth is wired
export const RECENT_MOCK = [
  {
    title: "The Shattered Meridian",
    type: "world" as const,
    subtitle: "Your world · 3 hours ago",
    previewGradient: "from-[#7fffd4]/15 via-[#0d47a1]/25 to-[#4a148c]/25",
    stats: [{ label: "chars", value: "7" }, { label: "lore", value: "12" }],
    accentColor: "#7fffd4",
    href: "/worlds/shattered-meridian",
    badge: "Draft",
  },
  {
    title: "Veyra Solcroft",
    type: "character" as const,
    subtitle: "Your character · Yesterday",
    previewGradient: "from-[#f59e0b]/15 via-[#92400e]/20 to-[#0f172a]/30",
    stats: [{ label: "scenes", value: "4" }],
    accentColor: "#fbbf24",
    href: "/worlds/shattered-meridian/characters/veyra",
    badge: "Draft",
  },
  {
    title: "The Iron Covenant",
    type: "story" as const,
    subtitle: "Your story · 2 days ago",
    previewGradient: "from-[#1c1917]/60 via-[#292524]/50 to-[#ef4444]/10",
    stats: [{ label: "acts", value: "2" }, { label: "scenes", value: "8" }],
    accentColor: "#ef4444",
    href: "/chat?context=iron-covenant",
  },
  {
    title: "Obsidian Soundscape",
    type: "music" as const,
    subtitle: "Your track · 3 days ago",
    previewGradient: "from-[#1f2937]/60 via-[#111827]/70 to-[#ffd700]/10",
    stats: [{ label: "mins", value: "3.2" }],
    accentColor: "#ffd700",
    href: "/music",
  },
];
