// AUTO-GENERATED by @arcanea/orchestrator ecosystem:build.
// Do not edit by hand. Edit .arcanea/config/{repos.json,manifest.yaml} and re-run.

export type Layer = 'substrate' | 'product' | 'surface';
export type Gate = 'source' | 'form' | 'pattern' | 'voice' | 'vision' | 'story' | 'world' | 'soul' | 'unity' | 'mastery';
export type Hemisphere = 'arc' | 'nea' | 'seam';
export type Status = 'built' | 'shipped' | 'wip' | 'orphan' | 'sunset' | 'external';

export interface EcosystemNode {
  id: string;
  name: string;
  description: string;
  layer: Layer;
  gate: Gate;
  hemisphere: Hemisphere;
  status: Status;
  repo?: string;
  github?: string;
  publicUrl?: string;
  packageVersion?: string;
  lastCommitAt?: string;
  lastVerifiedAt: string;
  consumes: string[];
  consumedBy: string[];
  isExternal: boolean;
  owner?: string;
  links: Record<string, string>;
}

export interface EcosystemEdge {
  source: string;
  target: string;
  kind: 'consumes' | 'bridges' | 'routes' | 'references';
}

export const GENERATED_AT = "2026-05-31T10:07:23.762Z";

export const NODES: EcosystemNode[] = [
  {
    "id": "anthropic-sdk",
    "name": "Anthropic SDK",
    "description": "Claude Sonnet/Opus/Haiku via @anthropic-ai/sdk",
    "layer": "substrate",
    "gate": "source",
    "hemisphere": "seam",
    "status": "external",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [
      "author-council",
      "orchestrator",
      "surface-author"
    ],
    "isExternal": true,
    "links": {
      "docs": "https://docs.anthropic.com"
    }
  },
  {
    "id": "arcanea",
    "name": "arcanea",
    "description": "OSS monorepo - the open-source engine",
    "layer": "substrate",
    "gate": "source",
    "hemisphere": "seam",
    "status": "built",
    "repo": "packages/arcanea-cli",
    "github": "https://github.com/frankxai/arcanea",
    "publicUrl": "https://github.com/frankxai/arcanea",
    "packageVersion": "0.1.0",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://github.com/frankxai/arcanea"
    }
  },
  {
    "id": "arcanea-ai-app",
    "name": "arcanea-ai-app",
    "description": "Main platform - arcanea.ai production",
    "layer": "surface",
    "gate": "unity",
    "hemisphere": "seam",
    "status": "shipped",
    "repo": "frankxai/arcanea-ai-app",
    "github": "https://github.com/frankxai/arcanea-ai-app",
    "publicUrl": "https://arcanea.ai",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://arcanea.ai"
    }
  },
  {
    "id": "arcanea-claw",
    "name": "arcanea-claw",
    "description": "AI media engine (NanoClaw fork)",
    "layer": "product",
    "gate": "pattern",
    "hemisphere": "arc",
    "status": "orphan",
    "repo": "frankxai/arcanea-claw",
    "github": "https://github.com/frankxai/arcanea-claw",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcanea-code",
    "name": "arcanea-code",
    "description": "Guardian-powered coding CLI fork; consumes harness/substrate but is not the universal harness",
    "layer": "surface",
    "gate": "form",
    "hemisphere": "seam",
    "status": "shipped",
    "repo": "packages/vscode",
    "github": "https://github.com/frankxai/arcanea-code",
    "publicUrl": "https://github.com/frankxai/arcanea-code",
    "packageVersion": "0.3.0",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://github.com/frankxai/arcanea-code"
    }
  },
  {
    "id": "arcanea-flow",
    "name": "arcanea-flow",
    "description": "Multi-agent orchestration (claude-flow/ruflo fork)",
    "layer": "substrate",
    "gate": "pattern",
    "hemisphere": "seam",
    "status": "built",
    "repo": "frankxai/arcanea-flow",
    "github": "https://github.com/frankxai/arcanea-flow",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcanea-infogenius",
    "name": "arcanea-infogenius",
    "description": "Knowledge-first visual intelligence MCP",
    "layer": "substrate",
    "gate": "vision",
    "hemisphere": "seam",
    "status": "built",
    "repo": "frankxai/arcanea-infogenius",
    "github": "https://github.com/frankxai/arcanea-infogenius",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcanea-intelligence-os",
    "name": "arcanea-intelligence-os",
    "description": "Mythology-infused agent orchestration",
    "layer": "substrate",
    "gate": "unity",
    "hemisphere": "seam",
    "status": "built",
    "repo": "packages/aios",
    "github": "https://github.com/frankxai/arcanea-intelligence-os",
    "packageVersion": "0.2.2",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcanea-mcp",
    "name": "arcanea-mcp",
    "description": "Historical MCP infrastructure entry - verify URL/access/name before use",
    "layer": "product",
    "gate": "form",
    "hemisphere": "arc",
    "status": "orphan",
    "github": "https://github.com/frankxai/arcanea-mcp",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcanea-memory",
    "name": "arcanea-memory",
    "description": "Historical memory MCP entry - likely superseded or absorbed by Starlight Intelligence System",
    "layer": "product",
    "gate": "form",
    "hemisphere": "arc",
    "status": "orphan",
    "github": "https://github.com/frankxai/arcanea-memory",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcanea-mobile",
    "name": "arcanea-mobile",
    "description": "Mobile application (Flutter/Compose)",
    "layer": "product",
    "gate": "form",
    "hemisphere": "arc",
    "status": "orphan",
    "repo": "frankxai/arcanea-mobile",
    "github": "https://github.com/frankxai/arcanea-mobile",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcanea-onchain",
    "name": "arcanea-onchain",
    "description": "Economic layer and Guardian assets",
    "layer": "substrate",
    "gate": "source",
    "hemisphere": "seam",
    "status": "built",
    "repo": "frankxai/arcanea-onchain",
    "github": "https://github.com/frankxai/arcanea-onchain",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcanea-orchestrator",
    "name": "arcanea-orchestrator",
    "description": "Parallel AI coding agent orchestration runtime across repos and agent runtimes",
    "layer": "substrate",
    "gate": "unity",
    "hemisphere": "seam",
    "status": "built",
    "repo": "frankxai/arcanea-orchestrator",
    "github": "https://github.com/frankxai/arcanea-orchestrator",
    "publicUrl": "https://github.com/frankxai/arcanea-orchestrator",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://github.com/frankxai/arcanea-orchestrator"
    }
  },
  {
    "id": "arcanea-records",
    "name": "arcanea-records",
    "description": "Music studio - Suno integration, soundscapes",
    "layer": "product",
    "gate": "voice",
    "hemisphere": "arc",
    "status": "orphan",
    "repo": "frankxai/arcanea-records",
    "github": "https://github.com/frankxai/arcanea-records",
    "publicUrl": "https://github.com/frankxai/arcanea-records",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://github.com/frankxai/arcanea-records"
    }
  },
  {
    "id": "arcanea-vault",
    "name": "arcanea-vault",
    "description": "Browser extension and capture/export/provenance layer feeding Arcanea and SIS",
    "layer": "product",
    "gate": "form",
    "hemisphere": "arc",
    "status": "orphan",
    "repo": "frankxai/kura",
    "github": "https://github.com/frankxai/kura",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "arcaneabot",
    "name": "arcaneabot",
    "description": "Integration bot (moltbot fork)",
    "layer": "product",
    "gate": "form",
    "hemisphere": "arc",
    "status": "orphan",
    "repo": "moltbot/moltbot",
    "github": "https://github.com/moltbot/moltbot",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "author-council",
    "name": "@arcanea/author-council",
    "description": "10 author voices · 8 rosters · 4 deliberation modes · MCP server",
    "layer": "product",
    "gate": "soul",
    "hemisphere": "arc",
    "status": "built",
    "repo": "packages/author-council",
    "packageVersion": "0.1.0",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [
      "anthropic-sdk",
      "sis"
    ],
    "consumedBy": [
      "book-forge",
      "book-mila",
      "book-tierras",
      "surface-author"
    ],
    "isExternal": false,
    "owner": "frank",
    "links": {
      "package": "/packages/author-council",
      "mcp": "/packages/author-council/src/mcp/server.ts"
    }
  },
  {
    "id": "book-forge",
    "name": "Forge of Ruin",
    "description": "First Open Library book — 45K+ words, 4 chapters",
    "layer": "product",
    "gate": "story",
    "hemisphere": "arc",
    "status": "built",
    "repo": "book/forge-of-ruin",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [
      "author-council",
      "design-system"
    ],
    "consumedBy": [
      "surface-library"
    ],
    "isExternal": false,
    "owner": "frank",
    "links": {
      "repo": "/book/forge-of-ruin"
    }
  },
  {
    "id": "book-mila",
    "name": "Das Mädchen, das drei Sprachen hörte",
    "description": "Trilingual children's book, Mila-bedtime test grade",
    "layer": "product",
    "gate": "story",
    "hemisphere": "arc",
    "status": "built",
    "repo": "book/das-maedchen-drei-sprachen",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [
      "author-council",
      "multilingual",
      "design-system"
    ],
    "consumedBy": [
      "surface-library"
    ],
    "isExternal": false,
    "owner": "frank",
    "links": {
      "live": "https://arcanea.ai/books/das-maedchen-drei-sprachen"
    }
  },
  {
    "id": "book-tierras",
    "name": "Las Tierras de Luz",
    "description": "Co-authored with Ana Cecilia Cancino — Veldoria setting",
    "layer": "product",
    "gate": "story",
    "hemisphere": "arc",
    "status": "built",
    "repo": "book/las-tierras-de-luz",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [
      "author-council",
      "multilingual",
      "design-system"
    ],
    "consumedBy": [
      "surface-library"
    ],
    "isExternal": false,
    "owner": "frank",
    "links": {
      "live": "https://arcanea.ai/books/las-tierras-de-luz"
    }
  },
  {
    "id": "claude-flow",
    "name": "claude-flow",
    "description": "Upstream multi-agent orchestration framework; Arcanea fork is arcanea-flow",
    "layer": "product",
    "gate": "form",
    "hemisphere": "arc",
    "status": "orphan",
    "github": "https://github.com/ruvnet/claude-flow",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "design-system",
    "name": "@arcanea/design-system",
    "description": "Tokens, brand kits, motion variants, primitives (AnimatedBeam, NumberTicker, Marquee)",
    "layer": "substrate",
    "gate": "form",
    "hemisphere": "seam",
    "status": "built",
    "repo": "packages/design-system",
    "packageVersion": "0.3.0",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [
      "book-forge",
      "book-mila",
      "book-tierras"
    ],
    "isExternal": false,
    "owner": "frank",
    "links": {
      "package": "/packages/design-system"
    }
  },
  {
    "id": "multilingual",
    "name": "@starlight/multilingual",
    "description": "i18n foundation — locales, translated slugs, canon glossary",
    "layer": "substrate",
    "gate": "voice",
    "hemisphere": "seam",
    "status": "built",
    "repo": "packages/multilingual",
    "packageVersion": "0.1.0",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [
      "book-mila",
      "book-tierras"
    ],
    "isExternal": false,
    "owner": "frank",
    "links": {
      "package": "/packages/multilingual"
    }
  },
  {
    "id": "oh-my-arcanea",
    "name": "oh-my-arcanea",
    "description": "Universal Arcanea agent harness target; current code remains OpenCode-derived until adapter cleanup",
    "layer": "surface",
    "gate": "voice",
    "hemisphere": "arc",
    "status": "shipped",
    "repo": "frankxai/oh-my-arcanea",
    "github": "https://github.com/frankxai/oh-my-arcanea",
    "publicUrl": "https://github.com/frankxai/oh-my-arcanea",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://github.com/frankxai/oh-my-arcanea"
    }
  },
  {
    "id": "orchestrator",
    "name": "@arcanea/orchestrator",
    "description": "Multi-agent runtime + ecosystem build pipeline",
    "layer": "substrate",
    "gate": "unity",
    "hemisphere": "seam",
    "status": "built",
    "repo": "packages/orchestrator",
    "packageVersion": "1.2.1",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [
      "sis",
      "anthropic-sdk"
    ],
    "consumedBy": [
      "surface-ecosystem"
    ],
    "isExternal": false,
    "owner": "frank",
    "links": {
      "package": "/packages/orchestrator"
    }
  },
  {
    "id": "sis",
    "name": "Starlight Intelligence System",
    "description": "Cross-session memory + horizon vaults + entry stream",
    "layer": "substrate",
    "gate": "source",
    "hemisphere": "seam",
    "status": "built",
    "repo": "https://github.com/frankxai/Starlight-Intelligence-System",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [
      "author-council",
      "orchestrator"
    ],
    "isExternal": false,
    "owner": "frank",
    "links": {
      "github": "https://github.com/frankxai/Starlight-Intelligence-System"
    }
  },
  {
    "id": "starlight",
    "name": "starlight",
    "description": "Minimal SIP adoption kit for Starlight Intelligence System",
    "layer": "product",
    "gate": "form",
    "hemisphere": "arc",
    "status": "orphan",
    "github": "https://github.com/frankxai/starlight",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "starlight-intelligence-system",
    "name": "starlight-intelligence-system",
    "description": "Starlight Intelligence System - SIS/SIP substrate, memory/context layer, MCP servers, adapters",
    "layer": "substrate",
    "gate": "source",
    "hemisphere": "seam",
    "status": "built",
    "repo": "frankxai/Starlight-Intelligence-System",
    "github": "https://github.com/frankxai/Starlight-Intelligence-System",
    "publicUrl": "https://github.com/frankxai/Starlight-Intelligence-System",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://github.com/frankxai/Starlight-Intelligence-System"
    }
  },
  {
    "id": "supabase",
    "name": "Supabase",
    "description": "Postgres, Auth, Realtime, Storage, pgvector",
    "layer": "substrate",
    "gate": "pattern",
    "hemisphere": "seam",
    "status": "external",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": true,
    "links": {
      "docs": "https://supabase.com/docs"
    }
  },
  {
    "id": "surface-author",
    "name": "/author",
    "description": "Public Author Council — paste chapter, pick roster, see deliberation",
    "layer": "surface",
    "gate": "soul",
    "hemisphere": "arc",
    "status": "wip",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [
      "author-council",
      "anthropic-sdk"
    ],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  },
  {
    "id": "surface-ecosystem",
    "name": "/ecosystem",
    "description": "The connected experience map (this page)",
    "layer": "surface",
    "gate": "unity",
    "hemisphere": "seam",
    "status": "shipped",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [
      "orchestrator"
    ],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://arcanea.ai/ecosystem"
    }
  },
  {
    "id": "surface-imagine",
    "name": "/imagine",
    "description": "Image generation — NB2, Fal, Replicate",
    "layer": "surface",
    "gate": "vision",
    "hemisphere": "arc",
    "status": "shipped",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://arcanea.ai/imagine"
    }
  },
  {
    "id": "surface-library",
    "name": "/library",
    "description": "Library OS — books, quotes, chapter summaries",
    "layer": "surface",
    "gate": "story",
    "hemisphere": "arc",
    "status": "shipped",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [
      "book-mila",
      "book-tierras",
      "book-forge"
    ],
    "consumedBy": [],
    "isExternal": false,
    "links": {
      "live": "https://arcanea.ai/library"
    }
  },
  {
    "id": "vercel",
    "name": "Vercel",
    "description": "Hosting, Fluid Compute, AI Gateway, Functions, Blob, Queues",
    "layer": "substrate",
    "gate": "mastery",
    "hemisphere": "nea",
    "status": "external",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": true,
    "links": {
      "docs": "https://vercel.com/docs"
    }
  },
  {
    "id": "vibe-os-substrate",
    "name": "vibe-os-substrate",
    "description": "SIP-conformant vertical scaffold for state engineering",
    "layer": "product",
    "gate": "form",
    "hemisphere": "arc",
    "status": "orphan",
    "github": "https://github.com/frankxai/vibe-os-substrate",
    "lastVerifiedAt": "2026-05-31T10:07:23.762Z",
    "consumes": [],
    "consumedBy": [],
    "isExternal": false,
    "links": {}
  }
];

export const EDGES: EcosystemEdge[] = [
  {
    "source": "author-council",
    "target": "anthropic-sdk",
    "kind": "consumes"
  },
  {
    "source": "author-council",
    "target": "sis",
    "kind": "consumes"
  },
  {
    "source": "book-forge",
    "target": "author-council",
    "kind": "consumes"
  },
  {
    "source": "book-forge",
    "target": "design-system",
    "kind": "consumes"
  },
  {
    "source": "book-mila",
    "target": "author-council",
    "kind": "consumes"
  },
  {
    "source": "book-mila",
    "target": "multilingual",
    "kind": "consumes"
  },
  {
    "source": "book-mila",
    "target": "design-system",
    "kind": "consumes"
  },
  {
    "source": "book-tierras",
    "target": "author-council",
    "kind": "consumes"
  },
  {
    "source": "book-tierras",
    "target": "multilingual",
    "kind": "consumes"
  },
  {
    "source": "book-tierras",
    "target": "design-system",
    "kind": "consumes"
  },
  {
    "source": "orchestrator",
    "target": "sis",
    "kind": "consumes"
  },
  {
    "source": "orchestrator",
    "target": "anthropic-sdk",
    "kind": "consumes"
  },
  {
    "source": "surface-author",
    "target": "author-council",
    "kind": "consumes"
  },
  {
    "source": "surface-author",
    "target": "anthropic-sdk",
    "kind": "consumes"
  },
  {
    "source": "surface-ecosystem",
    "target": "orchestrator",
    "kind": "consumes"
  },
  {
    "source": "surface-library",
    "target": "book-mila",
    "kind": "consumes"
  },
  {
    "source": "surface-library",
    "target": "book-tierras",
    "kind": "consumes"
  },
  {
    "source": "surface-library",
    "target": "book-forge",
    "kind": "consumes"
  }
];
