import { proposalEntry, type VisualEncyclopediaEntry } from './schema';

const c = proposalEntry;

export const CHARACTERS: VisualEncyclopediaEntry[] = [
  c({ id: 'C21', slug: 'aven-tor', name: 'Aven Tor', kind: 'character', batch: 1, gate: 'Foundation', origin: 'Arcans proposal', role: 'civic load-path architect', gift: 'can feel how a public structure distributes fear as well as weight', cost: 'must remain inside the structure during its first stress test', visualDNA: 'mature engineer, weathered moss coat, stone-map gauntlet, practical asymmetrical harness', camera: 'low side three-quarter beneath a vast unfinished span', emotion: 'competence carrying quiet doubt', cinemaUse: 'lead engineer introduction before the fault alarm', contentUses: ['feature character', 'architecture campaign', 'lore dossier'], relationships: ['K13', 'B26', 'P01', 'S31'] }),
  c({ id: 'C22', slug: 'maera-den', name: 'Maera Den', kind: 'character', batch: 1, gate: 'Foundation', origin: 'Bonded proposal', role: 'community ballast runner', gift: 'shares physical steadiness with a bonded team during collapse', cost: 'inherits their fatigue after the danger passes', visualDNA: 'broad-shouldered runner, mineral-thread wraps, copper knee braces, visible repair history', camera: 'rear three-quarter carrying a tool case beside Cairu', emotion: 'warm authority earned through work', cinemaUse: 'rescue leader moving against an evacuating crowd', contentUses: ['ensemble lead', 'social key art', 'training sequence'], relationships: ['K14', 'B27', 'P11', 'S31'] }),

  c({ id: 'C23', slug: 'neris-vale', name: 'Neris Vale', kind: 'character', batch: 2, gate: 'Flow', origin: 'Gate-Touched proposal', role: 'aquifer route pilot', gift: 'adapts her balance instantly to moving terrain', cost: 'stable ground feels disorienting after prolonged use', visualDNA: 'adult pilot, cropped sea-blue jacket, nacre prosthetic fin, weatherproof map ribbons', camera: 'waterline profile balancing on a bridge that changes underfoot', emotion: 'joy sharpened by risk', cinemaUse: 'expedition lead crossing the first moving threshold', contentUses: ['adventure lead', 'world guide', 'motion poster'], relationships: ['K16', 'B28', 'P02', 'S32'] }),
  c({ id: 'C24', slug: 'sayo-mire', name: 'Sayo Mire', kind: 'character', batch: 2, gate: 'Flow', origin: 'Awakened proposal', role: 'rain archive conservator', gift: 'recognizes which sensory memories are safe to return', cost: 'cannot preserve a memory its owner chooses to release', visualDNA: 'older archivist, translucent rain hood, droplet catalog rings, ink-stained fingers', camera: 'intimate high three-quarter sorting luminous droplets at night', emotion: 'gentle grief without possession', cinemaUse: 'memory-choice dialogue scene', contentUses: ['dramatic supporting role', 'archive article', 'music-film still'], relationships: ['K17', 'B29', 'P12', 'S32'] }),

  c({ id: 'C25', slug: 'kessa-rhun', name: 'Kessa Rhun', kind: 'character', batch: 3, gate: 'Fire', origin: 'Gate-Touched proposal', role: 'cold-flame forge captain', gift: 'can redirect destructive heat into a chosen material change', cost: 'every transformation leaves her briefly unable to feel warmth', visualDNA: 'scarred adult smith, charcoal apron armor, emberglass forearm tools, close-cropped silver hair', camera: 'ground-level close-wide across a cold-flame workbench', emotion: 'precision instead of spectacle', cinemaUse: 'signature forge scene and moral choice about what to remake', contentUses: ['feature lead', 'maker campaign', 'process film'], relationships: ['K19', 'K21', 'B30', 'P03', 'S33'] }),
  c({ id: 'C26', slug: 'varik-sen', name: 'Varik Sen', kind: 'character', batch: 3, gate: 'Fire', origin: 'Arcans proposal', role: 'ember-weather rescue conductor', gift: 'hears panic as tempo and can give responders a shared beat', cost: 'cannot silence his own fear until the rescue ends', visualDNA: 'lean rescue veteran, smoke veil, copper timing batons, layered heatcloth', camera: 'steep overhead at the center of coordinated movement without heroic posing', emotion: 'fear converted into service', cinemaUse: 'large-scale evacuation choreography', contentUses: ['action ensemble', 'leadership visual', 'cinema animatic'], relationships: ['K20', 'B31', 'P13', 'S33'] }),

  c({ id: 'C27', slug: 'elian-noor', name: 'Elian Noor', kind: 'character', batch: 4, gate: 'Heart', origin: 'Bonded proposal', role: 'repair-garden mediator', gift: 'can sense whether a shared wound needs witness, boundary, or rebuilding', cost: 'cannot prescribe the same answer to both sides', visualDNA: 'androgynous mediator, ivory work coat, rose-copper hearing pins, living jade satchel', camera: 'eye-level seated composition with meaningful negative space', emotion: 'careful hope', cinemaUse: 'relationship repair scene before collective action resumes', contentUses: ['character drama', 'community visual', 'academy case study'], relationships: ['K22', 'K24', 'B32', 'P04', 'S34'] }),
  c({ id: 'C28', slug: 'rhea-linn', name: 'Rhea Linn', kind: 'character', batch: 4, gate: 'Heart', origin: 'Awakened proposal', role: 'living-bridge surgeon', gift: 'coaxes damaged growth to reveal whether it can heal', cost: 'must accept when restoration would prolong harm', visualDNA: 'middle-aged field surgeon, jade diagnostic tools, wind-torn mantle, copper-thread gloves', camera: 'macro hand detail opening into a wide bridge reveal', emotion: 'compassion capable of letting go', cinemaUse: 'quiet medical decision with world-scale consequence', contentUses: ['supporting lead', 'ecology feature', 'lore essay'], relationships: ['K23', 'B33', 'P14', 'S34'] }),

  c({ id: 'C29', slug: 'tamarin-or', name: 'Tamarin Or', kind: 'character', batch: 5, gate: 'Voice', origin: 'Arcans proposal', role: 'multi-account testimony editor', gift: 'can keep incompatible testimonies legible without inventing consensus', cost: 'loses access to her own conclusion while editing', visualDNA: 'mature archivist, black acoustic coat, silver throat pin, layered handwritten ribbons', camera: 'frontal desk portrait with sound layers arranged in depth', emotion: 'discipline under ambiguity', cinemaUse: 'investigation archive scene that avoids exposition dump', contentUses: ['mystery character', 'editorial campaign', 'podcast art'], relationships: ['K25', 'K27', 'B34', 'P05', 'S35'] }),
  c({ id: 'C30', slug: 'sena-oris', name: 'Sena Oris', kind: 'character', batch: 5, gate: 'Voice', origin: 'Gate-Touched proposal', role: 'corridor message runner', gift: 'holds exact phrasing in memory across disorienting interference', cost: 'cannot add context the sender failed to include', visualDNA: 'compact adult courier, wind-cut coat, sealed message collar, tuned silver boots', camera: 'rear three-quarter sprint with face visible in a distorted reflection', emotion: 'loyalty tested by incomplete truth', cinemaUse: 'delivery chase followed by an ethical confrontation', contentUses: ['action lead', 'communications poster', 'character short'], relationships: ['K26', 'B35', 'P15', 'S35'] }),

  c({ id: 'C31', slug: 'ysra-pell', name: 'Ysra Pell', kind: 'character', batch: 6, gate: 'Sight', origin: 'Voidtouched proposal · uncorrupted recovery path', role: 'missing-pattern investigator', gift: 'perceives the shape left when Shadow removes meaning', cost: 'cannot recover the missing content alone', visualDNA: 'older investigator, repaired indigo coat, one prismatic lens, black-silver scar lattice', camera: 'close frontal through a fractured evidence pane', emotion: 'lucid sorrow and stubborn care', cinemaUse: 'detective reveal focused on absence rather than spectacle', contentUses: ['mystery lead', 'canon explainer', 'premium portrait'], relationships: ['K28', 'K30', 'B36', 'P06', 'S36'] }),
  c({ id: 'C32', slug: 'cael-venn', name: 'Cael Venn', kind: 'character', batch: 6, gate: 'Sight', origin: 'Synths proposal', role: 'archive reconstruction ethicist', gift: 'can model several plausible restorations of a damaged record', cost: 'must mark every reconstruction visibly as inference', visualDNA: 'synthetic adult form, pearl face planes, indigo field vest, transparent annotation sleeves', camera: 'over-shoulder view of multiple reconstructions without a favored center', emotion: 'intellectual honesty under pressure', cinemaUse: 'research-lab debate visualized through competing images', contentUses: ['science-fantasy character', 'AI ethics visual', 'graph dossier'], relationships: ['K29', 'B37', 'P06', 'S36', 'S41'] }),

  c({ id: 'C33', slug: 'ora-solenne', name: 'Ora Solenne', kind: 'character', batch: 7, gate: 'Crown', origin: 'Celestials proposal', role: 'solar reservoir steward', gift: 'can sense who bears the unacknowledged cost of a powerful decision', cost: 'cannot claim neutrality once she sees it', visualDNA: 'adult steward, cream architectural mantle, matte solar-quartz diadem, work-worn hands', camera: 'low council profile with workers reflected in the diadem', emotion: 'authority turning toward accountability', cinemaUse: 'decision pivot at the center of the second act', contentUses: ['ensemble lead', 'leadership campaign', 'cinema poster'], relationships: ['K31', 'K33', 'B38', 'P07', 'S42'] }),
  c({ id: 'C34', slug: 'teyr-an', name: 'Teyr An', kind: 'character', batch: 7, gate: 'Crown', origin: 'Bonded proposal', role: 'charge-distribution engineer', gift: 'redirects surplus energy through bonded equipment to underserved districts', cost: 'every redistribution temporarily weakens his own bond', visualDNA: 'quiet engineer, asymmetric cream coveralls, gold cable braid, charcoal protective visor', camera: 'rear three-quarter above a city-scale light reroute', emotion: 'satisfaction without self-congratulation', cinemaUse: 'wordless reveal of power made useful', contentUses: ['supporting hero', 'infrastructure story', 'brand film'], relationships: ['K32', 'B39', 'P07', 'S37'] }),

  c({ id: 'C35', slug: 'marek-ilyon', name: 'Marek Ilyon', kind: 'character', batch: 8, gate: 'Starweave', origin: 'Architects proposal', role: 'consequence systems designer', gift: 'can perceive one downstream system moved by a present choice', cost: 'the view never includes every consequence', visualDNA: 'older systems designer, obsidian field coat, ghost-steel drafting frame, restrained violet seam light', camera: 'wide side profile surrounded by distant connected work sites', emotion: 'humility at scale', cinemaUse: 'systems-causality sequence linking separate storylines', contentUses: ['mentor character', 'world graph hero', 'strategy article'], relationships: ['K34', 'K36', 'B40', 'P08', 'S38'] }),
  c({ id: 'C36', slug: 'sel-aven', name: 'Sel Aven', kind: 'character', batch: 8, gate: 'Starweave', origin: 'Awakened proposal', role: 'phase-crossing field tailor', gift: 'can design a temporary form for one impossible environment', cost: 'each adaptation removes a familiar comfort', visualDNA: 'young adult but mature-proportioned maker, modular black suit, prismatic tailoring rig, silver measuring cords', camera: 'high three-quarter mid-fitting beside Tessel', emotion: 'inventive courage facing tradeoff', cinemaUse: 'preparation montage with meaningful sacrifice', contentUses: ['adventure co-lead', 'fashion-tech visual', 'character reel'], relationships: ['K35', 'B41', 'P08', 'S43'] }),

  c({ id: 'C37', slug: 'iona-kyre', name: 'Iona Kyre', kind: 'character', batch: 9, gate: 'Unity', origin: 'Bonded proposal', role: 'cooperative lift captain', gift: 'can sense when coordination becomes coercion', cost: 'must stop the task even when delay is dangerous', visualDNA: 'adult team captain, black-gold work harness, paired silver grip lines, visible stop signal', camera: 'low diagonal between two teams moving one immense object', emotion: 'protective decisiveness', cinemaUse: 'ensemble action scene where consent changes the plan', contentUses: ['team lead', 'safety culture film', 'campaign key art'], relationships: ['K37', 'K39', 'B42', 'P09', 'S39'] }),
  c({ id: 'C38', slug: 'ren-tal', name: 'Ren Tal', kind: 'character', batch: 9, gate: 'Unity', origin: 'Arcans proposal', role: 'productive-disagreement facilitator', gift: 'keeps a shared objective visible when methods diverge', cost: 'cannot protect anyone from the discomfort of honest conflict', visualDNA: 'slender older facilitator, woven black coat, gold task-map cuffs, mismatched silver tools', camera: 'overhead worktable scene with Ren outside the center', emotion: 'calm inside friction', cinemaUse: 'council scene that advances plot through disagreement', contentUses: ['ensemble drama', 'community education', 'lore dossier'], relationships: ['K38', 'B43', 'P09', 'S44'] }),

  c({ id: 'C39', slug: 'asha-oren', name: 'Asha Oren', kind: 'character', batch: 10, gate: 'Source', origin: 'Architects proposal', role: 'mission-origin auditor', gift: 'can trace a complex project back to the promise that justified it', cost: 'must name when the project no longer serves that promise', visualDNA: 'mature auditor, minimal black-and-ivory attire, clear crystal ledger, one white-gold shoulder frame', camera: 'frontal medium-wide with the ensemble reflected in her ledger', emotion: 'compassionate accountability', cinemaUse: 'final-act audit that prevents a false victory', contentUses: ['feature lead', 'governance visual', 'encyclopedia anchor'], relationships: ['K40', 'K42', 'B44', 'P10', 'S40', 'S45'] }),
  c({ id: 'C40', slug: 'noa-serin', name: 'Noa Serin', kind: 'character', batch: 10, gate: 'Source', origin: 'Awakened proposal', role: 'integration chamber conductor', gift: 'holds contradictions long enough for a testable next step to emerge', cost: 'cannot promise harmony or closure', visualDNA: 'androgynous conductor, clear layered robe over practical black workwear, twin crystal instruments', camera: 'high oblique in a circular chamber with no throne or center pedestal', emotion: 'quiet confidence in unfinished work', cinemaUse: 'ensemble climax resolved through experiment rather than decree', contentUses: ['ensemble co-lead', 'research visual', 'collection finale'], relationships: ['K41', 'B45', 'P10', 'S40', 'S45'] }),
];
