import { proposalEntry, type VisualEncyclopediaEntry } from './schema';

const b = proposalEntry;

export const CREATURES: VisualEncyclopediaEntry[] = [
  b({ id: 'B26', slug: 'quarryshell-nibbler', name: 'Quarryshell Nibbler', kind: 'creature', batch: 1, gate: 'Foundation', origin: 'Wildlife proposal', role: 'micro-fracture grazer', gift: 'eats unstable mineral edges before they become dangerous shards', cost: 'avoids perfectly finished stone and cannot survive ornamental quarrying', visualDNA: 'badger-sized hexapod, layered slate shell, amber whiskers, soft moss undercoat', camera: 'macro low angle beside a monumental crack for scale', emotion: 'busy, harmless competence', cinemaUse: 'early-warning wildlife insert', contentUses: ['ecology card', 'family-safe mascot', 'cinema texture'], relationships: ['K13', 'C21', 'P01', 'S31'] }),
  b({ id: 'B27', slug: 'moss-crown-dray', name: 'Moss-Crown Dray', kind: 'creature', batch: 1, gate: 'Foundation', origin: 'Wildlife proposal', role: 'terrace-soil carrier', gift: 'moves living topsoil between damaged foundation gardens', cost: 'will shed its load rather than cross poisoned ground', visualDNA: 'small sturdy ungulate, crown of living moss, stone hoof caps, woven-looking fur bands', camera: 'wide side profile ascending terraced stone', emotion: 'ancient patience in a compact body', cinemaUse: 'restoration montage companion', contentUses: ['world atlas', 'social character', 'environment scene'], relationships: ['K15', 'C22', 'P11', 'S31'] }),

  b({ id: 'B28', slug: 'ribbonfin-listener', name: 'Ribbonfin Listener', kind: 'creature', batch: 2, gate: 'Flow', origin: 'Wildlife proposal', role: 'current-change sentinel', gift: 'turns its translucent fins toward new pathways in moving water', cost: 'cannot distinguish safe change from merely novel change', visualDNA: 'otter-ray hybrid silhouette, long nacre fins, deep-blue wet fur, silver sensory dots', camera: 'underwater upward three-quarter with fins forming a readable directional arc', emotion: 'curious responsiveness', cinemaUse: 'expedition route omen without prophecy', contentUses: ['creature atlas', 'cinema insert', 'animated loop'], relationships: ['K16', 'C23', 'P02', 'S32'] }),
  b({ id: 'B29', slug: 'pearlwake-tern', name: 'Pearlwake Tern', kind: 'creature', batch: 2, gate: 'Flow', origin: 'Wildlife proposal', role: 'rain-memory seed disperser', gift: 'carries empty memory pearls back into storm clouds', cost: 'filled pearls make its flight dangerously heavy', visualDNA: 'elegant seabird, pearl-lined tail fan, waterglass beak, blue-silver wing edges', camera: 'long-lens banking flight through rain with one heavy pearl visible', emotion: 'fragile duty', cinemaUse: 'transition between archive and storm locations', contentUses: ['cinema transition', 'music artwork', 'world atlas'], relationships: ['K17', 'C24', 'P12', 'S32'] }),

  b({ id: 'B30', slug: 'cindercoil-lynx', name: 'Cindercoil Lynx', kind: 'creature', batch: 3, gate: 'Fire', origin: 'Wildlife proposal', role: 'forge-heat scavenger', gift: 'draws waste heat into a glowing spiral along its back', cost: 'becomes sluggish and vulnerable after discharge', visualDNA: 'lean feline, charcoal mineral fur, copper coil spine, cool ember eyes, no armor', camera: 'low stalking profile against black glass with heat distortion', emotion: 'wary elegance', cinemaUse: 'forge district atmosphere and heat-status cue', contentUses: ['creature hero', 'cinematic insert', 'atlas profile'], relationships: ['K19', 'C25', 'P03', 'S33'] }),
  b({ id: 'B31', slug: 'hearthglass-beetle', name: 'Hearthglass Beetle', kind: 'creature', batch: 3, gate: 'Fire', origin: 'Wildlife proposal', role: 'cold-spark path marker', gift: 'lays a trail of heatless orange points visible through ash', cost: 'the trail fades when the beetle stops moving', visualDNA: 'hand-sized beetle, translucent black elytra, fine gold legs, pulsing cold core', camera: 'extreme macro overhead with a rescue route emerging behind', emotion: 'tiny urgency', cinemaUse: 'match cut from macro path to city-scale evacuation', contentUses: ['motion graphic source', 'ecology detail', 'social loop'], relationships: ['K20', 'C26', 'P13', 'S33'] }),

  b({ id: 'B32', slug: 'rosewind-hart', name: 'Rosewind Hart', kind: 'creature', batch: 4, gate: 'Heart', origin: 'Wildlife proposal', role: 'boundary-garden browser', gift: 'grazes only growth that has crossed into another living system without consent', cost: 'cannot feed in a garden with no clear boundaries', visualDNA: 'slender deer, rose-copper antlers like open brackets, ivory coat, jade leaf markings', camera: 'eye-level long-lens portrait between two garden zones', emotion: 'gentle discernment', cinemaUse: 'quiet visual metaphor before a boundary conversation', contentUses: ['creature atlas', 'drama insert', 'poster art'], relationships: ['K22', 'C27', 'P04', 'S34'] }),
  b({ id: 'B33', slug: 'jadepulse-mender', name: 'Jadepulse Mender', kind: 'creature', batch: 4, gate: 'Heart', origin: 'Wildlife proposal', role: 'living-bridge parasite cleaner', gift: 'eats diseased jade growth while leaving viable tissue intact', cost: 'overfeeds when exposed to artificially accelerated healing', visualDNA: 'fox-sized insectivore, jade whisker fans, ivory plated snout, copper pulse marks', camera: 'macro side view on a damaged living bridge', emotion: 'strange tenderness', cinemaUse: 'medical ecology insert supporting Rhea’s diagnosis', contentUses: ['world atlas', 'healing-system visual', 'cinema detail'], relationships: ['K23', 'C28', 'P14', 'S34'] }),

  b({ id: 'B34', slug: 'echoquill-finch', name: 'Echoquill Finch', kind: 'creature', batch: 5, gate: 'Voice', origin: 'Wildlife proposal', role: 'acoustic diversity indicator', gift: 'repeats the least-heard sound in its environment', cost: 'falls silent when every sound has been compressed into one signal', visualDNA: 'small dark finch, silver quill tail, translucent throat, asymmetric listening crest', camera: 'macro frontal with several dim sound sources behind', emotion: 'insistent delicacy', cinemaUse: 'subtle clue that a testimony is missing', contentUses: ['mystery insert', 'sound-brand character', 'atlas card'], relationships: ['K25', 'C29', 'P05', 'S35'] }),
  b({ id: 'B35', slug: 'resonant-bellfox', name: 'Resonant Bellfox', kind: 'creature', batch: 5, gate: 'Voice', origin: 'Wildlife proposal', role: 'corridor interference tracker', gift: 'its hollow tail rings only when a message is being bent', cost: 'cannot identify the source of distortion', visualDNA: 'long-legged fox, ink-black coat, silver bell tail, pale acoustic ears, mature animal anatomy', camera: 'tracking side profile through a warped corridor', emotion: 'alert companionship', cinemaUse: 'chase companion that turns sound design into story evidence', contentUses: ['action creature', 'audio campaign', 'cinema keyframe'], relationships: ['K26', 'C30', 'P15', 'S35'] }),

  b({ id: 'B36', slug: 'prismveil-ray', name: 'Prismveil Ray', kind: 'creature', batch: 6, gate: 'Sight', origin: 'Wildlife proposal', role: 'surface-truth grazer', gift: 'reveals different textures when seen from fact, inference, or fear angles', cost: 'no single viewing angle shows the whole animal', visualDNA: 'air-swimming ray, pearl underside, indigo translucent wings, narrow prismatic edge', camera: 'three-quarter view with one wing crossing distinct light planes', emotion: 'elusive clarity', cinemaUse: 'visual motif during an investigation’s competing readings', contentUses: ['creature hero', 'research visual', 'motion loop'], relationships: ['K28', 'C31', 'P06', 'S36'] }),
  b({ id: 'B37', slug: 'lantern-eye-kestrel', name: 'Lantern-Eye Kestrel', kind: 'creature', batch: 6, gate: 'Sight', origin: 'Wildlife proposal', role: 'absence-edge hunter', gift: 'perches beside gaps where a pattern should continue', cost: 'cannot distinguish loss from intentional silence', visualDNA: 'compact raptor, single luminous ring around each eye, pearl-gray feathers, indigo tail bars', camera: 'long-lens perched silhouette beside a visibly incomplete mural', emotion: 'watchful uncertainty', cinemaUse: 'recurring absence clue', contentUses: ['mystery motif', 'atlas profile', 'editorial still'], relationships: ['K29', 'C32', 'P06', 'S41'] }),

  b({ id: 'B38', slug: 'sunmantle-ibex', name: 'Sunmantle Ibex', kind: 'creature', batch: 7, gate: 'Crown', origin: 'Wildlife proposal', role: 'reservoir-overflow grazer', gift: 'absorbs excess solar warmth into a luminous shoulder mantle', cost: 'must descend to cold ground before whiteout', visualDNA: 'mountain ibex, cream coat, matte-gold horns, warm mantle plates, black hooves', camera: 'low wide silhouette on a reservoir rim at dusk', emotion: 'majestic restraint', cinemaUse: 'natural meter for dangerous power accumulation', contentUses: ['creature poster', 'cinema establishing shot', 'atlas entry'], relationships: ['K31', 'K33', 'C33', 'P07', 'S42'] }),
  b({ id: 'B39', slug: 'halo-petal-glider', name: 'Halo-Petal Glider', kind: 'creature', batch: 7, gate: 'Crown', origin: 'Wildlife proposal', role: 'distributed-light pollinator', gift: 'splits one bright beam across many low-light gardens', cost: 'cannot survive prolonged direct exposure', visualDNA: 'small gliding mammal, petal-like gold membranes, cream fur, charcoal eyes, no wings', camera: 'high oblique flight above dim terraces gaining gentle light', emotion: 'quiet generosity', cinemaUse: 'visual answer to the city power-reroute', contentUses: ['hopeful insert', 'ecology card', 'social animation'], relationships: ['K32', 'C34', 'P07', 'S37'] }),

  b({ id: 'B40', slug: 'phasehoof-strider', name: 'Phasehoof Strider', kind: 'creature', batch: 8, gate: 'Starweave', origin: 'Wildlife proposal', role: 'thin-boundary migrator', gift: 'crosses one narrow material boundary during seasonal migration', cost: 'each crossing leaves the herd out of step for several heartbeats', visualDNA: 'tall antelope-like body, ghost-steel hooves, pale mineral hide, offset prismatic mane', camera: 'side profile with one hoof on either side of a translucent wall', emotion: 'melancholy momentum', cinemaUse: 'world-scale migration motif and temporal-lag reference', contentUses: ['cinema key art', 'creature atlas', 'world trailer'], relationships: ['K34', 'K36', 'C35', 'P08', 'S38'] }),
  b({ id: 'B41', slug: 'threadtail-grazer', name: 'Threadtail Grazer', kind: 'creature', batch: 8, gate: 'Starweave', origin: 'Wildlife proposal', role: 'failed-path composter', gift: 'eats abandoned probability growth and trails fertile thread', cost: 'cannot revisit a consumed path', visualDNA: 'compact long-necked grazer, obsidian muzzle, pale fur, glowing thread tail, silver feet', camera: 'high three-quarter following a luminous but non-repeating trail', emotion: 'renewal with finality', cinemaUse: 'transition from failed plan to new route', contentUses: ['atlas hero', 'creator-recovery visual', 'cinema insert'], relationships: ['K35', 'C36', 'P08', 'S43'] }),

  b({ id: 'B42', slug: 'twinbeat-otter', name: 'Twinbeat Otter', kind: 'creature', batch: 9, gate: 'Unity', origin: 'Wildlife proposal', role: 'cooperative current fisher', gift: 'pairs with a differently paced partner to catch food neither could reach alone', cost: 'the pair separates if one begins taking both shares', visualDNA: 'two visibly distinct river otter morphs, silver chest marks, black-gold wet fur, natural proportions', camera: 'water-level two-shot with mirrored but unequal movement', emotion: 'joyful cooperation', cinemaUse: 'light ensemble beat that models reciprocity', contentUses: ['creature pair', 'community campaign', 'short-form animation'], relationships: ['K37', 'C37', 'P09', 'S39'] }),
  b({ id: 'B43', slug: 'chorusback-weaver', name: 'Chorusback Weaver', kind: 'creature', batch: 9, gate: 'Unity', origin: 'Wildlife proposal', role: 'shared-nest architect', gift: 'weaves separate nest chambers around one load-bearing frame', cost: 'abandons a frame when any chamber blocks another’s exit', visualDNA: 'large gentle arthropod, black-gold segmented back, silver silk combs, many expressive eyelets', camera: 'overhead architectural view of distinct chambers sharing one spine', emotion: 'strange social intelligence', cinemaUse: 'visual metaphor for unity without sameness', contentUses: ['atlas infographic', 'world documentary', 'graph art'], relationships: ['K38', 'K39', 'C38', 'P09', 'S44'] }),

  b({ id: 'B44', slug: 'quiet-orbit-crane', name: 'Quiet-Orbit Crane', kind: 'creature', batch: 10, gate: 'Source', origin: 'Wildlife proposal', role: 'integration-courtyard cycle keeper', gift: 'walks a complete orbit only when every habitat zone remains connected', cost: 'stops rather than bypassing a broken link', visualDNA: 'tall white-gray crane, thin gold orbital neck mark, black glass-like legs, clear feather edges', camera: 'high overhead courtyard circle with one broken arc visible', emotion: 'graceful accountability', cinemaUse: 'silent indicator that the mission is not yet complete', contentUses: ['cinema motif', 'atlas portrait', 'governance visual'], relationships: ['K40', 'C39', 'P10', 'S40'] }),
  b({ id: 'B45', slug: 'origin-shell-tortoise', name: 'Origin-Shell Tortoise', kind: 'creature', batch: 10, gate: 'Source', origin: 'Wildlife proposal', role: 'whole-pattern seed carrier', gift: 'its clear shell records the sequence of habitats that sustained it', cost: 'new growth is impossible if one habitat is erased from the record', visualDNA: 'large calm tortoise, translucent layered shell, white-gold growth rings, soft black skin', camera: 'low intimate three-quarter with miniature habitat reflections inside the shell', emotion: 'deep time made tender', cinemaUse: 'closing-world image tying the journey together', contentUses: ['collection finale', 'encyclopedia cover detail', 'cinema epilogue'], relationships: ['K41', 'C40', 'P10', 'S45'] }),
];
