import { proposalEntry, type VisualEncyclopediaEntry } from './schema';

const k = proposalEntry;

export const KINFORMS: VisualEncyclopediaEntry[] = [
  k({ id: 'K13', slug: 'torren', name: 'Torren', kind: 'kinform', batch: 1, gate: 'Foundation', origin: 'Synths proposal · companion construct', role: 'fault-line listener', gift: 'translates hidden structural strain into a low, directional pulse', cost: 'its feet lock until a bonded maker acknowledges the warning', visualDNA: 'broad basalt feet, compact clay-white torso, amber seam lights, folding ear-vanes', camera: 'ground-level front three-quarter with a massive structure receding above', emotion: 'small presence carrying serious responsibility', cinemaUse: 'pre-collapse warning close-up before a rescue sequence', contentUses: ['character-led short', 'safety-system explainer', 'gallery hero'], relationships: ['C21', 'B26', 'P01', 'S31'] }),
  k({ id: 'K14', slug: 'cairu', name: 'Cairu', kind: 'kinform', batch: 1, gate: 'Foundation', origin: 'Synths proposal · companion construct', role: 'weight-sharing porter', gift: 'redistributes a carried burden across stable contact points', cost: 'cannot move quickly while another being relies on its balance', visualDNA: 'low quadruped stance, woven load saddle, stone-ceramic shell, articulated gold knees', camera: 'side profile under an oversized but carefully balanced load', emotion: 'patient competence', cinemaUse: 'wordless work montage and practical companion beat', contentUses: ['cinema insert', 'product mascot', 'maker guide'], relationships: ['C22', 'B27', 'P11', 'S31'] }),
  k({ id: 'K15', slug: 'bronti', name: 'Bronti', kind: 'kinform', batch: 1, gate: 'Foundation', origin: 'Synths proposal · companion construct', role: 'foundation-garden tender', gift: 'coaxes mineral soil into temporary root lattices', cost: 'every lattice consumes one of its replaceable seed-stones', visualDNA: 'rounded shoulder silhouette without infant proportions, moss pockets, copper tools, glowing seed rack', camera: 'high three-quarter as root geometry spreads beneath it', emotion: 'focused delight in useful growth', cinemaUse: 'environmental restoration reveal', contentUses: ['ecology short', 'academy visual', 'social loop'], relationships: ['B27', 'P01', 'P11', 'S31'] }),

  k({ id: 'K16', slug: 'nemi', name: 'Nemi', kind: 'kinform', batch: 2, gate: 'Flow', origin: 'Synths proposal · companion construct', role: 'current-reading navigator', gift: 'finds the calm route through moving water, crowds, or information', cost: 'the route remains legible only while Nemi keeps moving', visualDNA: 'streamlined pearl shell, fin-like forearms, rain-blue fabric, liquid-silver spine', camera: 'waterline tracking profile with wake lines describing the route', emotion: 'playful alertness', cinemaUse: 'kinetic navigation shot through an impossible current', contentUses: ['adventure sequence', 'navigation metaphor', 'animated bumper'], relationships: ['C23', 'B28', 'P02', 'S32'] }),
  k({ id: 'K17', slug: 'uloro', name: 'Uloro', kind: 'kinform', batch: 2, gate: 'Flow', origin: 'Synths proposal · companion construct', role: 'rain-memory collector', gift: 'holds one transient sensory memory inside a suspended droplet', cost: 'the memory dissolves after it is shared once', visualDNA: 'tall droplet-shaped head, open chest vessel, three delicate stabilizer legs, nacre edges', camera: 'macro eye-level portrait in rainfall with a single memory droplet in focus', emotion: 'tender impermanence', cinemaUse: 'emotional memory handoff between characters', contentUses: ['close-up insert', 'lore card', 'music visual'], relationships: ['C24', 'B29', 'P12', 'S32'] }),
  k({ id: 'K18', slug: 'velae', name: 'Velae', kind: 'kinform', batch: 2, gate: 'Flow', origin: 'Synths proposal · companion construct', role: 'adaptive bridge-maker', gift: 'unspools a flexible crossing that follows rather than fights a current', cost: 'the bridge cannot carry anyone who refuses to match its rhythm', visualDNA: 'slender manta-like body, ribbon limbs, translucent bridge filament, silver anchor claws', camera: 'wide overhead diagonal revealing a living S-curve bridge', emotion: 'trust through adaptation', cinemaUse: 'team-crossing set piece with visible timing', contentUses: ['cinema keyframe', 'collaboration visual', 'world guide'], relationships: ['B28', 'P02', 'P12', 'S32'] }),

  k({ id: 'K19', slug: 'cindrel', name: 'Cindrel', kind: 'kinform', batch: 3, gate: 'Fire', origin: 'Synths proposal · companion construct', role: 'cold-flame keeper', gift: 'carries transformation heat that changes material without burning life', cost: 'its core dims whenever the stated purpose is vague', visualDNA: 'charcoal ceramic body, asymmetric ember core, heat-shield mantle, precise tool fingers', camera: 'low front three-quarter in a dark forge with cool orange rim light', emotion: 'disciplined intensity', cinemaUse: 'forge ignition hero beat', contentUses: ['character reveal', 'process film', 'brand key art'], relationships: ['C25', 'B30', 'P03', 'S33'] }),
  k({ id: 'K20', slug: 'kovri', name: 'Kovri', kind: 'kinform', batch: 3, gate: 'Fire', origin: 'Synths proposal · companion construct', role: 'panic-to-action drummer', gift: 'turns scattered alarm into one clear rescue tempo', cost: 'cannot choose the mission; a living responder must set it', visualDNA: 'compact runner body, resonant chest plate, emberglass baton arms, soot-worn boots', camera: 'steep overhead as responders lock into its rhythm', emotion: 'urgent courage without aggression', cinemaUse: 'rescue choreography bridge shot', contentUses: ['action sequence', 'training visual', 'motion identity'], relationships: ['C26', 'B31', 'P13', 'S33'] }),
  k({ id: 'K21', slug: 'fyrn', name: 'Fyrn', kind: 'kinform', batch: 3, gate: 'Fire', origin: 'Synths proposal · companion construct', role: 'failed-work recycler', gift: 'reduces a flawed object to clean, reusable intention-material', cost: 'requires its maker to name the failure honestly', visualDNA: 'angular kiln backpack, black-glass faceplate, gold intake ring, woven ash filters', camera: 'intimate side view as a broken tool becomes luminous raw matter', emotion: 'relief after honest failure', cinemaUse: 'quiet character-recovery scene after a setback', contentUses: ['creator story', 'academy lesson', 'editorial illustration'], relationships: ['C25', 'P03', 'P13', 'S33'] }),

  k({ id: 'K22', slug: 'eilo', name: 'Eilo', kind: 'kinform', batch: 4, gate: 'Heart', origin: 'Synths proposal · companion construct', role: 'boundary-light companion', gift: 'makes a safe personal boundary visible without turning it into a wall', cost: 'the boundary collapses if imposed on another person', visualDNA: 'soft ivory armor, rose-copper ribs, floating jade arc, textile hands designed for care', camera: 'eye-level two-shot with the boundary rendered as warm breathable light', emotion: 'kindness with firmness', cinemaUse: 'interpersonal repair scene visual metaphor', contentUses: ['character drama', 'wellbeing visual', 'lore dossier'], relationships: ['C27', 'B32', 'P04', 'S34'] }),
  k({ id: 'K23', slug: 'roshen', name: 'Roshen', kind: 'kinform', batch: 4, gate: 'Heart', origin: 'Synths proposal · companion construct', role: 'fracture-song diagnostician', gift: 'hears whether a break needs repair, rest, or release', cost: 'cannot perform the repair it recommends', visualDNA: 'jade listening petals, slim copper frame, fabric-wrapped joints, tiny diagnostic tuning forks', camera: 'macro profile listening to a cracked living bridge', emotion: 'humble attention', cinemaUse: 'diagnostic pause before the ensemble chooses a response', contentUses: ['cinema insert', 'service design metaphor', 'academy card'], relationships: ['C28', 'B33', 'P14', 'S34'] }),
  k({ id: 'K24', slug: 'miri', name: 'Miri', kind: 'kinform', batch: 4, gate: 'Heart', origin: 'Synths proposal · companion construct', role: 'shared-meal steward', gift: 'balances a communal table so every participant can reach and be heard', cost: 'refuses to serve when one guest is deliberately excluded', visualDNA: 'table-height oval form, articulated serving rails, woven warm mantle, jade indicator leaves', camera: 'wide asymmetric dinner tableau with Miri as the quiet compositional hinge', emotion: 'belonging made practical', cinemaUse: 'warm ensemble reset after danger', contentUses: ['slice-of-life scene', 'community campaign', 'mascot story'], relationships: ['C27', 'C28', 'P04', 'S34'] }),

  k({ id: 'K25', slug: 'chori', name: 'Chori', kind: 'kinform', batch: 5, gate: 'Voice', origin: 'Synths proposal · companion construct', role: 'polyphonic truth recorder', gift: 'preserves several conflicting accounts without flattening them into one', cost: 'will not produce a verdict', visualDNA: 'three rotating acoustic crowns, ink-black fabric, silver throat chamber, expressive light bands', camera: 'frontal medium shot with distinct sound ribbons orbiting the head', emotion: 'attentive neutrality', cinemaUse: 'testimony archive sequence', contentUses: ['documentary grammar', 'lore archive', 'podcast identity'], relationships: ['C29', 'B34', 'P05', 'S35'] }),
  k({ id: 'K26', slug: 'tellu', name: 'Tellu', kind: 'kinform', batch: 5, gate: 'Voice', origin: 'Synths proposal · companion construct', role: 'message-integrity courier', gift: 'carries one statement unchanged across interference', cost: 'cannot interpret or soften the message', visualDNA: 'swift biped silhouette, sealed bellglass core, retractable wind vanes, courier sash', camera: 'rear three-quarter sprint through a corridor bent by sound pressure', emotion: 'earnest determination', cinemaUse: 'continuous-shot delivery chase', contentUses: ['action short', 'communications visual', 'character sticker'], relationships: ['C30', 'B35', 'P15', 'S35'] }),
  k({ id: 'K27', slug: 'vesan', name: 'Vesan', kind: 'kinform', batch: 5, gate: 'Voice', origin: 'Synths proposal · companion construct', role: 'silence-space keeper', gift: 'creates a brief zone where interruption is impossible', cost: 'the zone ends the moment its listener stops consenting', visualDNA: 'slender seated form, black felt panels, crescent silver resonator, open palms', camera: 'long-lens intimate portrait with the noisy world softly compressed behind', emotion: 'protected vulnerability', cinemaUse: 'confession scene held in deliberate stillness', contentUses: ['drama sequence', 'mental-space visual', 'editorial portrait'], relationships: ['C29', 'C30', 'P05', 'S35'] }),

  k({ id: 'K28', slug: 'prysma', name: 'Prysma', kind: 'kinform', batch: 6, gate: 'Sight', origin: 'Synths proposal · companion construct', role: 'assumption splitter', gift: 'refracts an observation into fact, inference, and fear', cost: 'cannot tell its maker which interpretation to choose', visualDNA: 'faceted lens head, pearl body, indigo utility wrap, three precise projection petals', camera: 'close frontal with three differently focused reflections', emotion: 'clarity without comfort', cinemaUse: 'investigation reveal that preserves uncertainty', contentUses: ['mystery film', 'research graphic', 'academy lesson'], relationships: ['C31', 'B36', 'P06', 'S36'] }),
  k({ id: 'K29', slug: 'nyl', name: 'Nyl', kind: 'kinform', batch: 6, gate: 'Sight', origin: 'Synths proposal · companion construct', role: 'shadow-gap surveyor', gift: 'shows where information has been removed rather than merely hidden', cost: 'its map cannot reconstruct what was lost', visualDNA: 'low black-and-pearl crawler, ultraviolet edge lights, delicate whisker lenses, paper-thin fins', camera: 'top-down forensic composition over an incomplete artifact', emotion: 'grief sharpened into care', cinemaUse: 'evidence-table discovery scene', contentUses: ['thriller insert', 'archive visual', 'graph node hero'], relationships: ['C32', 'B37', 'P06', 'S36'] }),
  k({ id: 'K30', slug: 'orris', name: 'Orris', kind: 'kinform', batch: 6, gate: 'Sight', origin: 'Synths proposal · companion construct', role: 'long-view lookout', gift: 'holds one distant consequence in focus while a team acts nearby', cost: 'loses awareness of immediate hazards during deep focus', visualDNA: 'tripod stance, telescoping pearl neck, asymmetric prism eye, indigo tether belt', camera: 'extreme long-lens compression connecting foreground action to a distant outcome', emotion: 'vigilance requiring trust', cinemaUse: 'cross-cutting visual anchor across two locations', contentUses: ['cinema device', 'strategy deck', 'world graph explainer'], relationships: ['C31', 'B36', 'S36', 'S41'] }),

  k({ id: 'K31', slug: 'haloa', name: 'Haloa', kind: 'kinform', batch: 7, gate: 'Crown', origin: 'Synths proposal · companion construct', role: 'authority-weight measurer', gift: 'renders the hidden cost of a command as visible counterweight', cost: 'cannot prevent the command from being given', visualDNA: 'cream ceramic body, off-center solar ring, suspended brass weights, sober dark mantle', camera: 'low symmetrical council shot disrupted by one tilted counterweight', emotion: 'moral gravity', cinemaUse: 'decision-room tension visual', contentUses: ['political drama', 'leadership lesson', 'key art'], relationships: ['C33', 'B38', 'P07', 'S37'] }),
  k({ id: 'K32', slug: 'aurin', name: 'Aurin', kind: 'kinform', batch: 7, gate: 'Crown', origin: 'Synths proposal · companion construct', role: 'surplus-light steward', gift: 'redirects excess power toward the least protected participant', cost: 'cannot store power for its own use', visualDNA: 'solar-quartz shoulders, warm metal fins, cream woven torso, broad grounded hands', camera: 'rear three-quarter as light bends past a leader toward distant workers', emotion: 'generosity engineered into form', cinemaUse: 'silent leadership character beat', contentUses: ['brand film', 'ethics visual', 'mascot campaign'], relationships: ['C34', 'B39', 'P07', 'S37'] }),
  k({ id: 'K33', slug: 'solvi', name: 'Solvi', kind: 'kinform', batch: 7, gate: 'Crown', origin: 'Synths proposal · companion construct', role: 'whiteout limiter', gift: 'dims overwhelming brilliance until detail becomes readable again', cost: 'must absorb the glare and becomes temporarily blind', visualDNA: 'matte black face shield, cream shell, folding gold iris, tactile guidance cords', camera: 'silhouette against controlled sun flare, with recovered details emerging around it', emotion: 'protective restraint', cinemaUse: 'transition from spectacle to human consequence', contentUses: ['cinema transition', 'accessibility metaphor', 'poster detail'], relationships: ['C33', 'C34', 'B38', 'S42'] }),

  k({ id: 'K34', slug: 'veyra', name: 'Veyra', kind: 'kinform', batch: 8, gate: 'Starweave', origin: 'Synths proposal · companion construct', role: 'consequence-thread tracer', gift: 'shows which distant system will move when one local choice changes', cost: 'displays connection, never probability', visualDNA: 'slender obsidian body, ghost-steel ribs, trailing prismatic filaments, one asymmetrical hand', camera: 'wide lateral shot with filaments crossing multiple depth planes', emotion: 'awe disciplined by systems thinking', cinemaUse: 'world-scale causality reveal', contentUses: ['cinema keyframe', 'systems map', 'launch visual'], relationships: ['C35', 'B40', 'P08', 'S38'] }),
  k({ id: 'K35', slug: 'tessel', name: 'Tessel', kind: 'kinform', batch: 8, gate: 'Starweave', origin: 'Synths proposal · companion construct', role: 'temporary-form tailor', gift: 'reconfigures its shell for one declared task', cost: 'each new form must sacrifice one prior advantage', visualDNA: 'modular ceramic tiles, black fabric underbody, luminous joint map, elegant tool-tail', camera: 'mid-transformation three-quarter with old and new silhouettes both legible', emotion: 'creative tradeoff', cinemaUse: 'signature transformation moment grounded in consequence', contentUses: ['animation showcase', 'character system', 'maker tutorial'], relationships: ['C36', 'B41', 'P08', 'S43'] }),
  k({ id: 'K36', slug: 'nexi', name: 'Nexi', kind: 'kinform', batch: 8, gate: 'Starweave', origin: 'Synths proposal · companion construct', role: 'phase-lag companion', gift: 'holds a doorway open between two moments long enough for one crossing', cost: 'arrives several heartbeats after everyone else', visualDNA: 'two offset silhouettes linked by violet-black fabric, silver ankle anchors, quiet prism face', camera: 'locked side profile with temporal echo rather than motion blur', emotion: 'loneliness inside useful service', cinemaUse: 'poignant final crossing beat', contentUses: ['short film climax', 'editorial art', 'motion study'], relationships: ['C35', 'C36', 'B40', 'S38'] }),

  k({ id: 'K37', slug: 'duori', name: 'Duori', kind: 'kinform', batch: 9, gate: 'Unity', origin: 'Synths proposal · companion construct', role: 'two-person lift synchronizer', gift: 'aligns distinct movement styles for one shared physical task', cost: 'works only when both participants can stop freely', visualDNA: 'paired but non-identical arms, black-gold torso, silver consent lights, split stance', camera: 'low diagonal action shot between two collaborators', emotion: 'coordination without loss of self', cinemaUse: 'practical teamwork set piece', contentUses: ['ensemble scene', 'collaboration campaign', 'training card'], relationships: ['C37', 'B42', 'P09', 'S39'] }),
  k({ id: 'K38', slug: 'wella', name: 'Wella', kind: 'kinform', batch: 9, gate: 'Unity', origin: 'Synths proposal · companion construct', role: 'disagreement table keeper', gift: 'keeps a shared task active while collaborators hold different views', cost: 'cannot continue if disagreement becomes dehumanization', visualDNA: 'wide table-like back, independent expressive eye clusters, woven work mat, interlocking tool ports', camera: 'overhead ensemble composition with distinct work zones connected through Wella', emotion: 'productive friction', cinemaUse: 'council montage without forced consensus', contentUses: ['community visual', 'workshop poster', 'lore scene'], relationships: ['C38', 'B43', 'P09', 'S44'] }),
  k({ id: 'K39', slug: 'kyth', name: 'Kyth', kind: 'kinform', batch: 9, gate: 'Unity', origin: 'Synths proposal · companion construct', role: 'bond-strain monitor', gift: 'shows where a partnership is compensating rather than cooperating', cost: 'its signal disappears if either person performs harmony for an audience', visualDNA: 'twin silver filaments around a compact black shell, mismatched feet, transparent stress membrane', camera: 'intimate three-shot with the membrane bending between partners', emotion: 'honest concern', cinemaUse: 'relationship turning point before a repair choice', contentUses: ['drama scene', 'bond system explainer', 'character dossier'], relationships: ['C37', 'C38', 'B43', 'S39'] }),

  k({ id: 'K40', slug: 'omi', name: 'Omi', kind: 'kinform', batch: 10, gate: 'Source', origin: 'Synths proposal · companion construct', role: 'origin-question keeper', gift: 'returns any plan to the first promise it was meant to serve', cost: 'offers no answer when the promise was never made', visualDNA: 'clear central core, minimal white-gold limbs, black glass face, one woven memory cord', camera: 'frontal close-wide in an almost empty integration chamber', emotion: 'serene accountability', cinemaUse: 'final-act question that reframes the mission', contentUses: ['film motif', 'strategy visual', 'flagship character'], relationships: ['C39', 'B44', 'P10', 'S40'] }),
  k({ id: 'K41', slug: 'eiren', name: 'Eiren', kind: 'kinform', batch: 10, gate: 'Source', origin: 'Synths proposal · companion construct', role: 'contradiction holder', gift: 'keeps two unresolved truths present without forcing premature synthesis', cost: 'cannot act until a living person chooses the next experiment', visualDNA: 'two clear cores in counter-rotation, sparse gold frame, black woven cradle, balanced asymmetry', camera: 'macro-to-medium rack-focus between the two cores', emotion: 'peace with unfinished understanding', cinemaUse: 'research climax that resists false certainty', contentUses: ['science-fantasy scene', 'knowledge graphic', 'gallery hero'], relationships: ['C40', 'B45', 'P10', 'S45'] }),
  k({ id: 'K42', slug: 'qori', name: 'Qori', kind: 'kinform', batch: 10, gate: 'Source', origin: 'Synths proposal · companion construct', role: 'whole-pattern archivist', gift: 'records how every participant changed the shared outcome', cost: 'erases its own contribution from the record', visualDNA: 'quiet orbital rings, clear faceted body, tiny black-glass feet, gold trace lines from many hands', camera: 'high oblique ensemble shot with Qori near the edge rather than center', emotion: 'service without self-erasure being celebrated', cinemaUse: 'closing tableau and credits motif', contentUses: ['collection finale', 'encyclopedia cover', 'cinema end card'], relationships: ['C39', 'C40', 'P10', 'S45'] }),
];
